### ISSUE TITLE
Spin-monitoring-daemon can't hit metrics endpoint on Gate

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#2016] opened 2017-10-05 23:55 UTC
*Title*

spin-monitoring-daemon can't hit metrics endpoint on Gate when configured via Halyard

*Cloud Provider*

Spinnaker running on Kubernetes deployed via halyard

*Environment*

1.2.2 halyard at least, I don't see anything in 1.2.2 -> 1.4.2 that would have addressed this. I see the same issue on a non-halyard deployed gate instance that we backported the spin-monitoring-daemon to. That gate is running off v4.6.3

*Feature Area*

Spin-monitoring-daemon connecting to gate

*Description*

```
➜  gate git:(master) ✗ kk logs -f spin-gate-v000-kw3bw -n spinnaker-lab -c spin-monitoring-daemon
19:38:09 Loaded config from /opt/spinnaker-monitoring/config/spinnaker-monitoring.yml
19:38:09 Updating catalog from /opt/spinnaker-monitoring/registry at 1507232262
19:38:09 loading /opt/spinnaker-monitoring/registry/gate.yml
19:38:09 gate failed https://localhost/spectator/metrics with <urlopen error [Errno 111] Connection refused>
19:38:09 Collection times 8 (ms): {'gate': 8}
19:38:09 Starting Monitor
19:38:09 Starting HTTP server on host=0.0.0.0, port=8008
```

Here is my hal managed metrics config
```
/opt/spinnaker-monitoring/config # cat spinnaker-monitoring.yml
## WARNING
## This file was autogenerated, and _will_ be overwritten by Halyard.
## Any edits you make here _will_ be lost.

datadog:
  enabled: false
prometheus:
  enabled: true
  add_source_metalabels: true
stackdriver:
  enabled: false
period: 30
enabled: true

server:
  host: 0.0.0.0
  port: 8008

monitor:
  period: 30
  metric_store:
  - prometheus

# halconfig
```

```
/opt/spinnaker-monitoring/registry # cat gate.yml
## WARNING
## This file was autogenerated, and _will_ be overwritten by Halyard.
## Any edits you make here _will_ be lost.

metrics_url: https://localhost/spectator/metrics
```

Relevant part of the gate.yml

```
/opt/spinnaker/config # cat gate.yml
## WARNING
## This file was autogenerated, and _will_ be overwritten by Halyard.
## Any edits you make here _will_ be lost.

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: true
```

*Steps to Reproduce*

Deploy spinnaker via halyard and set up spin-monitoring-daemon as a feature. All the services seem to be working minus gate, I noticed in the gate.yml in the registry folder that the metrics_url is missing the port number for the gate instance. That seems to be part of the problem. Another problem I haven't been able to track down is that the gate process doesn't seem to listen on localhost:8084 or 0.0.0.0:8084 which might be unrelated...

On our non-halyard managed gate install running the spinnaker monitoring sidecar, we do have a well formed metrics_url but are finding that gate is not returning the /spectator/metrics endpoint because it either is protected via auth, or something else weird is going on.

**Comment by lwander** [comment] 2017-10-06 13:21
I think there is some port that can be exposed via spring that listens on localhost and isn't protected via auth...

**Comment by edwinavalos** [comment] 2017-10-06 13:42
I'll be testing 1.4.2 this morning and updating the halyard controlled env to confirm its still broken.

**Comment by edwinavalos** [comment] 2017-10-06 15:54
Still happening in 1.4.2,

```
➜  tgt-halyard git:(master) kk logs -f spin-gate-v000-c1b6s -n spinnaker-lab -c spin-monitoring-daemon
14:14:38 Loaded config from /opt/spinnaker-monitoring/config/spinnaker-monitoring.yml
14:14:38 Updating catalog from /opt/spinnaker-monitoring/registry at 1507299214
14:14:38 loading /opt/spinnaker-monitoring/registry/gate.yml
14:14:38 gate failed https://localhost/spectator/metrics with <urlopen error [Errno 111] Connection refused>
14:14:38 Collection times 7 (ms): {'gate': 4}
14:14:38 Starting Monitor
14:14:38 Starting HTTP server on host=0.0.0.0, port=8008
```

**Comment by ttomsu** [comment] 2017-10-12 13:57
@lwander The spectator endpoint is not part of the Spring management endpoints. It's a normal controller, like any of the other Application controllers.

Based on this error:

> 14:14:38 gate failed https://localhost/spectator/metrics with <urlopen error [Errno 111] Connection refused>

It looks like `localhost` needs the port included.

**Comment by edwinavalos** [comment] 2017-10-16 13:39
@ttomsu in our backported instance of the monitoring daemon against HEAD on Gate it was still experiencing the issue when I filed the ticket. It was correctly specified to hit localhost:8084 which is the port that gate was running in the other pod. I think I'm going to try and figure this one out this week.

**Comment by benjaminws** [comment] 2018-02-14 21:50
👋 I'm seeing this in nightly builds of spinnaker

**Comment by nfirvine** [comment] 2018-03-19 23:16
I'm seeing this too. Some observations:

https://github.com/spinnaker/spinnaker-monitoring/blob/master/spinnaker-monitoring-daemon/registry.dev/gate.yml
^ this example is correct

However, the registry for gate generated by halyard is wrong:

```
metrics_url: https://localhost/spectator/metrics
```

My gate base URL is the external URL, which is `https`, and has no port.

I suspect the cause is here https://github.com/spinnaker/halyard/blob/master/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/MetricRegistryProfileFactoryBuilder.java#L64 and relates to Spinnaker's general confusion about internal vs external URLs. cf. https://github.com/spinnaker/spinnaker/issues/2524

I'm going to see if I can figure out how to override it, but considering it's an obscure generated file, I'm not holding my breath.

**Comment by nfirvine** [comment] 2018-03-20 20:31
I'd argue that if the monitoring-daemon pod can't scrape metrics for 100% of the things it's supposed to be scraping, it should be failing its health check

**Comment by nfirvine** [comment] 2018-03-20 20:36
Another problem is that gate requires auth for `/spectator/metrics` if auth is enabled, including from `localhost`, and it ends up issuing redirects to `/login`

**Comment by nfirvine** [comment] 2018-03-20 22:16
I tried writing my own `spinnaker-monitoring` pod with the correct URL. Unfortunately, the fact that `/spectator/metrics` lives behind auth is a show stopper. I suppose I could try to give `spinnaker-monitoring` a service account, but that seems like a lot of work, and unlikely to be supported. I'm out of ideas.

**Comment by iniinikoski** [comment] 2018-04-05 22:32
Ha, just bumped into this... I only changed the config of Gate regarding SAML - and kaboom... 

I see this one as well:

```
22:28:48 gate failed https://localhost/spectator/metrics with <urlopen error [Errno 111] Connection refused>
````
What puzzles me why haven't I seen this before...

**Comment by ttomsu** [comment] 2018-04-12 17:48
@lwander - what say you to giving this to one of our new guys to turn into a proper Spring Management endopoint? As part of that work, I'd suggest making Halyard turn the management endpoints to a different port than the service's (say, 9050).

**Comment by lwander** [comment] 2018-04-12 18:11
:+1:

**Comment by sweetib** [comment] 2018-05-17 09:00
do we have any solution for this issue yet?

**Comment by benjaminws** [comment] 2018-08-08 23:48
I worked around this in an uncreative way, but wanted to share.

1. Enable basic auth in gate
2. Set `metrics_url` in `/opt/spinnaker-monitoring/registry/gate.yml` to use the user/pw e.g. `metrics_url: http://user:pass@localhost:8084/`

note that this isn't great because it turns on basic auth, which some may not be able to do. also you could generate a client cert if you're using x509...

**Comment by danielpeach** [comment] 2018-08-09 01:07
This was fixed here: https://github.com/spinnaker/halyard/pull/950

Not sure which Halyard version it was released with.

**Closed by danielpeach** 2018-08-09 01:07 UTC
Labels: auth, beginner friendly, bug, enhancement

**Comment by seanpeters86** [comment] 2018-11-12 18:37
@danielpeach Following up from this, we just got around to checking if this fixed our issue (same team as `edwinavalos` above...and after upgrading to 1.6 we started to see this:

```
/usr/local/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/local/lib/python2.7/site-packages/google': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
15:36:38 Loaded config from /opt/spinnaker-monitoring/config/spinnaker-monitoring.yml
15:36:38 Updating catalog from /opt/spinnaker-monitoring/registry at 1542036995
15:36:38 loading /opt/spinnaker-monitoring/registry/gate.yml
15:36:38 gate failed https://localhost:8084/spectator/metrics with <urlopen error [Errno 111] Connection refused>
15:36:38 Collection times 2 (ms): {'gate': 2}
15:36:38 Starting HTTP server on host=0.0.0.0, port=8008
15:36:38 Starting Monitor
15:37:22 gate failed https://localhost:8084/spectator/metrics with <urlopen error [Errno 111] Connection refused>
15:37:22 Collection times 2 (ms): {'gate': 1}
15:38:22 gate failed https://localhost:8084/spectator/metrics with <urlopen error [Errno 111] Connection refused>
15:38:22 Collection times 1 (ms): {'gate': 1}
15:39:22 gate failed https://localhost:8084/spectator/metrics with HTTP Error 401: Unauthorized
```

We tried a few things and eventually added `basicAuthEnabled: true` into our gate.yml and then saw this again:

```
/usr/local/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/local/lib/python2.7/site-packages/google': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
17:09:24 Loaded config from /opt/spinnaker-monitoring/config/spinnaker-monitoring.yml
17:09:24 Updating catalog from /opt/spinnaker-monitoring/registry at 1542042556
17:09:24 loading /opt/spinnaker-monitoring/registry/gate.yml
17:09:24 gate failed https://null:null@localhost:8084/spectator/metrics with <urlopen error [Errno 111] Connection refused>
17:09:24 Collection times 2 (ms): {'gate': 2}
17:09:24 Starting HTTP server on host=0.0.0.0, port=8008
17:09:24 Starting Monitor
17:09:43 gate failed https://null:null@localhost:8084/spectator/metrics with <urlopen error [Errno 111] Connection refused>
```

Do we need to set username/password somewhere for this? Looked through the docs and couldn't find anywhere that we could do this securely outside of just adding it to the service.yml. Alternatively if we don't need basicAuth enabled is there something else we need to add in halyard for this?

**Comment by ttomsu** [comment] 2018-11-12 18:53
@seanpeters86 - Try adding

```
basicAuthEnabled: true
username: foo
password: bar
```

The fields are undocumented, but the code supports them: https://github.com/spinnaker/halyard/blob/master/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceSettings.java#L52-L53

Note: this currently doesn't work if you're using LDAP as the authentication provider - fix for that is here, (but could use validation): https://github.com/spinnaker/gate/pull/664

**Comment by seanpeters86** [comment] 2018-11-12 19:36
That did the trick! Only question we have is what (if any) security concerns are there with this user/pass combination. Quick inspection makes me believe that this is only allowing access to the endpoint via localhost, so it should be fine but any insight you can give here would be helpful.

Thanks! @ttomsu

**Comment by diasjorge** [comment] 2019-04-01 17:00
@seanpeters86 I've tested the workaround and this enabled basic authentication from the external urls too.
