### ISSUE TITLE
In experimental/Kubernetes/simple, updating config with update-config.sh deletes all configuration files

### ISSUE THREAD

**Issue by petetnt** [spinnaker/spinnaker#1140] opened 2016-09-13 13:51 UTC
## Environment

Spinnaker on Kubernetes on AWS, brought up with https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple

## Description

The [README.md](https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple) claims the following:

> Any time you want changes that you made to the config files to show up in Spinnaker, you need to run
>
> ``` 
>$ bash scripts/update-config.sh # this recreates the secrets described above
> $ bash scripts/update-component.sh <component name> # for each component whose config you touched
> ```
> The only files you should change are the -local.yml files, the rest are pulled in by the update-config.sh script, and will overwrite any local changes you have.

Most of which seems to be untrue, considering that `update-config.sh` first (correctly) deletes the secrets and then preceeds to `rm` `config/*.yaml`

``` sh
CONF_DIR=../../../config/

for FILENAME in $CONF_DIR*.yml; do
    if [ ${FILENAME:${#CONF_DIR}} != "default-spinnaker-local.yml" ]; then
        rm config/${FILENAME:${#CONF_DIR}}
    fi
done
```

which most likely isn't wanted behavior. `update-config.sh` also doesn't pull anything in, it just proceeds to run `startup-config.sh` which depends on the files `cleanup-config.sh` just deleted.

Obviously the branch is tagged `experimental` and I should know better than to run potentially destructive commands before actually looking at the files it runs 💇 ...

## Steps to Reproduce

1. Clone the `kubernetes/simple` sample from https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple
2. Make changes to your `-local.yml` configuration files under `./config`
3. Run `scripts/update-config.sh`
4. Notice all of your config files being deleted

**Comment by ajordens** [comment] 2016-10-06 03:15
Thoughts @lwander?

**Comment by lwander** [comment] 2016-10-06 13:28
I can't reproduce. That block of code deletes every non `-local.yml` config file, you're likely making changes to the non`-local.yml` config, which is checked in, versioned, and likely to be overwritten.

**Closed by lwander** 2016-10-06 13:28 UTC

**Comment by lwander** [comment] 2016-10-06 13:32
Since the documentation isn't clear about this, I submitted a fix to the docs you can see linked above.

**Comment by petetnt** [comment] 2016-10-06 13:38
I **didn't** edit any wrong files that's for sure, I think the issue was more on how  `make` handles paths and how the scripts rely on relative paths which made the check evaluate `true` every time. You can blame that on user error for sure, sorry about that.

**Comment by petetnt** [comment] 2016-10-06 13:40
Not sure why deleting _anything_ is needed in the first place though? The README.md claims that they are overwritten anyway.

**Comment by lwander** [comment] 2016-10-06 13:52
Where does `make` come in? 

If that check evaluates to `true`, it will delete a file matching the name it found in whatever relative path it's searching, not every file. In fact, it should be pretty noisy about not finding any of the correct config files in that path.

If you were to overwrite a file, how would you go about doing it without effectively deleting the old copy?

**Comment by petetnt** [comment] 2016-10-06 14:09
The `make` is part of our own internal build processes, not related to the `kube` spinnaker config directly. TL;DR: it's a script that drives the scripts under `scripts/` while doing other things.

My point was that if you overwrite files regardless, why do you need to delete them first? No scripts doing arbitrary `rm`s, no chance of something failing in between 🎱. 

The failure was my fault for sure, I can't deny that. It's was unfortunate, but those things do happen every now and then. Remember when [Steam on Linux `rm -rf`'d everything owned by user](https://github.com/valvesoftware/steam-for-linux/issues/3671)?

**Comment by lwander** [comment] 2016-10-06 14:19
I see - I leaned toward deleting before replacing to ensure no errant config gets through the cracks, but you bring up a valid point. If you have the time, I'd be happy to merge a PR changing this behavior.

In a few weeks these scripts will deprecated in a favor of a more robust way to configure & update Spinnaker: https://github.com/spinnaker/halyard

**Comment by petetnt** [comment] 2016-10-06 14:21
Cool! Can't wait for `halyard` myself! Thanks for your replies @lwander and have a nice week!
