### ISSUE TITLE
runJob stage broken for Kubernetes V1 provider

### ISSUE THREAD

**Issue by CommanderPrS** [spinnaker/spinnaker#3916] opened 2019-01-31 01:16 UTC
### Issue Summary:

It is not possible to use the `runJob` stage with the Kubernetes V1 provider without editing the stage JSON manually to change the provider type from `titus` to `kubernetes` and to replace the entire `"cluster": {...}` key with an empty `"clusters": []` key (see below for more details).

### Cloud Provider(s):

Kubernetes V1 provider.

### Environment:

Spinnaker 1.12.0 running in GKE.

### Feature Area: 

The `runJob` stage in pipelines.

### Description:

First, right after adding a new `runJob` stage in a pipeline, the box with the list of accounts is empty:

![image](https://user-images.githubusercontent.com/14830158/52022978-28458700-24b0-11e9-8065-19daaf83a64a.png)

This is caused by the wrong provider type in the JSON:

![image](https://user-images.githubusercontent.com/14830158/52023009-4b703680-24b0-11e9-8734-23660672c469.png)

Changing `titus` to `kubernetes` in the stage JSON unblocks the UI and it is possible to configure the stage as required. However, the stage fails when the pipeline is executed with the `Cannot get property 'imageDescription' on null object` error:

![image](https://user-images.githubusercontent.com/14830158/52023066-87a39700-24b0-11e9-881b-be837b69efff.png)

Here is the corresponding stack trace from the pipeline JSON:

```
java.lang.NullPointerException: Cannot get property 'imageDescription' on null object
org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
com.netflix.spinnaker.orca.clouddriver.tasks.providers.kubernetes.KubernetesContainerFinder$_populateFromStage_closure1.doCall(KubernetesContainerFinder.groovy:68)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
groovy.lang.Closure.call(Closure.java:418)
org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
com.sun.proxy.$Proxy147.accept(Unknown Source)
java.util.ArrayList.forEach(ArrayList.java:1257)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:213)
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
com.netflix.spinnaker.orca.clouddriver.tasks.providers.kubernetes.KubernetesContainerFinder.populateFromStage(KubernetesContainerFinder.groovy:67)
com.netflix.spinnaker.orca.clouddriver.tasks.providers.kubernetes.KubernetesContainerFinder$populateFromStage.call(Unknown Source)
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
com.netflix.spinnaker.orca.clouddriver.tasks.providers.kubernetes.KubernetesJobRunner.getOperations(KubernetesJobRunner.groovy:47)
com.netflix.spinnaker.orca.clouddriver.tasks.job.JobRunner$getOperations.call(Unknown Source)
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
com.netflix.spinnaker.orca.clouddriver.tasks.job.RunJobTask.execute(RunJobTask.groovy:65)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:100)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:311)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:99)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:97)
com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:98)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:182)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:49)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:33)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:59)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:33)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:68)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:55)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:42)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:175)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:56)
com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:56)
com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

To get rid of this error, one needs to go back to the stage JSON and remove the `"cluster": {...}` key:

![image](https://user-images.githubusercontent.com/14830158/52023449-02b97d00-24b2-11e9-9c2e-80b2ca7ba8e4.png)

This is the correct JSON:

![image](https://user-images.githubusercontent.com/14830158/52023532-4613eb80-24b2-11e9-93f6-98b10b6dd1cd.png)

After that the pipeline succeeds as expected:

![image](https://user-images.githubusercontent.com/14830158/52023622-ac007300-24b2-11e9-9a6b-456e000050cd.png)

**Comment by sbwsg** [comment] 2019-02-06 20:03
This appears to be a duplicate of https://github.com/spinnaker/spinnaker/issues/3879 and will require some work to change the way stages are created.

**Closed by sbwsg** 2019-02-06 20:03 UTC
Labels: bug, provider/kubernetes-v1
