### ISSUE TITLE
Jenkins stage not invoking job

### ISSUE THREAD

**Issue by bfarrell** [spinnaker/spinnaker#2845] opened 2018-05-29 20:44 UTC
### Issue Summary:
When running a Jenkins stage, stage is not executing correctly.

### Cloud Provider(s):
AWS
K8s

### Environment:
Spinnaker 1.7.6 on local K8s

### Feature Area: 
Jenkins Stage

### Description:
Ive tried connecting to a couple different Jenkins boxes I have.  I can pull the jobs successfully but running a job it either goes into 1 of 4 actions
a.  Pipeline immediately fail - No StageDefinitionBuilder implementation for jenkins found
b.  Pipeline gets marked successful and Jenkins stage gets marked skipped
c.  Stage goes into running state (pipeline blue) but shows Terminal for pipeline
d.  Rarely, actually runs the Jenkins job but then marks it failed even though the job was successful

I have another Spinnaker stack that is successfully connecting to the same Jenkins and running jobs but it is on version 1.7.1.

### Steps to Reproduce:
1. Create a new pipeline
2. Add a Jenkins stage
3. Choose Jenkins job to run
4. Save pipeline
5. Invoke pipeline

### Additional Details:

Here is the exception log when it immediately fails:
2018-05-29 20:34:57.028  INFO 1 --- [    scheduler-3] com.netflix.spinnaker.q.QueueProcessor   : [] Received message CancelStage(executionType=pipeline, executionId=0ef8ccde-d5cb-4d61-a308-6a660e37d194, application=mytestapp, stageId=a0d79ecc-fb7a-438f-94aa-8ffb747c3049)
2018-05-29 20:34:57.033  INFO 1 --- [    handlers-18] c.n.s.orca.igor.pipeline.JenkinsStage    : [] Cancelling stage (stageId: a0d79ecc-fb7a-438f-94aa-8ffb747c3049, executionId: 0ef8ccde-d5cb-4d61-a308-6a660e37d194, context: [failPipeline:true, job:testbf, parameters:[:], continuePipeline:false, master:JenkinsCaaS, exception:[timestamp:1527626097001, exceptionType:NoSuchStageDefinitionBuilder, operation:Jenkins, details:[stackTrace:com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for jenkins found
	at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$1(DefaultStageDefinitionBuilderFactory.java:43)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:43)
	at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:136)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$55f02348.call(AuthenticationAware.kt)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:79)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:57)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:31)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:66)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:53)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:65)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:48)
	at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
	at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, error:Unexpected Task Failure, errors:[No StageDefinitionBuilder implementation for jenkins found]], shouldRetry:false]])
2018-05-29 20:34:57.034  INFO 1 --- [    handlers-18] c.n.spinnaker.orca.igor.IgorService      : [] ---- ERROR 
2018-05-29 20:34:57.035  INFO 1 --- [    handlers-18] c.n.spinnaker.orca.igor.IgorService      : [] java.lang.IllegalArgumentException: Path parameter "queuedBuild" value must not be null.
	at retrofit.RequestBuilder.setArguments(RequestBuilder.java:242)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:298)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy110.stop(Unknown Source)
	at com.netflix.spinnaker.orca.igor.BuildService.stop(BuildService.groovy:41)
	at com.netflix.spinnaker.orca.igor.BuildService$stop.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at com.netflix.spinnaker.orca.igor.tasks.StopJenkinsJobTask.execute(StopJenkinsJobTask.groovy:46)
	at com.netflix.spinnaker.orca.Task$execute.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.netflix.spinnaker.orca.igor.pipeline.JenkinsStage.cancel(JenkinsStage.groovy:63)
	at com.netflix.spinnaker.orca.q.handler.CancelStageHandler$handle$1$$special$$inlined$let$lambda$1.run(CancelStageHandler.kt:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ezimanyi** [comment] 2018-05-30 17:52
It seems that somehow Orca is not correctly autowiring the list of stages on startup, as it can't find a `StageDefinitionBuilder` for Jenkins even though there is one defined.  This looks similar to another error reported by the same user where pipelines are not saving because Orca can't find a class to handle tasks of `savePipeline`.  I'm not sure *why* this autowiring is not working, but I suspect that's the cause of both issues.

**Comment by bfarrell** [comment] 2018-05-31 13:10
I moved from my external redis to the halyard deployed redis yesterday and this problem went away.  Im wondering if tasks were just getting lost.  Doesnt necessarily explain the exception above but could explain the other potential paths my executions were going.  I had used this comment to setup the external redis through halyard but not sure if I am missing something.  Thought it was working as history was being saved correctly.

https://github.com/spinnaker/spinnaker/issues/2034#issuecomment-337248475

**Comment by ezimanyi** [comment] 2018-06-04 19:42
@bfarrell : I'm baffled as to how the particular Redis being used could have caused the above issue, but glad it's working now.  I'll close this now, but feel free to re-open if you see this behavior again.

**Closed by ezimanyi** 2018-06-04 19:42 UTC
Labels: bug, component/orca, help wanted

**Comment by lwander** [comment] 2018-06-04 19:46
It seems an overloaded redis causes all sorts of problems -- people have also had trouble saving pipelines recently. We've added these pages to help with this: https://www.spinnaker.io/setup/productionize/caching/externalize-redis/

**Comment by lluu** [comment] 2019-01-16 23:52
@ezimanyi  i'm running into a similiar issue that bfarrell ran into, mine is for Manual Judgement stage.  I'm running Spinnaker 1.10
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$**NoSuchStageDefinitionBuilder**: No StageDefinitionBuilder implementation for manualJudgment found\n\tat com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$1(DefaultStageDefinitionBuilderFactory.java:43)\n\tat java.util.Optional.orElseThrow(Optional.java:290)\n\tat com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:43)\n\tat com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:139)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)\n\tat com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:94)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:65)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)\n\tat com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n

I have two Spinnaker swimlanes running the same exact Spinnaker code, Manual Judgement stage works on one, but not the other.  The only difference between the two is the external redis that they're using.. so reading bfarrell's resolution, i thought clear redis cache would solve my issue.. unfortunately it didn't.  The trouble swimlane had a very large redis cache, but i cleared it, all history are gone.. and manual judgment is still not working..   I continue to get the stack trace above.  Because it's working on one swimlane, i don't think the issue is with the code.. i copied the pipeline json from the working swimlane to the problematic one, so the pipeline definition is identical.. so the issue can't be the json defintion.  **Can you pls shed some light on where else i can investigate?**  orca log shows:

2019-01-16 22:46:28.208  INFO 7495 --- [    scheduler-7] com.netflix.spinnaker.q.QueueProcessor   : [] Received message StartStage(executionType=pipeline, executionId=01D1CDGAJWA89VD529T4W9T36X, application=regression, stageId=01D1CDGAJW9V304S96NTYKM3KB)
2019-01-16 22:46:28.211  WARN 7495 --- [    handlers-20] c.n.s.o.e.DefaultExceptionHandler        : [] Error occurred during task Manual Judgment
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for manualJudgment found
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$1(DefaultStageDefinitionBuilderFactory.java:43)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:43)
        at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:139)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:94)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:65)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:48)
        at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
        at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-01-16 22:46:28.211 ERROR 7495 --- [    handlers-20] c.n.s.orca.q.handler.StartStageHandler   : [] Error running manualJudgment stage for pipeline[01D1CDGAJWA89VD529T4W9T36X]
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for manualJudgment found
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$1(DefaultStageDefinitionBuilderFactory.java:43)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:43)
        at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:139)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:94)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54)
