### ISSUE TITLE
Generated JSON for Deploy Manifest Seems Incorrect

### ISSUE THREAD

**Issue by bgreeleyquibi** [spinnaker/spinnaker#5460] opened 2020-02-18 18:35 UTC
### Issue Summary:
When I create a new pipeline with bake and deploy stages via Deck, I'm getting the following error in the UI when I execute the pipeline.
```
Exception ( Deploy Manifest )
No manifest artifact account was specified.
```

### Cloud Provider(s):
GCP

### Environment:
Spinnaker 1.18.2
Halyard 1.31.1

### Feature Area:
Pipelines
UI

### Description:
I'm expecting that Deck would generate the correct JSON for the Deploy Manifest stage, but it is not.

### Steps to Reproduce:
1. Create a pipeline with an expected Docker artifact
2. Add a bake stage for packaging manifests via Kustomize
3. Add a deploy manifest stage that binds the Docker artifact with baked manifests.

### Additional Details:
I was able to get around this by reviewing my previous Spinnaker instance and doing a diff of my Deploy Manifest stage and adding the following line that looks like it was missing:
```
"manifestArtifactAccount": "embedded-artifact",
```

**Comment by duftler** [comment] 2020-02-18 20:20
What version of Spinnaker are you running for the previous Spinnaker instance?

**Comment by bgreeleyquibi** [comment] 2020-02-18 20:21
> What version of Spinnaker are you running for the previous Spinnaker instance?

1.16.0

**Comment by duftler** [comment] 2020-02-26 16:09
Hi Brandon,

Have worked through this in detail now, and was able to reproduce the issue you reported.

It can be resolved by following the "updating" instructions here: https://www.spinnaker.io/guides/user/kubernetes-v2/kustomize-manifests/#updating-116-bake-manifest-stage-for-117

Took a while to figure out what was going on, but I'm confident that will resolve the issue.

@maggieneterval Pointed out several other things as we were troubleshooting. The screen grabs in those docs assume the operator has enabled the `artifactsRewrite` feature flag in deck. I enabled that flag and the configuration was much more straightforward than before.

If you don't already have it enabled, you can enable it by adding it to your `~/.hal/default/profiles/settings-local.js` file in cloud shell. Here is what mine looks like:

```
$ cat ~/.hal/default/profiles/settings-local.js
window.spinnakerSettings.feature.artifactsRewrite = true;
window.spinnakerSettings.feature.kustomizeEnabled = true;
```

We would like to clean up the artifact configuration story in deck and not have multiple paths to choose from. We'd be very interested in hearing your feedback after you have a chance to try out this different configuration experience.

We can also enable it by default for Spinnaker for GCP, but let's first confirm that it resolves your problem.

**Comment by maggieneterval** [comment] 2020-03-04 19:01
Hi @bgreeleyquibi -- please let us know if you are still experiencing this issue after enabling `artifactsRewrite` so we can investigate further. Definitely keep us posted on any additional friction you encounter while configuring artifacts. Thanks!

**Closed by maggieneterval** 2020-03-04 19:01 UTC
Labels: sig/kubernetes
