### ISSUE TITLE
After a rollout is paused, no resume rollout option

### ISSUE THREAD

**Issue by romil-punetha** [spinnaker/spinnaker#4996] opened 2019-10-02 10:24 UTC
### Issue Summary:
During a rollout, I chose the deployment and did a pause rollout. However, when I wanted to resume it, there was no resume rollout option.

### Cloud Provider(s):
EKS : 1.13

### Environment:
Halyard: 1.24 (using the nightly image build which is the latest one)
Spinnaker: 1.16.0

### Steps to Reproduce:
During a rollout, under infrastructure, click on pause rollout. In the same dropdown, there's no resume rollout option

**Comment by maggieneterval** [comment] 2019-10-16 19:01
Hi @romil-punetha, thanks for taking the time to open this issue!

I'm not able to reproduce this problem after taking the following steps:

1. Deploy a Deployment resource using Spinnaker's Deploy (Manifest) stage.
2. While the Deployment is still in the process of becoming stable, go to Spinnaker's Infrastructure tab and click "Pause Rollout" from the Deployment Actions dropdown.
3. The "Resume Rollout" option appears as expected in the Deployment Actions dropdown.

According to the [code](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html#L56), the "Resume Rollout" button should appear whenever the manifest's status is reported as paused. Are you able to verify that:
1. Your Deployment's manifest's `spec.paused` is set to `true` (can verify this by running `kubectl get deployment {your_deployment_name} -o yaml | grep paused`)
2. Spinnaker is correctly reporting this status (can check the response to `{your_gate_endpoint}/manifests/{your_account_name}/{your_namespace}/deployment%20{your_deployment_name}` from the browser console when opening the details sidebar and ensure that `status.paused.state` is `true`).

**Comment by maggieneterval** [comment] 2019-10-23 18:31
Hi @romil-punetha, hope all is well! I'm going to close this issue for now since I haven't been able to reproduce it, but if you're still able to reproduce it and can provide any further details per my previous comment, please feel free to re-open. Thank you!

**Closed by maggieneterval** 2019-10-23 18:31 UTC
Labels: enhancement, provider/kubernetes-v2, sig/kubernetes
