### ISSUE TITLE
spinnaker shows non-existent tags in UI

### ISSUE THREAD

**Issue by babinin** [spinnaker/spinnaker#5737] opened 2020-05-05 10:26 UTC
### Issue Summary:
Clouddriver with MySQL did not removing non-existent docker tags from database

### Feature Area:
Clouddriver/Cats/Sql

At the moment, we have 9 tags in our repository but there are 20 in clouddriver.cats* (same in UI)

<img width="966" alt="Screenshot 2020-05-05 at 13 15 24" src="https://user-images.githubusercontent.com/17936209/81056238-d8374a80-8ed2-11ea-86c3-108108c36f09.png">

(oldest image is 20.04.13-12.59)

mysql> SELECT * FROM clouddriver.cats_v1_imageId WHERE id LIKE '%ads-3rd-party-stats%';
+----------------------------------------------------------------------------------+
| id                                                                               |
+----------------------------------------------------------------------------------+
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.07.12-07.52 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.07.12-08.03 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.07.12-08.24 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.09.02-14.14 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.10.09-12.13 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.11.01-15.33 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.11.04-15.22 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:19.12.13-12.48 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.03.10-13.01 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.13-12.59 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.13-13.26 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.14-07.00 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.14-09.16 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.16-07.13 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.16-14.51 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.30-11.31 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.30-11.49 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.04.30-12.33 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.05.05-08.02 
| dockerRegistry:imageId:index.docker.io/loopme/ads-3rd-party-stats:20.05.05-08.19 
+----------------------------------------------------------------------------------+
20 rows in set (0.00 sec)

**Comment by ealebed** [comment] 2020-06-17 12:02
any updates?

**Comment by maggieneterval** [comment] 2020-07-17 13:51
Hey @babinin and @ealebed, thanks for reporting this one! A fix will be released with Spinnaker 1.22, which is currently scheduled for mid-August.

The cause of the non-existent tags showing up in the UI was that we were never clearing deleted tags from Clouddriver's cache. This is because the caching agent responsible for Docker tags was `informative` rather than `authoritative`, meaning the tags it was caching were not considered the full set of existing tags. This behavior actually was intentional based on [this PR](https://github.com/spinnaker/clouddriver/pull/1132) from 2016 "to prevent images from being deleted", but unless there's something I'm totally missing, I think we want the Docker image caching agent to to authoritative so that deleted images get deleted. I've tested the fix on my dev setup and all seems to be working as expected, but definitely let me know if you notice any regressions.

**Closed by maggieneterval** 2020-07-17 13:51 UTC
Labels: sig/kubernetes
