### ISSUE TITLE
No credentials registered to handle Artifact [Docker

### ISSUE THREAD

**Issue by dylanjohnsonsfo** [spinnaker/spinnaker#2959] opened 2018-06-27 01:38 UTC
### Issue Summary:

No credentials registered to handle Artifact(type=docker/image, name=us.gcr.io/kubernetes-production-201717/ops-api, version=b0c831746196824eaeb595f85a5e597b8f9f16ac, location=null, reference=us.gcr.io/kubernetes-production-201717/ops-api:b0c831746196824eaeb595f85a5e597b8f9f16ac, metadata=null, artifactAccount=embedded-artifact, provenance=null, uuid=null)

### Cloud Provider(s):

Google 

### Environment:

K8S 

### Feature Area: 

 Pipelines 

### Description:

Seems like my pipeline is having auth issues with GCR. I know the GCR creds are ok as I can browse the registry when setting up a Docker trigger. Problem is when I use the Docker trigger, it fires when a new image is available but then I get this Authentication issue when trying to the use the image artifact. 

### Steps to Reproduce:

Setup a docker trigger with an expected artifact of type docker image then try to bind that in the

**Comment by sbwsg** [comment] 2018-06-27 12:22
It looks as though the Expected Artifact you've setup in your pipeline's stage is configured with the default "embedded-artifact" artifact account, which won't include your credentials for GCR.

In your pipeline, where you've used the artifact, you should see a dropdown called "Artifact Account" that can be used to set the correct credentials.  Here's a screenshot from one of my stages that includes an Expected Artifact:

<img width="320" alt="screen shot 2018-06-27 at 8 16 39 am" src="https://user-images.githubusercontent.com/34253460/41973400-df546340-79e2-11e8-845f-7518543b8047.png">

Here you can see both the default "embedded-artifact" account listed as well as one called "gcs-artifact-account" that I would selected for my docker image artifact.

If you haven't yet configured an artifact account for your GCR artifacts then the command to use would be `hal config artifact gcs account add` (more info here: https://www.spinnaker.io/reference/halyard/commands/#hal-config-artifact-gcs-account-add)

**Comment by dylanjohnsonsfo** [comment] 2018-06-27 15:59
@sbwsg Hi , thanks for helping me out here. I did set the artifact account to the gcs-artifact one, the one i already configured with hal. I knw its working as I mentioned before as I can browse images via the UI. I still get the error on the Deploy manifest stage 

```
Exception ( Deploy Manifest )
No credentials registered to handle Artifact(type=docker/image, name=us.gcr.io/kubernetes-production-201717/ops-api, version=11b37d6151bd991862b75763cacd5aaf52a561e8, location=null, reference=us.gcr.io/kubernetes-production-201717/ops-api:11b37d6151bd991862b75763cacd5aaf52a561e8, metadata=null, artifactAccount=jhh-github-artifact-account, provenance=null, uuid=null)
```

**Comment by dylanjohnsonsfo** [comment] 2018-06-27 16:09
I get a different error on the deploy stage now though. 

```Exception ( Monitor Deploy )
The following artifacts could not be bound: '[Artifact(type=docker/image, name=us.gcr.io/kubernetes-production-201717/ops-api, version=957e4ac9a05083b8fe0c2621cd38592cd8a791f2, location=null, reference=us.gcr.io/kubernetes-production-201717/ops-api:957e4ac9a05083b8fe0c2621cd38592cd8a791f2, metadata=null, artifactAccount=null, provenance=null, uuid=null)]' . Failing the stage as this is likely a configuration error.```

**Comment by lwander** [comment] 2018-06-27 17:06
That's good news -- does your manifest have the field "image: us.gcr.io/kubernetes-production-201717/ops-api" in the container spec? The artifact substitution is done by name, to allow the tag/digest to be resolved dynamically.

**Comment by lwander** [comment] 2018-06-27 17:10
Also, I see you're listing the GH file (the manifest) as a required artifact to bind. This won't work as the manifest itself is what the other artifacts are being bound to. You can treat "Req. artifacts to bind" as a safety precaution to fail when a docker image or configmap wasn't correctly bound.

**Comment by dylanjohnsonsfo** [comment] 2018-06-28 02:00
@lwander @sbwsg Thanks for the help guys, I finally got it working thanks to you! Now i need to work out the Canary setup configurations :) 👍

**Comment by dylanjohnsonsfo** [comment] 2018-06-28 02:01
@lwander @sbwsg Do you have any example configs for the Canary. I have it working kind of, problem is the type is gce-instance so the metrics are the same for the control/experiment :)

**Comment by lwander** [comment] 2018-06-28 12:05
@andreasevers wrote a great guide for the v1 provider (is applicable to v2 as well) for canary: https://ordina-jworks.github.io/cloud/2018/06/01/Automated-Canary-Analysis-using-Spinnaker.html -- maybe this can help?

**Comment by lwander** [comment] 2018-06-28 12:06
In any case, since the issue is resolved I'll close this -- feel free to open another issue if you run into trouble with canary

**Closed by lwander** 2018-06-28 12:06 UTC
Labels: artifacts, provider/kubernetes-v2
