### ISSUE TITLE
Dev instance credentials not working

### ISSUE THREAD

**Issue by radkin** [spinnaker/spinnaker#810] opened 2016-03-17 21:56 UTC
When starting a local development instance on a mac the account is not showing for a google service account that has been added via environment variables.

Details: 

All services are starting and showing "up" when checking health URLs. Builds look okay; however, Gate is not starting with everything else and requires another start after the others are running. 

The environment variables are as follows

```bash
env | grep SPINN
SPINNAKER_GOOGLE_ENABLED=true
SPINNAKER_GOOGLE_DEFAULT_REGION=us-central1
SPINNAKER_HOME=/Users/username/workspace/Spinnaker
SPINNAKER_GOOGLE_PROJECT_CREDENTIALS_PATH=/Users/username/.spinnaker/google-cloud-secret.json
SPINNAKER_GOOGLE_DEFAULT_ZONE=us-central1-b
SPINNAKER_GOOGLE_PROJECT_ID=our-project-name
```

Tried it with quotes and without. Confirmed there is no 
`/Users/username/.spinnaker/spinnaker-local.yml `
file

curl localhost:7002/credentials
[] 

Tried adding a spinnaker-local.yml with settings in there but had the same issue. Is there an easy way to increase log verbosity and see what is happening? Checked all the logs and the messages look the same on the local development instance as they do on a fully functional Ubuntu machine in GCE. Confirmed all services are running as "user" and not root.

*note*: had to use jdk1.8_31 as other versions had strange errors and didn't build cleanly. Found the correct version on a travis build for spinnaker and used it.

**Comment by duftler** [comment] 2016-03-17 22:00
@ewiseblatt

**Comment by ewiseblatt** [comment] 2016-03-18 01:59
I'm not sure SPINNAKER_HOME is real. I've never seen that before. It should be HOME.
Try curl localhost:7002/env. 

Make sure /Users/username/.spinnaker/google-cloud-secret.json is readable by the process running spinnaker. It should be chmod 600 (and spinnaker run as "username") for security.

It turns out that $HOME/.spinnaker/spinnaker-local.yml is probably not consulted. I say "probably" because it isnt by debian packages, but you are on a mac so not sure what your script looks like. The debian install only reads from /opt/spinnaker/config, so put your spinnaker-local.yml there.

Let me know if this helps.

**Comment by radkin** [comment] 2016-03-18 17:45
After some experimentation I figured out that the mac dev environment is looking to the config dir that is used when you start it with (in build) `../spinnaker/dev/run_dev.sh`

When I moved the spinnaker-local.yml there hints followed when the configuration didn't meet .yml linting standards. This is what I see when I try to add a credentials path
"yaml.scanner.ScannerError: mapping values are not allowed here"

I tried adding it without quotes, with single and double, even tried escaping out the forward slashes. Everything ends up with the above message. Tried changing where spaces were, etc. nothing. Eventually, copying the file again, chmod 600 and adding only the values for true and the path without quotes it started without complaints. It is still not listed when checking credentials on 7002. Double-checked the Service Account permissions and it is an "editor" which is the same as the other service accounts, including one that has been working fine for our GCE instance.

**Comment by radkin** [comment] 2016-03-18 18:20
This is what I think *should* work, according to the documentation

```bash
  google:
    # If you want to deploy some services to Google Cloud Platform (google),
    # set enabled and provide primary credentials for deploying.
    # Enabling google is independent of other providers.
    enabled: true
    defaultRegion: us-central1
    defaultZone: us-central1-b
    primaryCredentials:
      name: my-google-account
      # The project is the Google Project ID for the project to manage with Spinnaker.
      # The jsonPath is a path to the JSON service credentials downloaded from the
      # Google Developer's Console.
    project: my-secret-project
      jsonPath: /Users/username/workspace/Spinnaker/spinnaker/config/google-cloud-creds.json
```

but, it has the same yaml mapping values error
`yaml.scanner.ScannerError: mapping values are not allowed here` always on the same line, "jsonPath"

**Comment by radkin** [comment] 2016-03-18 18:53
Managed to get the above values to work, but it required moving jsonPath back one tab so that it is like this:

```bash
  "providers": {
    "google": {
      "project": "ace-tranquility-749", 
      "jsonPath": "/Users/username/workspace/Spinnaker/spinnaker/config/google-cloud-creds.json", 
      "defaultRegion": "us-central1", 
      "enabled": true, 
      "primaryCredentials": {
        "name": "my-google-account"
      }, 
      "defaultZone": "us-central1-b"
    }, 
    "aws": {
```
what we know
* The file is read when starting up the dev instance
* The yml formatting is correct
* The user who is running the services matches the ownership of the files
* There are still no credentials showing
* changing the "name" to match name in the .json creds file does not fix this.

**Comment by ewiseblatt** [comment] 2016-03-19 01:41
project is an attribute of primaryCredentials so should be indented to the
same level as name and jsonPath. The YML itself is probably malformed since
you have a string value as a child of another string value. So the error
message is probably reasonable.

**Comment by ewiseblatt** [comment] 2016-03-19 01:43
Also, the spinnaker/config/default-spinnaker-local.yml was intended as a
starting point for your own. You dont need to use it. I'm just pointing it
out.

**Comment by ewiseblatt** [comment] 2016-03-19 01:48
The providers.google.primaryCredentials.name is arbitrary.
Above you have the jsonPath and project under "google", not
"google.primaryCredentials".
The net effect is that your primaryCredentials project and credentials are
empty. That would default you to manage the GCP project that you are
running spinnaker in. If you arent seeing anything, then I will bet you are
not in a GCE VM. If you were, then you'd be managing yourself rather than
ace-tranquility-749 (unless that's where you were).

**Comment by radkin** [comment] 2016-03-21 17:03
Per instructions above project, jsonPath and name are all attributes of primaryCredentials. They have been indented to reflect this.

```bash
{
  "google": {
    "defaultRegion": "us-central1", 
    "enabled": true, 
    "primaryCredentials": {
      "project": "super-secret", 
      "jsonPath": "/Users/username/workspace/Spinnaker/spinnaker/config/google-cloud-secret.json", 
      "name": "my-google-account"
    }, 
    "defaultZone": "us-central1-b"
  }
}
```
Still no luck

```bash
curl localhost:7002/credentials
[] 
```

the .json file is as follows `-rw-------@ 1 username  wheel google-cloud-secret.json`
Confirmed the user running spinnaker services is "username".

Is there some way to gather debug information regarding credentials? There isn't anything showing in the logs.

**Comment by ewiseblatt** [comment] 2016-03-21 17:20
In clouddriver.log, I see the provider accounts getting created just after
all the URL apis are "Mapped".

Normally when you install spinnaker, it creates a spinnaker user and runs
as that.
Why are you in the wheel group? Not sure the implications of that, but
sounds suspicious for different reasons.

Did you curl localhost:7002/env yet?

**Comment by ewiseblatt** [comment] 2016-03-21 17:22
In particular we could clarify the jsonPath in there is what you are
expecting. And user.name is what you think.

**Comment by radkin** [comment] 2016-03-21 20:24
curl localhost:7002/env was revealing. There are several jsonPath's showing up in there. One of them is listing everything as it should

```bash
"providers.google.defaultRegion":"us-central1","providers.google.defaultZone":"us-central1-b","providers.google.enabled":true,"providers.google.primaryCredentials.jsonPath":"/Users/username/workspace/Spinnaker/spinnaker/config/google-cloud-secret.json","providers.google.primaryCredentials.name":"my-google-account","providers.google.primaryCredentials.project":"super-secret"
```

username & the "super-secret" project are correct ;)
Despite all of this looking like it should work, we're still not getting credentials with this

`curl localhost:7002/credentials`

Used the swagger UI too, perhaps that will help?
http://localhost:8084/swagger-ui.html#!/credentials-controller/getAccountsUsingGET

It says this under /credentials getAccount

```bash
Response Class (Status 200)

    Model
    Model Schema
```

```bash
[
  {
    "name": "string",
    "requiredGroupMembership": {},
    "type": "string"
  }
]
```

as for the clouddriver log, saw this

```bash
2016-03-21 12:02:06.687  INFO 32974 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/credentials],methods=[GET]}" onto public java.util.List<java.util.Map> com.netflix.spinnaker.clouddriver.controllers.CredentialsController.list()
2016-03-21 12:02:06.688  INFO 32974 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/credentials/{name:.+}],methods=[GET]}" onto public java.util.Map com.netflix.spinnaker.clouddriver.controllers.CredentialsController.getAccount(java.lang.String)
```

Here's what I see in the log after all the mapping

```bash
2016-03-21 12:02:09.035  INFO 32974 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Request mapping: optionsForSearches belongs to groups: [[ResourceGroup{groupName='repository-search-controller', position=0, controller=org.springframework.data.rest.webmvc.RepositorySearchController}]] 
2016-03-21 12:02:09.035  INFO 32974 --- [           main] s.w.ClassOrApiAnnotationResourceGrouping : Group for method listSearches was repository-search-controller
2016-03-21 12:02:09.035  INFO 32974 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Request mapping: listSearches belongs to groups: [[ResourceGroup{groupName='repository-search-controller', position=0, controller=org.springframework.data.rest.webmvc.RepositorySearchController}]] 
2016-03-21 12:02:09.046  INFO 32974 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Created resource listing Path: /default/endpoint-mvc-adapter Description: endpoint-mvc-adapter Position: 0
2016-03-21 12:02:09.048  INFO 32974 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Created resource listing Path: /default/credentials-controller Description: credentials-controller Position: 0
2016-03-21 12:02:09.048  INFO 32974 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Created resource listing Path: /default/instance-controller Description: instance-controller Position: 0
2016-03-21 12:02:09.048  INFO 32974 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Created resource listing Path: /default/elastic-ip-controller Description: elastic-ip-controller Position: 0
```

it says the default credentials controller is created.

**Comment by ewiseblatt** [comment] 2016-03-21 20:32
I'm seeing it earlier in my clouddriver.log before the controller.

2016-03-18 18:46:45.376  INFO 10448 --- [           main]
o.s.d.r.w.BaseUriAwareHandlerMapping     : Mapped "{[/alps],methods=[GET]}"
onto
org.springframework.http.HttpEntity<org.springframework.hateoas.alps.Alps>
org.springframework.data.rest.webmvc.alps.AlpsController.alps()
2016-03-18 18:46:45.831  INFO 10448 --- [           main]
c.a.a.p.i.ProfilesConfigFileLoader       : Skip unsupported property name
region in profile [default].
2016-03-18 18:46:47.051  INFO 10448 --- [           main]
c.n.s.c.security.ProviderUtils           : Adding accounts [my-aws-account]
of type NetflixAmazonCredentials...
2016-03-18 18:46:47.271  WARN 10448 --- [           main]
com.netflix.spectator.api.Spectator      : no config impl found in
classpath, using default
2016-03-18 18:46:47.778  INFO 10448 --- [           main]
c.n.s.c.security.ProviderUtils           : Adding accounts
[my-google-account] of type GoogleNamedAccountCredentials...

**Comment by radkin** [comment] 2016-03-21 21:55
I think this is the line you are talking about @ewiseblatt 

`2016-03-21 21:13:17.974  INFO 9273 --- [           main] c.n.s.c.security.ProviderUtils           : Adding accounts [my-google-account] of type GoogleNamedAccountCredentials...`

It shows up on the instance running in GCE. It does not show up on the dev instance of this mac. I'm going to look at security.ProviderUtils , perhaps the answer is there.

**Comment by radkin** [comment] 2016-03-22 00:02
After careful review, found the following:

[GoogleConfiguration.groovy]( clouddriver/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleConfiguration.groovy )

So, “@Import([ GoogleCredentialsInitializer ])” is used to import @Configuration class from the [GoogleCredentialsInitializer]( clouddriver/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy )

And here is where we try to read the values for our credentials

```groovy
      try {
        def jsonKey = GoogleCredentialsInitializer.getJsonKey(managedAccount)
        def googleAccount = new GoogleNamedAccountCredentials(managedAccount.name,
                                                              managedAccount.environment ?: managedAccount.name,
                                                              managedAccount.accountType ?: managedAccount.name,
                                                              managedAccount.project,
                                                              jsonKey,
                                                              managedAccount.imageProjects,
                                                              googleApplicationName)

        if (!managedAccount.project) {
          throw new IllegalArgumentException("No project was specified for Google account $managedAccount.name.");
        }
```

**If it has no project it is supposed to complain about that:**
"No project was specified for Google account $managedAccount.name."

**If it cannot load the account it is supposed to complain about that**
“Could not load account ${managedAccount.name} for Google.”

Why are there no complaints? @cfieber any ideas?

From what I can tell clouddriver is reading in the values from `spinnaker-local.yml` and they are not used, without complaints.

**Comment by ewiseblatt** [comment] 2016-03-22 00:10
@duftler might, but he might not be available.

I forgot to mention earler,
check your localhost:7002/env spring.config.location and make sure that the
right jsonPath is being resolved. You mentioned there were lots of them
returned.

**Comment by duftler** [comment] 2016-03-22 00:19
Can you please post the entire response to `curl localhost:7002/env` here (make sure to omit anything that looks sensitive).

Haven't followed this thread closely, but it kind of looks like the spinnaker-local.yml values are properly specified, but that the references to those value aren't being considered by clouddriver. That is, maybe `/spinnaker/config/clouddriver.yml` isn't being used when starting clouddriver.

**Comment by radkin** [comment] 2016-03-22 01:12
The gist is [here](https://gist.github.com/radkin/3be22ad9937fb011fd9d)

**Comment by ewiseblatt** [comment] 2016-03-23 23:15
In your spinnaker-local, google.enabled is false (line 411)

**Comment by radkin** [comment] 2016-03-25 18:36
It looks like we have for applicationConfig in env

```bash
/Users/username/.spinnaker/spinnaker-local.yml
/Users/username/workspace/Spinnaker/spinnaker/config/clouddriver.yml
/Users/username/workspace/Spinnaker/spinnaker/config/spinnaker-local.yml
```

line 497 google.enabled is true. I confirmed there is only one spinnaker-local.yml file and re-started using run_dev.sh and there are still "False" entries in "env" and the one "true" entry with all the correct information. 

I removed the `spinnaker/config/spinnaker-local.yml` file and got this error (looks like progress)

```java
2016-03-25 10:45:19.149  INFO 68350 --- [           main] c.n.s.c.security.ProviderUtils           : Adding accounts [my-google-account] of type GoogleNamedAccountCredentials...
2016-03-25 10:45:19.334  INFO 68350 --- [           main] Class                                    : Could not load account my-google-account for Google.

java.lang.RuntimeException: failed to create credentials
        at com.netflix.spinnaker.clouddriver.google.security.GoogleNamedAccountCredentials.buildCredentials(GoogleNamedAccountCredentials.java:120)
        at com.netflix.spinnaker.clouddriver.google.security.GoogleNamedAccountCredentials.<init>(GoogleNamedAccountCredentials.java:56)
        at com.netflix.spinnaker.clouddriver.google.security.GoogleNamedAccountCredentials.<init>(GoogleNamedAccountCredentials.java:44)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

Researching the above "INFO"

**Comment by radkin** [comment] 2016-03-25 19:36
Looking at the [code](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java) we are definitely getting something for the .json key as the error requires `if (jsonKey != null) {` as a condition.

It says

```java
Caused by: java.io.IOException: Error reading credentials from stream, 'type' field not specified.
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStream(GoogleCredential.java:254)
        at com.netflix.spinnaker.clouddriver.google.security.GoogleNamedAccountCredentials.buildCredentials(GoogleNamedAccountCredentials.java:107)
        ... 168 common frames omitted
```

It is true, there is no field "type" listed in the credentials. Checked GCP documentation for Google Compute Service Accounts and it looks like we're using the correct account type. Tried a "other" account just in case service accounts are not what we need.

**Comment by radkin** [comment] 2016-03-25 19:56
tried following this suggestion and setting [the environment variable](http://stackoverflow.com/questions/35629641/how-to-set-google-application-credentials-for-google-compute-engine) like this

`export GOOGLE_APPLICATION_CREDENTIALS=/Users/username/.spinnaker/google-cloud-napkin.json` , but it didn't work; same error.

**Comment by ewiseblatt** [comment] 2016-03-25 20:30
we dont use that credential environment variable (at least not yet); we use
multiple accounts.
I think I know the problem. We just hit this testing a release an hour ago.
Was this instance created from Click To Deploy? If not then what I am
thinking isnt it.

**Comment by ewiseblatt** [comment] 2016-03-25 20:31
BTW, if it was C2D then see if you have an
/opt/spinnaker/config/google-credentials.json file that is 1 byte. if so
just remove it.

**Comment by radkin** [comment] 2016-03-25 21:33
No, it's not C2D, it's a dev instance on my mac laptop. BTW, thanks for the tip regarding the C2D credentials file. I'll keep an eye out for it if we deploy more GCP instances that way.

**Comment by ewiseblatt** [comment] 2016-03-25 22:09
that will be fixed soon. hopefully in the next hour. working on it now.
i need a bit more time to firefight this then will try to figure out what
you are seeing.

**Comment by ewiseblatt** [comment] 2016-03-25 23:06
are you on slack? Can we do this more interactively?

**Comment by ewiseblatt** [comment] 2016-03-26 00:51
Problem appears to have turned out that the key came from API Oauth Credentials and not Project Permissions Service Account.

**Closed by ewiseblatt** 2016-03-26 00:51 UTC
