### ISSUE TITLE
Missing Parameter in hal command for ldap configuration:

### ISSUE THREAD

**Issue by pombaer** [spinnaker/spinnaker#3657] opened 2018-11-28 08:00 UTC
### Issue Summary:
Cannot configure "gate" with ldap provider for Active Directory because of missing configuration parameters.

### Cloud Provider(s):
kubernetes

### Environment:
halyard_1.12.0 (docker image "stable")

### Feature Area: 
security - authn - ldap (gate configuration)

### Description:
Anonymous access to Active Directory is not enabled, so i need a Account to bind to AD. 
"config security authn ldap edit" does not support "mangerDN" and "managerPassword" what would be necessary to bind to AD (like authz configuration) and search the user for authentication, it is only possible to configure it by editing "default/profile/gate-local.yml".

Maybe a configuration with --user-dn-pattern "CN={0},CN=Users,DC=objectbay,DC=com" works in some environments, but the "CN" patterns created in Active Directory do not reflect the "sAMAccountName" which i want to use for login.  If i enter "givenName" and "sn" Attribute on creating a new user the CN is "cn=<givenName> <sn>, ou=...." and sAMAccountName is diffent, in our case first character from givenName and whole sn Name, so the "user-dn-pattern" soes not match when entering sAMAccountName. 

### Steps to Reproduce:
Try to make a running configuration with "hal" command options and without manually editing configuraion files like "default/profile/gate-local.yml"

### Additional Details:
This may not be a bug but a annoying configuration issue.

The following Issue "https://github.com/spinnaker/spinnaker/issues/2570" is still open, but seams to be related to "fiat" (authz), no idea why the configuration parameters were not added to "authn" configuration too in this step.

**Comment by jfillo** [comment] 2018-11-28 17:33
This looks like a duplicate of https://github.com/spinnaker/spinnaker/issues/3268

**Comment by sbwsg** [comment] 2018-11-29 21:35
Closed as dupe of #3268

**Closed by sbwsg** 2018-11-29 21:35 UTC
