### ISSUE TITLE
Custom Kinds not deploying in 1.17.0 release 

### ISSUE THREAD

**Issue by raghunandanbs** [spinnaker/spinnaker#5112] opened 2019-11-07 10:01 UTC
### Cloud Provider(s):
Kubernetes

### Environment:
Local Debian

### Description:
While deploying charts containing some custom artifacts, I get following errors:

```
deployKubernetesManifest.deployKubernetesManifest.podDisruptionBudget.Error reading kind [podDisruptionBudget]. Please check connectivity and access permissions to the cluster
```

```
deployKubernetesManifest.deployKubernetesManifest.rule.config.istio.io.Error reading kind [rule.config.istio.io]. Please check connectivity and access permissions to the cluster
```

**Comment by raghunandanbs** [comment] 2019-11-08 03:23
To clarify, I reverted the spinnaker version to 1.16 release and it worked well.

**Comment by raghunandanbs** [comment] 2019-11-12 03:47
Hi! To give more info on this,  If revert the version back to 1.16.5, it is working.

**Comment by chaudyg** [comment] 2019-11-25 18:16
Also seeing the same issue!

**Comment by ezimanyi** [comment] 2019-11-26 20:46
@raghunandanbs @chaudyg : Can you please provide some more details about what workflow is leading to the above errors, and perhaps a small reproducible test case?

The first error message above is for a `podDisruptionBudget` which is not a custom kind, so likely indicates that the service account Spinnaker is running as does not have permission to read that kind.  The second message about `rule.config.istio.io` does relate to a CRD, but I'd need more details to understand what's happening.  In particular:
* Do you have anything configured under `kinds`, `omitKinds`, or `customResources` in the account you're using to deploy these manifests?
* Is `checkPermissionsOnStartup` set on the account you're using to deploy these manifests?
* Does the CRD exist in the cluster before you try to deploy an object of that type, or are you deploying both the CRD and the object using it as part of a single operation?  (If it's the latter, you're likely running into #4645, but that's not new in 1.17 so probably your workflow is a bit different.)
* Can you provide a simple manifest (or multi-manifest separated by `---` as the case may be) that fails on 1.17.x but passed on 1.16.x?

With this info, I can try to reproduce and see what changed in 1.17.  Thanks!

**Comment by chaudyg** [comment] 2019-11-27 13:41
Hi @ezimanyi . Indeed I seem to be hitting https://github.com/spinnaker/spinnaker/issues/4645

**Comment by chaudyg** [comment] 2019-12-03 14:33
Just to confirm, the error for me was:
```
deployKubernetesManifest.deployKubernetesManifest.Prometheus.monitoring.coreos.com.Error reading kind [Prometheus.monitoring.coreos.com]. Please check connectivity and access permissions to the cluster
```

I am getting the error when deploying both the CRD for `Prometheus.monitoring.coreos.com` and a `Prometheus` object as part fo the same deployment

My hal config has the following config

```yaml
        kinds: []
        omitKinds:
        - '[PodPreset]'
        customResources: []
```

The stage worked in 1.16.5. Which is strange.

**Comment by ezimanyi** [comment] 2019-12-16 19:56
I'm going to close this as a duplicate of #4645; @raghunandanbs please re-open with more details if it seems your issue is not a duplicate of that one.  Thanks!

**Closed by ezimanyi** 2019-12-16 19:56 UTC
Labels: sig/kubernetes
