### ISSUE TITLE
Canary Stage UI allows fractional Lifetime, Kayenta crashes on fractions

### ISSUE THREAD

**Issue by dotdotdotpaul** [spinnaker/spinnaker#2698] opened 2018-04-24 16:33 UTC
The "Lifetime" field in the Canary Stage configuration indicates "hours", but often people want to run canaries for shorter periods of time (particularly when testing).  The UI does not prevent someone from entering a fractional value, like "0.5" (which would expect to result in a 30-minute run).

However, although the UI allows the value to be saved, when the stage actually runs, Kayenta throws an exception:

> Unable to map context to class com.netflix.spinnaker.orca.kayenta.model.KayentaCanaryContext

This should be a pretty easy fix, but it's not clear to me if it's preferable to fix the UI to prevent the entry of fractional values, or if the Kayenta microservice should be updated to handle them.  Currently, this is a problem as entering a fraction results in an exception that isn't particularly meaningful and it's likely that people will attempt to enter fractional values.

**Comment by andreasevers** [comment] 2018-05-18 12:16
I'd also be very interested in this fix, for demo purposes.
For now I'm restricted to either failing the canary stage after a couple of minutes since waiting for an hour during a demo isn't an option.
Using a retrospective analysis is a possibility although that restricts me from using the audience as canary pool.

**Comment by duftler** [comment] 2018-06-07 18:56
Duplicate of https://github.com/spinnaker/kayenta/issues/283.

**Comment by duftler** [comment] 2018-06-20 15:50
The PR's closing this issue are referenced here: spinnaker/kayenta#283

**Closed by duftler** 2018-06-20 15:50 UTC
Labels: component/kayenta
