### ISSUE TITLE
Unable to create new server group on GKE application (1.10.1)

### ISSUE THREAD

**Issue by Herrera93** [spinnaker/spinnaker#3544] opened 2018-11-01 19:57 UTC
### Issue Summary:

I have a kubernetes application but after updating to 1.10.0 there is a problem creating a new server group, when I click on the button *Create Server Group* nothing happens and it throws an error on the error:
```
TypeError: "defaults is null"
	buildNewClusterCommand app.js?b04b558c6a2ea3e9b2e4:65771:9
	buildNewServerGroupCommand app.js?b04b558c6a2ea3e9b2e4:20384:19
	buildNewServerGroupCommand app.js?b04b558c6a2ea3e9b2e4:11320:49
	createServerGroup app.js?b04b558c6a2ea3e9b2e4:117483:9
	processQueue vendors~app.js?b04b558c6a2ea3e9b2e4:428342:37
	scheduleProcessQueue vendors~app.js?b04b558c6a2ea3e9b2e4:428386:27
	digest vendors~app.js?b04b558c6a2ea3e9b2e4:429481:15
	evalAsync vendors~app.js?b04b558c6a2ea3e9b2e4:429710:15
	completeOutstandingRequest vendors~app.js?b04b558c6a2ea3e9b2e4:417784:7
	timeoutId vendors~app.js?b04b558c6a2ea3e9b2e4:418064:7
```
It seems like the *null* sent here:
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/cluster/allClusters.controller.js#L108
causes the error to be thrown here:
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/kubernetes/src/cluster/configure/CommandBuilder.js#L41

### Cloud Provider(s):

Google Kubernetes Engine

### Environment:

Kubernetes V1 deployment through Halyard

### Feature Area: 

Deck

**Comment by sbwsg** [comment] 2018-11-06 15:32
Thanks for the issue report; This appears to be a duplicate of https://github.com/spinnaker/spinnaker/issues/3559

I'll try and get a patch in to 1.10 today 👍 Closing this issue in favor of #3559

**Closed by sbwsg** 2018-11-06 15:32 UTC
