### ISSUE TITLE
Bake starts in two AWS regions at the same time, only one is desired

### ISSUE THREAD

**Issue by costimuraru** [spinnaker/spinnaker#2095] opened 2017-11-13 13:57 UTC
*Title*

Bake starts in two AWS regions at the same time, only one is desired

*Cloud Provider*
AWS

*Environment*

Running version 1.4.2, deployed in AWS

*Feature Area*

Pipeline - Bake

*Description*

We have a pipeline consisting of two stages: Bake, then Deploy.
The Bake is configured to build an AMI in us-east-1 (and then using packer to copy to sa-east-1).
The Deploy is configured to Deploy to sa-east-1.

When running the pipeline, the expected behavior would be:
- Bake AMI in us-east-1
- (packer to copy AMI to sa-east-1) as part of the same Bake stage
- Deploy should use this AMI to deploy to sa-east-1

Actual behavior is:
- Bake AMI in us-east-1 starts as sub-task
- Bake AMI in sa-east-1 starts as sub-task
Bake fails in sa-east-1 (we don't have any config for this kind of Bake).

*Steps to Reproduce*

*Additional Details*

**Stage1: Bake (us-east-1 selected)**
<img width="784" alt="screenshot 2017-11-13 15 45 56" src="https://user-images.githubusercontent.com/952836/32728897-bd24519a-c88a-11e7-949a-f8af92b44fb2.png">

---

**Stage2: Deploy (deploying in sa-east-1)**
![screenshot 2017-11-13 15 45 36](https://user-images.githubusercontent.com/952836/32729198-a295b87c-c88b-11e7-871d-8753ebb1bbe2.jpg)

---

**Running the pipeline: Bake starts in both us-east-1 and sa-east-1**. Expected behavior would be for the Bake to start only in us-east-1, as configured in the Bake stage.
![screenshot 2017-11-13 15 46 27](https://user-images.githubusercontent.com/952836/32729014-1a6f6542-c88b-11e7-8072-4b54621becc1.jpg)

**Comment by duftler** [comment] 2017-11-14 12:52
The is the intended behavior of the logic in Orca's bake stage which implicitly synthesizes bakes in each region target by a deploy in the given execution.

Closing this issue as @costimuraru confirmed that they are able to bake in the intended region and avoid the copy-over behavior.

**Closed by duftler** 2017-11-14 12:52 UTC
