### ISSUE TITLE
Appengine deployment failing with IOException error

### ISSUE THREAD

**Issue by skalle** [spinnaker/spinnaker#4574] opened 2019-06-28 05:41 UTC
### Issue Summary:
The initial Appengine deployment after not deploying anything for ~a day often fails with IOException errors  - File not Found or Failed to delete file or directory. 

Following deployments normally work fine and seem to continue working until there's a gap of a while before trying again. 

### Cloud Provider(s):

Google GKE + Appengine + GCB + GCS

### Environment:

Deploying to Appengine with GCS tar file artifacts. 
Appengine standard environment.

Spinnaker 1.14.7

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Appengine

### Steps to Reproduce:

- Deploy something to Appengine. 
- Wait until next day. 
- Deploy again. 
- IOException failure of either file not found or failure to delete file or folder. 

- Deploy again . 
- Working fine
- Continues to work fine for all following deployments.

### Additional Details:

=== Log entry

2019-06-28 14:36:16.128 AEST
2019-06-28 04:36:16.128 INFO 1 --- [ol-6-thread-150] c.n.s.c.data.task.jedis.JedisTask : [ORCHESTRATION] Orchestration failed: DeployAppengineAtomicOperation | IOException: [Unable to delete file: /var/tmp/clouddriver/gs:--*******-5b597af9-e438-47b0-ad0b-c441e70a3557.tar#1561696561443003/app-spin.yaml]
Expand all | Collapse all {
 insertId:  "jamlwhaxes0qid7xb"  
 logName:  "projects/chrome-infra-spinnaker/logs/stdout"  
 metadata: {…}  
 receiveTimestamp:  "2019-06-28T04:36:20.422811037Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "2019-06-28 04:36:16.128  INFO 1 --- [ol-6-thread-150] c.n.s.c.data.task.jedis.JedisTask        : [ORCHESTRATION] Orchestration failed: DeployAppengineAtomicOperation | IOException: [Unable to delete file: /var/tmp/clouddriver/gs:--*******-5b597af9-e438-47b0-ad0b-c441e70a3557.tar#1561696561443003/app-spin.yaml]
"  
 timestamp:  "2019-06-28T04:36:16.128759926Z"  
}

=== Log traceback.

2019-06-28 14:36:16.132 AEST
2019-06-28 04:36:16.132 ERROR 1 --- [ol-6-thread-150] c.n.s.c.o.DefaultOrchestrationProcessor : java.io.IOException: Unable to delete file: /var/tmp/clouddriver/gs:--*******-5b597af9-e438-47b0-ad0b-c441e70a3557.tar#1561696561443003/app-spin.yaml at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400) at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721) at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617) at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391) at com.netflix.spinnaker.clouddriver.appengine.gcsClient.AppengineGcsRepositoryClient.downloadFiles(AppengineGcsRepositoryClient.groovy:76) at com.netflix.spinnaker.clouddriver.appengine.gcsClient.AppengineGcsRepositoryClient.updateLocalDirectoryWithVersion(AppengineGcsRepositoryClient.groovy:44) at com.netflix.spinnaker.clouddriver.appengine.model.AppengineRepositoryClient$updateLocalDirectoryWithVersion$1.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) at com.netflix.spinnaker.clouddriver.appengine.deploy.ops.DeployAppengineAtomicOperation.cloneOrUpdateLocalRepository(DeployAppengineAtomicOperation.groovy:230) at com.netflix.spinnaker.clouddriver.appengine.deploy.ops.DeployAppengineAtomicOperation$cloneOrUpdateLocalRepository$1.callCurrent(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176) at com.netflix.spinnaker.clouddriver.appengine.deploy.ops.DeployAppengineAtomicOperation.cloneOrUpdateLocalRepository(DeployAppengineAtomicOperation.groovy:234) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176) at com.netflix.spinnaker.clouddriver.appengine.deploy.ops.DeployAppengineAtomicOperation$_operate_closure1.doCall(DeployAppengineAtomicOperation.groovy:146) at com.netflix.spinnaker.clouddriver.appengine.deploy.ops.DeployAppengineAtomicOperation$_operate_closure1.doCall(DeployAppengineAtomicOperation.groovy) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) at com.netflix.spinnaker.clouddriver.appengine.deploy.AppengineMutexRepository.atomicWrapper(AppengineMutexRepository.groovy:36) at com.netflix.spinnaker.clouddriver.appengine.deploy.AppengineMutexRepository$atomicWrapper.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) at com.netflix.spinnaker.clouddriver.appengine.deploy.ops.DeployAppengineAtomicOperation.operate(DeployAppengineAtomicOperation.groovy:134) at com.netflix.spinnaker.clouddriver.appengine.deploy.ops.DeployAppengineAtomicOperation.operate(DeployAppengineAtomicOperation.groovy) at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate$0.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:89) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) at groovy.lang.Closure.call(Closure.java:405) at groovy.lang.Closure.call(Closure.java:399) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82) at java_util_concurrent_Callable$call$0.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:88) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) at groovy.lang.Closure.call(Closure.java:405) at groovy.lang.Closure.call(Closure.java:399) at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:129) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

=== File in clouddriver /var/tmp/clouddriver/gs:--*******-5b597af9-e438-47b0-ad0b-c441e70a3557.tar#1561696561443003

bash-4.4$ ls -la app-spin.yaml
-rw-r--r--    1 spinnake nogroup       1268 Jun 25 05:58 app-spin.yaml

**Comment by skalle** [comment] 2019-07-01 23:12
I have this failing fairly reliably for a pipeline atm. , the folders in the errors messages changes from one deployment to another but seem to fail every time.  The tar file produced in this particular pipeline have the same name between runs ..

For the other pipelines where the first run normally fail the tar file name changes (named after the GCB id).

Unpacking the tar file the directories in the errors not found or fail to delete does exist fine.

Will leave this pipeline as is for a bit in-case there's information that would be of interest.

**Comment by skalle** [comment] 2019-07-02 06:36
Some more information. 

We deploy multiple services in the affected pipelines. Looking at the logs it seem the deployments run concurrently fetching the tar archives.

Running `lsof` during the deployments show files being locked by `java` when things fail.

Is it possible the operations clobber each other running FileUtil.forcedelete on the same folder?

**Comment by ezimanyi** [comment] 2019-07-10 23:46
I spent some time looking into this today---I wasn't able to reproduce this and from reading the code it's not clear to me how things got into a state where this file can't be deleted.

There is a locking mechanism that ensures that only one deployment at a time is operating on a given folder.  The lock is obtained before we fetch the GCS file and un-tar it, and is released only after we've called `gcloud app deploy` (which should be the last we need of the files).

It's also interesting that the error is indicating that the process trying to delete `app-spin.yaml` sees the file exists but is unable to delete it.  (We're calling `FileUtils.forceDelete` which would show a different error message if we tried to delete a file that didn't exist.)

A few questions about the pipeline that's reliably failing:
* When you say the pipeline deploys multiple services, do you have multiple stages in the pipeline that all use the same GCS `.tar` file but deploy different `.yaml` files?
* Is it always the same file in the error message (`app-spin.yaml`) or does the error sometimes show up for different files?
* I'd be interested particularly on what has `app-spin.yaml` open---is it the `clouddriver` java process?  Is there still a lock there when things are quiescent and no pipelines are running?  Is the file opened read or write?
* After you see that error message, can you delete the file yourself using `rm` (when logged in as the same user as clouddriver runs)?

It's possible there's a bug in the locking logic as it looks like it may not be perfect, but I'm suspicious that's the issue if you're seeing this consistently (as the couple of small bugs I see reflect very small windows).

**Comment by skalle** [comment] 2019-07-12 05:37
Hey Eric.

For the questions. 
- Multiple services. 

  Our Appengine app have multiple services
   - We've tried deploying the services with multiple configurations in one Deploy step.
    - One deploying the default service app.yaml
    - One deploying the backend service backend.yaml
    - Both use configured with the same TAR file artifact.
  - We've also tried having multiple deploy steps running in parallel. 

  Both run into the IOException errors. 

  Suppose we could do some serial deployment but would prefer the option where we have multiple configurations in one Deploy step , this so we don't have the versions diverge if one of the services fail to deploy.  

- Is it always the same file - No, It's pretty much always different files or directories.
- Further information - Limited by busybox lsof here , I'll give installing the real APK a go.
- Can you delete the file - Yes. After the deployment fails there are no locks remaining.

**Comment by ezimanyi** [comment] 2019-07-12 15:25
@skalle : Thanks for the details!  I've cherry-picked the above change to fixed the threading bugs in the locking of the directory into the 1.14 branch so it will be in 1.14.10 (which should be released early next week).  I'm hoping that fixes the issue as I can't see how there would otherwise be simultaneous operations trying to modify the same directory.

Can you please give 1.14.10 a try next week and let me know if this is still occurring?

**Comment by ezimanyi** [comment] 2019-07-12 16:20
(Also, if you have a dev environment you can test this change right away by setting the version to `release-1.14.x-latest-validated`)

**Comment by skalle** [comment] 2019-07-17 12:44
Hey @ezimanyi  eagerly waiting for 1.14.10 to give it a go.

**Comment by ezimanyi** [comment] 2019-07-17 21:00
Sorry for the delay, we'll push this patch release tomorrow.

**Comment by ezimanyi** [comment] 2019-07-18 18:43
1.14.10 [has been released](https://www.spinnaker.io/community/releases/versions/1-14-10-changelog#spinnaker-release-1-14-10) with this fix

**Closed** 2019-08-29 19:19 UTC
Labels: bug, provider/appengine
