### ISSUE TITLE
(openstack) Create server group hangs on Wait for Up Instances

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1153] opened 2016-09-15 16:50 UTC
Creating a server group in openstack hangs on "Wait for Up Instances".

Excerpt from orca log:

2016-09-15 12:30:17.139  INFO 2272 --- [TaskExecutor-13] c.n.s.o.b.StageStatusPropagationListener : Task SUCCEEDED but not all other tasks are complete (stageId: 38ca6170-aece-4e15-bdf3-4877f4c0c5aa, nonBookEndTaskStatus: NOT_STARTED) ... tasks: [{"id":"2","name":"determineSourceServerGroup","startTime":1473956980247,"endTime":1473956980447,"status":"SUCCEEDED"}, {"id":"3","name":"determineHealthProviders","startTime":1473956980465,"endTime":1473956980583,"status":"SUCCEEDED"}, {"id":"4","name":"createServerGroup","startTime":1473956980616,"endTime":1473956981197,"status":"SUCCEEDED"}, {"id":"5","name":"monitorDeploy","startTime":1473956981228,"endTime":1473956984451,"status":"SUCCEEDED"}, {"id":"6","name":"forceCacheRefresh","startTime":1473956984483,"endTime":1473957017138,"status":"SUCCEEDED"}, {"id":"7","name":"waitForUpInstances","startTime":null,"endTime":null,"status":"NOT_STARTED"}, {"id":"8","name":"forceCacheRefresh","startTime":null,"endTime":null,"status":"NOT_STARTED"}, {"id":"9","name":"getCommits","startTime":null,"endTime":null,"status":"NOT_STARTED"}]
2016-09-15 12:30:17.186  INFO 2272 --- [TaskExecutor-13] o.s.batch.core.job.SimpleStepHandler     : Executing step: [38ca6170-aece-4e15-bdf3-4877f4c0c5aa.createServerGroup.waitForUpInstances.7]
2016-09-15 12:30:17.188  INFO 2272 --- [TaskExecutor-13] c.n.s.o.b.StageTaskPropagationListener   : Setting task status to RUNNING (stageId: 38ca6170-aece-4e15-bdf3-4877f4c0c5aa, taskId: 7) [beforeTask]
2016-09-15 12:30:17.189  INFO 2272 --- [TaskExecutor-13] c.n.s.o.b.StageStatusPropagationListener : Marking Stage as RUNNING (stageId: 38ca6170-aece-4e15-bdf3-4877f4c0c5aa)
2016-09-15 12:30:17.191  INFO 2272 --- [TaskExecutor-13] c.n.spinnaker.orca.echo.EchoService      : ---> HTTP POST http://10.81.72.188:8089/
2016-09-15 12:30:17.247  INFO 2272 --- [TaskExecutor-13] c.n.spinnaker.orca.echo.EchoService      : <--- HTTP 200 http://10.81.72.188:8089/ (55ms)
2016-09-15 12:30:17.251  INFO 2272 --- [TaskExecutor-13] c.n.s.orca.clouddriver.OortService       : ---> HTTP GET http://10.81.72.188:7002/applications/mitaka/clusters/my-openstack-account/mitaka-0915-0928/openstack
2016-09-15 12:30:17.303  INFO 2272 --- [TaskExecutor-13] c.n.s.orca.clouddriver.OortService       : <--- HTTP 200 http://10.81.72.188:7002/applications/mitaka/clusters/my-openstack-account/mitaka-0915-0928/openstack (51ms)
2016-09-15 12:30:17.304  INFO 2272 --- [TaskExecutor-13] c.n.s.o.c.t.i.WaitForUpInstancesTask     : mitaka-0915-0928-v000: Target desired size is 1
2016-09-15 12:30:17.304  INFO 2272 --- [TaskExecutor-13] c.n.s.o.c.t.i.WaitForUpInstancesTask     : mitaka-0915-0928-v000: Instances up check - healthy: 0, target: 1
...

Following that there are numerous log message sequences of the form:
2016-09-15 12:30:27.354  INFO 2272 --- [TaskExecutor-13] c.n.s.o.c.t.i.WaitForUpInstancesTask     : mitaka-0915-0928-v000: Calculating target desired size from snapshot (1) and server group (1)
2016-09-15 12:30:27.354  INFO 2272 --- [TaskExecutor-13] c.n.s.o.c.t.i.WaitForUpInstancesTask     : mitaka-0915-0928-v000: Target desired size is 1
2016-09-15 12:30:27.354  INFO 2272 --- [TaskExecutor-13] c.n.s.o.c.t.i.WaitForUpInstancesTask     : mitaka-0915-0928-v000: Instances up check - healthy: 0, target: 1

**Comment by drmaas** [comment] 2016-09-16 19:23
I am not able to reproduce this against our mitaka install - have you verified that the instance actually does come up in openstack and is in ACTIVE status? I believe that deck just calls back to one of the controller methods that lists the instances for the server group and looks for ones that are up, so you could make calls to clouddriver via the swagger page to see if it is reporting the up instance(s).

**Comment by drmaas** [comment] 2016-09-21 14:12
Since this issue is not reproducible, we should close it and re-open if it comes up again.

**Comment by drmaas** [comment] 2016-09-22 20:35
This should get resolved via #1159 and #1160

**Closed** 2016-09-26 19:28 UTC
Labels: OpenStack
