### ISSUE TITLE
Igor unable to fetch jobs from Jenkins after Jenkins Integration

### ISSUE THREAD

**Issue by crackerplace** [spinnaker/spinnaker#892] opened 2016-05-18 19:09 UTC
**Spinnaker is unable to display the job list from jenkins**

*Cloud Provider*

AWS

*Environment*

We have installed Spinnaker using the Spinnaker-Ubuntu-14.04-22 - ami-4b35d42b  image and deployed to an AWS instance. 

*Feature Area*

Igor,Jenkins

*Description*

When we add a trigger,jobs should be populated in the job list dropdown when we select jenkins as the  master.Jobs are present in jenkins but are not displayed in UI.

*Steps to Reproduce*

We have completed all the steps as described in the hello-spinnaker example below.We have used the AWS spinnaker image to directly configure spinnaker in AWS.

www.spinnaker.io/docs/hello-spinnaker.

I am trying to create a sample pipeline as noted in the above example.But while I create trigger in the first step and select jenkins ,the jobs are not getting populated and am getting below error in browser.

GET http://localhost:8084/v2/builds/Jenkins/jobs 429 (Too Many Requests)

The actual issue looks like while retrofit is trying to map the response from jenkins getjobs into the JobList class its finding an attribute _class in jenkins response xml and which is not present in JobList groovy class.Below is how we tried finding the issue

1)Login to AWS Spinnaker instance

2)Gate service is exposed at port 8084.
curl http://localhost:8084/v2/builds/Jenkins/jobs.

{"failureCause":"retrofit.RetrofitError: 429 Too Many Requests","error":"Too Many Requests","message":"429 Too Many Requests","status":429,"url":"http://localhost:8088/jobs/Jenkins","timestamp":1462793944530}

3)Igor service is exposed at port 8088.
curl http://localhost:8088/jobs/Jenkins

{"fallbackException":"java.lang.UnsupportedOperationException: No fallback available.","failureType":"COMMAND_EXCEPTION","failureCause":"retrofit.converter.ConversionException: org.simpleframework.xml.core.AttributeException: Attribute '_class' does not have a match in class com.netflix.spinnaker.igor.jenkins.client.model.JobList at line 1","error":"Hystrix Failure","message":"jenkins-Jenkins-getJobs failed and no fallback available.","status":429,"timestamp":1462793896853}

When I check in the igor logs,there are few exceptions which are occuring during the getprojects by jenkins poll

Caused by: retrofit.converter.ConversionException: org.simpleframework.xml.core.AttributeException: Attribute '_class' does not have a match in class com.netflix.spinnaker.igor.jenkins.client.model.ProjectsList at line 2
at retrofit.converter.SimpleXMLConverter.fromBody(SimpleXMLConverter.java:38)
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:367)
... 39 common frames omitted
Caused by: org.simpleframework.xml.core.AttributeException: Attribute '_class' does not have a match in class com.netflix.spinnaker.igor.jenkins.client.model.ProjectsList at line 2

4)Connect to jenkins and get the jobs as its being done in spinnaker code https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy

resp = requests.get('http://jenkinserverip:8080/api/xml?tree=jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name]]]]]]]]]]',auth=('admin','password'))
print resp.text

    <hudson` _class='hudson.model.Hudson'><job _class='hudson.model.FreeStyleProject'><name>Hello Build</name></job><job _class='hudson.model.FreeStyleProject'><name>Hello `Poll</name></job></hudson>

So as the jenkins response is having the _class attribute ,retrofit is throwing an error at this line http://grepcode.com/file/repo1.maven.org/maven2/com.squareup.retrofit/retrofit/1.9.0/retrofit/RestAdapter.java#383

How can we fix this issue ?

Can the code be updated by adding @Root(strict=false) in the ProjectsList and JobList classes ?

*Additional Details*

Additional information such as screenshots and exception logs.

![spinnaker_jenkinsissue](https://cloud.githubusercontent.com/assets/6803956/15371624/0520b52a-1d5a-11e6-9f95-e3669f106780.png)

**Comment by crackerplace** [comment] 2016-05-18 22:11
We are facing the same issue even when we install spinnaker from source(git master).

**Comment by tomaslin** [comment] 2016-05-19 18:05
the jenkins api changed a little between 2.2 and above. Will look at this

**Comment by crackerplace** [comment] 2016-05-19 20:18
@tomaslin ok.Can this be even updated in the www.spinnaker.io/docs/hello-spinnaker docs so that it would help others too.

**Comment by tomaslin** [comment] 2016-05-19 20:19
shouldn't have to, this is fixed by https://github.com/spinnaker/igor/pull/96

**Comment by crackerplace** [comment] 2016-05-19 20:37
That's cool.Thanks.

**Closed** 2016-05-19 22:01 UTC

**Comment by AvdhutPandit** [comment] 2016-07-19 15:13
I am having AWS spinnaker machine. I want to update my IGOR. How can I upadte it?

**Comment by hmgauthami** [comment] 2016-07-22 07:37
you can use apt-get upgrade spinnaker-igor to upgrade. Its better to upgrade all services together.

**Comment by AvdhutPandit** [comment] 2016-07-22 07:40
Thank you..! I did it yesterday the same thing.. it is working now..!

**Comment by rakesh-joshi** [comment] 2017-06-20 08:41
I'm also facing the same issue with Igor and Jenkins.. can someone help me out here.. i have install everything through Halyard. Attached the igor log file. 


[Igor.txt](https://github.com/spinnaker/spinnaker/files/1087506/Igor.txt)

**Comment by rossedman** [comment] 2017-08-01 02:49
Did anyone find a fix for this? Running Spinnaker 1.2.0 and receiving this error running Jenkins.

**Comment by divjotsinghnanda** [comment] 2017-08-01 15:33
This issue still seems to persist with the latest version of Spinnaker. Can anyone please look into this and solve it.

**Comment by rakesh-joshi** [comment] 2017-08-02 20:00
@divjotsinghnanda / @rossedman, How you guys are integrating Jenkins with Spinnaker. 
if Jenkins Running on http so mention the same in command, if you are using Halyard then try to run the below script.

**hal config ci jenkins master add my-jenkins-master --address http://my.domain.com:8080/ --username $USERNAME--password.**

Try this.

**Comment by sncitom3** [comment] 2017-08-02 20:14
I am having the same issue - After installing Spinnaker on AWS with the quick start. My Jenkins version is 2.6.
I've updated Igor and still the issue persists

**Comment by tomaslin** [comment] 2017-08-03 02:46
I'm not quite sure if this is the same issue as 2.3 or a new issue due to changes in jenkins 2.6. If anyone is blocked what would help would be any error messages in igor.log microservice

**Comment by rossedman** [comment] 2017-08-03 16:15
@tomaslin Hey Tom, didn't want to thread hijack but here is my error output:

```
com.netflix.hystrix.exception.HystrixRuntimeException: jenkins-jenkins-getProjects failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:801)
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:785)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:99)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1514)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1404)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8171)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:100)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1005)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1473)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1369)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:297)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8171)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:517)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:495)
	at rx.Observable.unsafeSubscribe(Observable.java:8171)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: retrofit.RetrofitError: 500 Server Error
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy71.getProjects(Unknown Source)
	at com.netflix.spinnaker.igor.jenkins.client.JenkinsClient$getProjects.call(Unknown Source)
	at com.netflix.spinnaker.igor.jenkins.service.JenkinsService$_getProjects_closure1.doCall(JenkinsService.groovy:70)
	at com.netflix.spinnaker.igor.jenkins.service.JenkinsService$_getProjects_closure1.doCall(JenkinsService.groovy)
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:923)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:906)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:574)
	at com.netflix.spinnaker.hystrix.SimpleHystrixCommand.run(SimpleHystrixCommand.groovy:53)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	... 21 common frames omitted
```

**Comment by sncitom3** [comment] 2017-08-03 23:23
@tomaslin I have the same errors as @rossedman

**Comment by priteshmehta** [comment] 2017-08-04 04:09
I am getting same error with latest Spinnaker v1.1.2 & Jenkins v2.64.

**Comment by rossedman** [comment] 2017-08-04 19:41
@tomaslin @sncitom3 @priteshmehta 

To solve this I went to Configure Global Security and set:
- Jenkins Own User Database
- Logged-in Users Can Do Anything

Created my user and then provided those credentials to Spinnaker

Originally when deploying it was set to "Delegate to servlet container". Even though I had created a user Spinnaker could not access Jobs this way. 

To debug I disabled security and Spinnaker was able to retrieve jobs. I then set security back how it was and tried to curl using basic auth and I could not access Jenkins even through that.

**Comment by sncitom3** [comment] 2017-08-04 20:44
Actually for us the issue was the Jenkins Server EC2 Security groups were closed to spinnaker.

**Comment by priteshmehta** [comment] 2017-08-07 06:33
Thank you @rossedman. I will try it out.

**Comment by grizzthedj** [comment] 2017-11-02 18:42
I was having the same issue where spinnaker couldn't retrieve the jenkins jobs. I found that quoting the the Jenkins username and password didn't work. Everything worked when I removed the quotes.

e.g.
`echo myPassword | hal config ci jenkins master add jenkins-test --address http://my-jenkins-server/ --username myUser --password `

**Comment by amitmindstix** [comment] 2018-03-26 15:12
Still an issue in Spinnaker 1.6.0 and Jenkins v2.107.1
Getting Http error code 429 Too many requests when loading jobs.

**Comment by jhohertz** [comment] 2018-04-21 00:27
Still an issue in Spinnaker 1.6.1 and Jenkins v2.107.2.

Spinnaker is deployed on a k8s 1.9.6 cluster through halyard. I have confirmed the jenkins instance is reachable from the pod running igor by connecting to it and testing via wget from the pod.

No matter what I do, I get the 429 error from the "jobs" call from the deck UI. With or without TLS, with or without an ELB in front of the service. Logs do not reveal anything insightful about what is going wrong.

**Comment by umairadeeb** [comment] 2018-12-04 15:02
I got this fixed by configuring tomcat to allow special characters requested in Igor's request. Specifically [ ].
This is specific to Jenkins server running on tomcat. It has been discussed [here](https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters/51212677#51212677)

Open $TOMCAT_HOME/conf/server.xml and append **relaxedQueryChars="[,]"** after <Connector port="80":

`<Connector port="8080" protocol="HTTP/1.1"
connectionTimeout="20000"
redirectPort="8443"
relaxedQueryChars="[,]" />`

**Comment by aleksejlopasov** [comment] 2018-12-12 12:30
Yesterday, I found out the reason of the issue in my case. I had 200 code while using curl and 429 while trying to fetch Jenkins jobs in Spinnaker UI. The issue occurred due to empty list of jobs in Jenkins.
Once I integrated Jenkins and Spinnaker I've tested the integration with creating new Jenkins step in Spinnaker pipeline. As there were no jobs in Jenkins, I expected to see empty list of jobs in Spinnaker without any errors in web console, but got 429.
However, this error has disappeared as soon as the new job (simple freestyle project) has been created in Jenkins and Spinnaker's successfully fetched it. 
I'm not sure but it seems to be Igor does not expect Jenkins job list to be white clean and can not process an empty Jenkins reply

**Comment by shishirms** [comment] 2019-03-26 11:28
I am able to integrate jenkins servers which i have created in my AWS account for testing purpose with Spinnaker successfully, but when i am trying to the same with internal jenkins which is in private cloud i am getting "retrofit.RetrofitError: 429".
curl -v -u username:password -X GET http://jenkins.server.com/jenkins/job/EXP/
when i ran curl command from my spinnaker instance, i am able to see all jobs in output.

Not sure why i am facing this. could someone please help me on this?

**Comment by LochanRn** [comment] 2020-01-05 16:49
Hi guys i have been facing the same issue, went through all the comments above and also several other posts and blogs, still could not find a work around. Please help me fix this issue, if any of you have a solution for this.

I have been using kubernetes in azure to deploy spinnaker. 

I have installed spinnaker using helm charts.
Link for Helm charts: https://github.com/helm/charts/tree/master/stable/spinnaker

I also installed Jenkins in the same cluster in a different namespace using helm charts (Helm Charts version 3 is being used)

Configured Jenkins by setting 

- Jenkins Own User Database
- Logged-in Users Can Do Anything
Created my user and then provided those credentials to Spinnaker

**Configured** spinnaker by enabling jenkins.
**Command used**: hal config ci jenkins enable 

**Configured jenkins master** by adding a master with address:dns:port(servicename.namespace.svc.cluster.local:port) username:  myUsername created in jenkins password myPassword created in jenkins
**Command used**: hal config ci jenkins master add jenkinsSpinnaker --address spinnakerSERVICENAME.spinnakerNAMESPACE.svc.cluster.local:PORT --username USERNAME--, password PASSWORD

Config File after configuring jenkins:
![Screenshot (93)_LI](https://user-images.githubusercontent.com/25365962/71783026-15fc9300-3007-11ea-99b9-3f3a6afac3d1.jpg)

Also enabled igor by adding the details in helm charts:

  _additionalProfileConfigMaps:
    create: true
    data: 
      igor.yml: |
        enabled: true
        skipLifeCycleManagement: true_ 
Cross checked for igor pod in the respective namespace : It is up and running.
I am accessing spinnaker and jenkins UI via ingress. I have configured ingress in helm charts of jenkins and spinnaker.

On opening my spinnaker UI and trying to add a jenkins stage to a pipeline, I have no dropdowns of the masters in the UI. 
![Screenshot (98)](https://user-images.githubusercontent.com/25365962/71783146-74764100-3008-11ea-9384-4f48093744fe.png)

Browser console errors : 
![Screenshot (92)](https://user-images.githubusercontent.com/25365962/71782913-94f0cc00-3005-11ea-809a-33b4bc7a8430.png)

On trying the curl command I am getting the output 
![Screenshot (97)_LI](https://user-images.githubusercontent.com/25365962/71783042-3298cb00-3007-11ea-9536-e11417707d81.jpg)
![Screenshot (96)](https://user-images.githubusercontent.com/25365962/71783065-89060980-3007-11ea-88d3-5f4febc13c6c.png)
![Screenshot (95)](https://user-images.githubusercontent.com/25365962/71783067-899ea000-3007-11ea-8dcd-a35bed8a5785.png)
