### ISSUE TITLE
GCP: Instance group Port Name Mapping not working properly

### ISSUE THREAD

**Issue by nickjacques** [spinnaker/spinnaker#2033] opened 2017-10-16 20:56 UTC
*Cloud Provider*

GCP

*Environment*

Spinnaker with multiple GCP projects (3) - deploying instances, clusters/instance groups, and load balancers into projects.

*Feature Area*

Deployment configuration and server groups/clusters/instance groups - specifically, the Port Name Mapping section. This may include Cloud Driver and Front50. 

*Description*

It appears that the behavior of "Port Name Mapping" in Spinnaker has changed over time. Previously, it appeared to create a K/V in the `loadBalancingPolicy` object, like this: `"listeningPort": 8888,`. However, it seems that now an array is added to `loadBalancingPolicy`, which looks like this:

```
"namedPorts": [
        {
        "name": "http",
        "port": 8888
        }
    ]
```

The problem occurs when a pipeline config was created using the old `loadBalancingPolicy` but Spinnaker was updated to use the new `namedPorts` data structure, without modifying the pipeline. In this scenario, the following happens:

- Running the pipeline to deploy a new version of the app will cause default values for Named Ports (http/80) to be used.
- The previous `listeningPort` value appears throughout in the Spinnaker UI (like the right sidebar when inspecting an instance group:
  -  ![a10fc636-af6e-11e7-9af5-9f6f4c769acc](https://user-images.githubusercontent.com/9409467/31633988-8d309cd2-b287-11e7-9daa-4b26920a91f0.png)

"Silently" using the default values while displaying the (incorrect) value of `listeningPort` causes much confusion and complicates troubleshooting. It's also an issue because it appears that `listeningPort` is no longer used for Named Ports, but will appear in various places if the value is there.

Comparison of pipeline JSON before fixing the deployment configuration with a Port Name Mapping:
```
"loadBalancers": [],
"loadBalancingPolicy": {
    "balancingMode": "RATE",
    "capacityScaler": 1,
    "listeningPort": 8888,
    "maxRatePerInstance": 1000
},
```

GCP shows the deployed cluster/server group/instance group was created with the default http/80 instead of 8888:
```
$ gcloud compute instance-groups describe sampleapp-v023 --project my-project --region us-central1
creationTimestamp: '2017-10-12T13:55:16.044-07:00'
description: 'This instance group is controlled by Regional Instance Group Manager
  ''sampleapp-v023''. To modify instances in this group, use the Regional
  Instance Group Manager API: https://cloud.google.com/compute/docs/reference/latest/instanceGroupManagers'
fingerprint: [redacted]
id: '[redacted]'
kind: compute#instanceGroup
name: sampleapp-v023
namedPorts:
- name: http
  port: 80
network: https://www.googleapis.com/compute/v1/projects/my-project/global/networks/my-network
region: https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1
selfLink: https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1/instanceGroups/sampleapp-v023
size: 4
subnetwork: https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1/subnetworks/my-subnetwork
```

After updating the deployment configuration with Port Name Mapping:
```
"loadBalancers": [],
"loadBalancingPolicy": {
    "balancingMode": "RATE",
    "capacityScaler": 1,
    "listeningPort": 8888,
    "maxRatePerInstance": 1000,
    "namedPorts": [
        {
        "name": "http",
        "port": 8888
        }
    ]
},
```

GCP now shows the correct configuration:
```
$ gcloud compute instance-groups describe sampleapp-v025 --project my-project --region us-central1
creationTimestamp: '2017-10-12T14:43:37.071-07:00'
description: 'This instance group is controlled by Regional Instance Group Manager
  ''sampleapp-v025''. To modify instances in this group, use the Regional
  Instance Group Manager API: https://cloud.google.com/compute/docs/reference/latest/instanceGroupManagers'
fingerprint: [redacted]
id: '[redacted]'
kind: compute#instanceGroup
name: sampleapp-v025
namedPorts:
- name: http
  port: 8888
network: https://www.googleapis.com/compute/v1/projects/my-project/global/networks/my-network
region: https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1
selfLink: https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1/instanceGroups/sampleapp-v025
size: 4
subnetwork: https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1/subnetworks/my-subnetwork
```

This is quite a serious issue because it is silently backwards-incompatible with the `listeningPort` data structure. Teams can inadvertently deploy to production in a way that might cause their app to stop working (by sending LB traffic to the wrong port). Even worse, the Spinnaker UI will display the value of `listeningPort`, even though it is not used, causing teams to believe that the configuration is correct when it is not.

*Steps to Reproduce*

- Create a pipeline that deploys a new instance group and attaches it to a load balancer. 
- Edit the pipeline JSON, and add `"listeningPort": 8888,` in the `loadBalancingPolicy` object. 
- Save the pipeline. 
- Deploy the pipeline.
- After the pipeline has been deployed, go to the Clusters view and select the newly-deployed cluster.
- In the right-hand sidebar, expand the "Port Name Mapping" section and observe that it displays "http → 8888"
- In a terminal, run `gcloud compute instance-groups describe <server group name>` and observe that the output includes:
  ```
  namedPorts:
  - name: http
    port: 80
  ```
- Now, update the deployment config of the pipeline and add a Port Name Mapping of "http" and "8888" and save the pipeline.
- Edit the pipeline JSON and observe that the `loadBalancingPolicy` now contains:
  ```
  "namedPorts": [
        {
        "name": "http",
        "port": 8888
        }
    ]
  ```
- Deploy the pipeline.
- In a terminal, run `gcloud compute instance-groups describe <server group name>` and observe that the output includes:
  ```
  namedPorts:
  - name: http
    port: 8888
  ```

*Additional Details*

I'm able to provide any additional debug/troubleshooting information if needed.

**Comment by edwinavalos** [comment] 2017-10-16 21:12
@jtk54 FYI I can get more information for you on this one, but specifically we were running clouddriver: 1.683.1 let me know what versions of the other components are needed to debug this.

**Comment by jtk54** [comment] 2017-10-17 14:19
Can you give me a priority for how important this is to address? Is it feasible for teams to update their pipeline templates to match the new deploy description?

If I collate the feedback down into deliverables: 

* Ensure that the default behavior when `listeningPort` is specified but not `namedPorts` is to use the default port name `'http'` while keeping the supplied value for `listeningPort`. (Note: this was the intended behavior.)

* Modify the server group details to render the named ports only, if a value is present for listeningPort, show a warning.

Make sense? Am I missing anything?

**Comment by jtk54** [comment] 2017-10-20 18:38
I was able to reproduce this successfully -- the namedPorts changes were indeed not backwards compatible.

I changed the UI to render `namedPorts`, not `listeningPort` in the server group details: https://github.com/spinnaker/deck/pull/4299

and modified the GCE deploy operation to default properly when provided a `listeningPort` over `namedPorts`: https://github.com/spinnaker/clouddriver/pull/2023.

**Comment by jtk54** [comment] 2017-10-23 14:02
Clouddriver fix released in 1.690.2, Deck fix in 2.1147.0. Give it a spin and let me know.

**Comment by jeffbean** [comment] 2017-10-24 22:12
I'm on a debian Halyard deployment and this issue is blocking me. I am using halyard deployment '1.4.2' and would love to test these fixes. 

Is there a way to install the updated versions of these components using halyard?

**Comment by nickjacques** [comment] 2017-10-24 22:22
@jtk54 thank you very much! Sounds like @edwinavalos and team plan on checking that out as soon as we're able to.

**Comment by jtk54** [comment] 2017-10-25 13:58
@jeffbean I can give you a version to deploy with Halyard once our build is fixed (hopefully this week, incidentally I'm working on that now).

**Comment by jtk54** [comment] 2017-10-30 16:48
@jeffbean Deploy version `master-2017-10-30-20171030063036` with Halyard to test out the namedPorts fixes. Keep in mind this version is unvalidated :)

**Comment by jtk54** [comment] 2017-10-31 20:19
@nickjacques @edwinavalos can you confirm that the behavior is fixed?

**Comment by tik-son** [comment] 2017-11-02 02:04
@jtk54 It seems that named port setting works correctly in master-2017-10-30-20171030063036.

**Closed** 2017-11-02 15:21 UTC
Labels: provider/gce
