### ISSUE TITLE
Waiting for Cassandra to start...

### ISSUE THREAD

**Issue by lygfanye** [spinnaker/spinnaker#568] opened 2015-11-17 04:46 UTC
I install it by InstallSpinnaker.sh on ubuntu, but it stop at : 

```
Reading state information... Done
cassandra-tools is already the newest version.
cassandra is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Waiting for Cassandra to start..

```

**Comment by duftler** [comment] 2015-11-17 13:21
Have you tried killing the installation script (ctrl-c) and using `cqlsh` to see if cassandra is installed and running?

That readout looks like it is already installed.

Maybe it is installed and is configured to use different ports than are configured by default?

If it is already there, and the ports don't match, you could always fetch the installation script and comment out the lines waiting for cassandra to start:

1) curl -O https://spinnaker.bintray.com/scripts/InstallSpinnaker.sh
2) vi InstallSpinnaker.sh
3) Comment out these lines:
```
if ! nc -z localhost 7199; then
    echo "Waiting for Cassandra to start..."
    while ! nc -z localhost 7199; do
       sleep 1
    done
    echo "Cassandra is ready."
fi
```
Or change from port 7199 to whatever is configured.
4) bash InstallSpinnaker.sh

**Comment by lygfanye** [comment] 2015-11-17 15:14
ok, Let me try

**Comment by lygfanye** [comment] 2015-11-19 06:31
yeahm I find the InstallSpinnaker.sh  does not start Cassandra, I start it by myself and it run next step

**Comment by skorten** [comment] 2015-11-19 18:47
@lygfanye were there any messages in /var/log/cassandra/system.log from when the while statement failed to exit?  I want to put in a fix but am not having any luck trying to reproduce the issue.

**Comment by skorten** [comment] 2015-12-04 16:31
There is a fix for this issue in https://github.com/spinnaker/spinnaker/pull/624

**Comment by hc000** [comment] 2016-02-17 00:12
I am also getting this issue, where its stuck at waiting for cassandra to start. I ctrl+c, then ran the script again, same issue.

here are the logs you asked for.
http://fpaste.org/323821/56678561/

Will try duftler's approach and see how that goes.

**Comment by tomaslin** [comment] 2016-03-14 10:28
can this issue be closed?

**Comment by hc000** [comment] 2016-03-14 16:52
After experimenting some more, in my specific case when the VM does not have enough memory there are numerous errors that comes up. But after increasing the memory everything is working when using a known good version # for all of the components.

**Closed** 2016-03-14 17:00 UTC
