### ISSUE TITLE
Docker image bound not working

### ISSUE THREAD

**Issue by axot** [spinnaker/spinnaker#5828] opened 2020-06-10 05:03 UTC
### Issue Summary:
docker image name in k8s deployment did not bound successfully.

### Cloud Provider(s):
GKE

### Environment:
Spinnaker 1.18.8 and 1.19.11 in GKE

### Feature Area:
Artifacts

### Description:
We defined a docker image artifact in a child pipeline like this,
```
{
  "defaultArtifact": {
    "artifactAccount": "docker-registry",
    "id": "3f639aa3-ab1f-4878-b585-260390ed870f",
    "name": "gcr.io/project/image",
    "reference": "gcr.io/project/image:${trigger['parentExecution']['trigger']['tag']}",
    "type": "docker/image",
    "version": "${trigger['parentExecution']['trigger']['tag']}"
  },
  "displayName": "gcr.io/project/image",
  "id": "5511c702-0ef2-4f31-84cc-93f10fdec49a",
  "matchArtifact": {
    "artifactAccount": "docker-registry",
    "id": "a7073a73-ed19-44bc-89ef-39c7c2264bb2",
    "name": "this-field-has-bug-use-expression-in-default",
    "type": "docker/image"
  },
  "useDefaultArtifact": true,
  "usePriorArtifact": false
},
```

This works in our test pipeline, but in production pipeline,
the image in k8s deployment still show as `gcr.io/project/image` without any tag name.

We also checked pipeline json source, but the json files seems correctly
```
stages[0].context.kato.tasks[0].resultObjects[0].manifests[1].spec.template.spec.containers[0].image:
gcr.io/project/image:2020.06.09_16.42.44-e3535056

stages[0].context.kato.tasks[0].resultObjects[0].boundArtifacts:
{
"customKind": false,
"reference": "gcr.io/project/image:2020.06.09_16.42.44-e3535056",
"metadata": {
"id": "3f639aa3-ab1f-4878-b585-260390ed870f"
},
"name": "gcr.io/project/image",
"artifactAccount": "docker-registry",
"type": "docker/image",
"version": "2020.06.09_16.42.44-e3535056"
},
```

### Steps to Reproduce:
Could not be reproduce this in a similar pipeline setup now.

### Additional Details:

**Comment by maggieneterval** [comment] 2020-06-12 14:51
Hi @axot! Thanks for taking the time to report this issue.

You mentioned that you are not able to reproduce this issue in a similar pipeline setup now. Are you still able to consistently reproduce this issue using the original pipeline with which you experienced the issue? If yes, would you be able to provide a diff of the working vs. non-working pipeline JSON?

Thanks!

**Comment by axot** [comment] 2020-06-12 15:29
Hi @maggieneterval, Thank you for following-ups.

Our production pipeline was very complicate, the diff will be very large, let me try next Monday and then feedback to you.

Have a nice weekend!

**Comment by axot** [comment] 2020-06-15 10:01
@maggieneterval I uploaded whole pipeline of production and child. Could please check it?
And also we found if and a `sleep 10` stage before deploy, it works fine.

![image](https://user-images.githubusercontent.com/611054/84644714-7f7bb880-af3a-11ea-9ab8-e37c58bf530f.png)
[prod_vs_test_pipeline.zip](https://github.com/spinnaker/spinnaker/files/4779470/prod_vs_test_pipeline.zip)

**Comment by axot** [comment] 2020-06-15 12:17
One more interesting thing was, in below Deploy Status view show the correct Deployment YAML. But if you check the actually yaml in k8s, the tag name was not bound :(
![image](https://user-images.githubusercontent.com/611054/84656267-62041a00-af4d-11ea-961c-3c91303243c5.png)

**Comment by maggieneterval** [comment] 2020-06-15 13:34
Hi @axot, thanks for sharing your pipeline JSON. Very strange that adding a `sleep 10` stage causes this to work as expected! Those are pretty complicated pipelines so it's difficult to tell just by looking at the JSON what could be happening here. Please feel free to share a more minimal reproducible case if possible. Also, could you please turn debug logging on and see what's happening in the manifest artifact replacement logic on [this line](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacer.java#L103)? I'm curious if the artifact it is attempting to bind is what we expect it to be at this point. And just to confirm, the expected docker artifact is specified in the appropriate Deploy stages' "Required Artifacts to Bind" field, right? If not all required artifacts are bound, Clouddriver will throw [this error](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeployManifestOperation.java#L138). It sounds like you are not seeing that error, but the expected replacement is not occurring as expected.

**Comment by axot** [comment] 2020-06-15 13:56
Hi @maggieneterval,

> could you please turn debug logging on and see what's happening in the manifest artifact replacement logic on this line? I'm curious if the artifact it is attempting to bind is what we expect it to be at this point.

Okay, let me change clouddrivers' log level tomorrow to see what happened.

>the expected docker artifact is specified in the appropriate Deploy stages' "Required Artifacts to Bind" field, right? If not all required artifacts are bound, Clouddriver will throw this error. It sounds like you are not seeing that error, but the expected replacement is not occurring as expected.

Yes, I think we not seeing this error.

1. Prod Parent -> Prod Child (Bound failed)
2. Test Parent -> Test Child (Bound success)
3. Test Parent -> Prod Child (Bound success)
4. retry Prod Child itself (Bound success)
5. add wait 10 seconds to Prod Child, then trigger again from Prod Parent. (Bound success)
6.

**Comment by axot** [comment] 2020-06-16 07:10
Hi @maggieneterval, we found KubernetesDeployManifestOperation run twice, first time was correct, and the second time was wrong.

```
05:36:44.655 DEBUG 1 --- [ionProcessor-11] .v.o.m.KubernetesDeployManifestOperation : Manifest in app-6-v2-account to be deployed: image=gcr.io/xxx/yyy:2020.06.16_10.43.29-0271c1da

05:36:47.204 DEBUG 1 --- [ionProcessor-12] .v.o.m.KubernetesDeployManifestOperation : Manifest in app-6-v2-account to be deployed: image=gcr.io/xxx/yyy
```

We have full debug log for ionProcessor-11 and ionProcessor-12, if it is useful, we could send to you via Google CE.

Thanks!

**Comment by maggieneterval** [comment] 2020-06-23 13:22
Hey @axot, thanks so much for sending the debug logs! I'm still unable to reproduce this issue on my end, so I'm going to close this for now, but I'm happy to reopen and take another look if you are able to send a minimal reproducible example (i.e.,  pipeline JSON with a single expected artifact and a single deploy stage that fails to bind it). Thanks!

**Closed by maggieneterval** 2020-06-23 13:22 UTC
Labels: provider/docker-registry, sig/kubernetes

**Comment by axot** [comment] 2020-06-25 14:41
Hi @maggieneterval, sure I think this issue may not easily reproducible in a simple pipeline. In the meaning time, I'm wondering is it normal we saw `.v.o.m.KubernetesDeployManifestOperation` appear twice in a 3 seconds span. Is it possible caused by a connection retry, or something like global locks or exception etc.? Thanks!
