### ISSUE TITLE
Add support for GCE Autoscalers.

### ISSUE THREAD

**Issue by duftler** [spinnaker/spinnaker#700] opened 2016-01-25 13:43 UTC

**Comment by duftler** [comment] 2016-02-07 05:00
When cloning a server group associated with an Autoscaler, the Autoscaler will also be cloned.
In addition, while there is no first-class ui support for configuring autoscaler properties yet, if one were to add the autoscaling properties into the json of a pipeline (via the 'Edit as JSON' action when configuring a pipeline), the new Autoscaler will be created as part of the deploy operation.

**Comment by lihan** [comment] 2017-04-27 00:37
I'm seeing following error message for Spinnaker `0.79` deployed on GKE `1.6.1`. Is following what will be addressed in this issue?
```
com.netflix.spinnaker.clouddriver.kubernetes.deploy.exception.KubernetesOperationException: Get Autoscalers in default for account my-kubernetes-account failed: the server could not find the requested resource
  at sun.reflect.GeneratedConstructorAccessor237.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
  at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
  at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
  at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor.formatException(KubernetesApiAdaptor.groovy:59)
  at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor$formatException$8.callCurrent(Unknown Source)
  at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor.exceptionWrapper(KubernetesApiAdaptor.groovy:100)
  at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
  at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor.getAutoscalers(KubernetesApiAdaptor.groovy:433)
  at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor$getAutoscalers$7.call(Unknown Source)
  at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesServerGroupCachingAgent$_buildCacheResult_closure22.doCall(KubernetesServerGroupCachingAgent.groovy:295)
```

**Comment by danielpeach** [comment] 2017-04-27 12:52
@lihan this issue should have been closed a long time ago, since Spinnaker supports GCE autoscalers.

If you're still seeing a Kubernetes bug, please open a new issue. Also, any other information you have about the bug and how we might reproduce it would be appreciated.

**Closed by danielpeach** 2017-04-27 12:52 UTC
Labels: Google Compute Engine, in-flight
