### ISSUE TITLE
Artifacts Rewrite regressions, improperly handles GCS artifact names

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#6045] opened 2020-09-11 22:20 UTC
### Issue Summary:
In 1.20 artifacts rewrite is enabled by default and future versions it unable to be disabled, it however is missing a couple core features that expected artifacts solved. 
1.) The new system is unable to handle custom references in gcs (ie name != reference)

2.) There is no way to set a default artifact, this is useful in gcs and github for pulling from a certain key/branch

### Cloud Provider(s):
gcs

### Environment:
prod

### Feature Area:
Artifacts UI

### Description:
In the old system we took advantage of the artifact resolver matching on `name` when binding trigger artifacts, this allowed up to reference changing gcs keys with the same human readable name ie:
```
{
customKind: false,
reference: "gs://artifacts-bucket/spinnaker-artifacts/example/j-j-1474/kustomized.out.yaml",
name: "kustomized.out.yaml",
type: "gcs/object",
version: "j-j-1474"
}
```

This workflow seems to work at first in the new system as I would expect i could create a new artifact name it `kustomized.out.yaml` and it should bind the trigger artifact from context named `kustomized.out.yaml`. However Spinnaker throws an error saying the artifact is invalid as it does not begin with `gcs://`, it seems the new system is unable to bind based on name and it just attempts to create an artifact in place.

Also, it is impossible to define a default artifact now, this is used by teams which infrequently change their kubernetes manifest but need override the artifact on manual executions, this flow seems impossible in the new ui.

### Steps to Reproduce:
For unable to bind custom referenced gcs artifacts
1.) Add a pubsub trigger which resolves a gcs artifact in the format seen above
2.) Add deploy stage with new artifact equal to `name` field
3.) trigger pipeline with manual or pubsub, see that the artifact throws an error for gcs://

For Default Artifacts
1.) Try to add a default artifact

### Additional Details:
Spinnaker 1.20, PubSub or webhook trigger

**Comment by maggieneterval** [comment] 2020-09-15 20:18
Hey @perek! Was looking into this and had a few questions.

> The new system is unable to handle custom references in gcs (ie name != reference)

I checked out 1.19 with the old UI, and 1.20 with the new UI, and they look pretty much the same for GCS, with only an Object Path input in both the Match and Default artifact forms. Was there an older version that had more fields available and allowed you to define different `name` and `reference` fields? You should probably be able to define a _custom_ artifact of type `gcs/object` with different `name` and `reference` fields if you need to, though I haven't tested this.

> There is no way to set a default artifact

You should be able to set a default artifact in the "If Missing" section the same way you did in the old UI. Including screenshots of old vs. new for reference.


<details><summary>1.19 (old UI)</summary>
<p>

![6SSTRXGazhLLQX4](https://user-images.githubusercontent.com/15936279/93258125-d4161600-f76b-11ea-994f-66709b1e267c.png)

</p>
</details>

<details><summary>1.20 (new UI)</summary>
<p>

![6WoXtACVcpopixb](https://user-images.githubusercontent.com/15936279/93259474-e85b1280-f76d-11ea-9713-f189f508de68.png)


</p>
</details>


Let me know what I'm missing; thanks @perek! 🤗

**Comment by maggieneterval** [comment] 2020-09-16 14:02
Pere and I chatted offline; there was some confusion as the expectation was that the dialog that includes both "match" and "default" artifacts would be inline in individual stages, when actually this dialog exists only in the "artifact constraint" field of triggers. While there are certainly UX improvements to be made with the new UI, this is not a bug, so I'm going to close this issue for now.

**Closed by maggieneterval** 2020-09-16 14:02 UTC
Labels: sig/ui-ux
