### ISSUE TITLE
Error running packer to bake an image

### ISSUE THREAD

**Issue by hiradha** [spinnaker/spinnaker#757] opened 2016-02-18 20:59 UTC
I am seeing the following errors in rosco/rush when I start the bake process in "Getting Started" guide example. 

I cannot seem to find packer installed in the rush container. Should packer be installed in rush manually or am I missing something. The guide does not say anything about this being a precursor step.
I  am new to docker - so not exactly sure.

{"logsContent":"Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program \"packer\" (in directory \".\"): error=2, No such file or directory)"}
<--- END HTTP (178-byte body)
2016-02-18 20:52:19.278 ERROR 1 --- [.0-8087-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "packer" (in directory "."): error=2, No such file or directory)] with root cause

java.lang.IllegalArgumentException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "packer" (in directory "."): error=2, No such file or directory)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)

**Comment by duftler** [comment] 2016-02-18 21:11
packer is required by rush.

@tomaslin How was packer accessed in the rush container before?

There was some discussion on slack about making packer an explicit dependency of the rush package, but that isn't the case today (the install scripts first install packer, prior to installing rush).

**Comment by tomaslin** [comment] 2016-02-23 09:51
there was never a requirement for packer in rush before since this was within a docker container

**Comment by stevehiley** [comment] 2016-03-03 03:18
Hello,

I encountered the same error in the "Getting Started" guide, http://spinnaker.io/documentation/getting_started.html. This happens when I kick off the "start manual execution" of my new test pipeline.

**Same exception:**
Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "packer" (in directory "."): error=2, No such file or directory)

Is there a workaround or fix that will be coming here?

Thank you!

**Comment by duftler** [comment] 2016-03-03 15:51
The `/opt/rosco/config/packer` directory is where the packer templates and scripts will be installed (that is, the artifacts for use by packer when building/provisioning new images).
You need to be able to ssh into your rush machine, login as whatever user rush will attempt to execute jobs as, and enter `packer`. If this doesn't result in seeing the packer 'help' output, there is no way that images will be successfully built.

**Comment by stevehiley** [comment] 2016-03-03 20:16
@duftler Thanks for the hint. I am running Spinnaker in AWS. All child services are running as the spinnaker user on that VM (I confirmed in rosco log). I added the path to my self-installed packer binary to the running user's (spinnaker) .profile, which should provide visibility to the running processes, and confirmed that this user can find "packer" from the command line. The error from Spinnaker persists though (after restart of service).

If I take the error message at face value, it is looking for packer in the current directory ("."), which would explain why adding it to the path has no effect. What directory that is in this context, I have no idea.

I'd like to get this sample app working however I can. The larger issue seems to be a packaging issue of including the right dependencies in the right places for using together, as indicated in your earlier comments.

**Comment by stevehiley** [comment] 2016-03-04 01:08
**Update:** I finally got a workaround running. In addition to downloading and installing packer, I had to add the path for that to /opt/rush/bin/rush script:
`PATH=$PATH:/usr/local/packer`
Adding it to the .profile on the root and spinnaker accounts had no effect. I can only surmise that the startup scripts upstream are resetting the path to some absolute. Very frustrating ...

**Closed** 2016-03-11 16:11 UTC
