### ISSUE TITLE
Deploying v2 Manifest: sometimes "Force Cache Refresh" takes 12 minutes to complete

### ISSUE THREAD

**Issue by mcombell-cafex** [spinnaker/spinnaker#3366] opened 2018-09-21 15:02 UTC
### Issue Summary:

When deploying a v2 manifest, sometimes the "Force Cache Refresh" task takes 12 minutes to complete.

### Cloud Provider(s):

Kubernetes

### Environment:

Spinnaker version 1.9.3
Kubernetes version 1.9.3
1 master node: 24 CPU cores, 48GB memory
10+ worker nodes: each has 24 CPU cores, 48GB memory
50+ namespaces with lots of deployments, etc

### Feature Area: 

Pipeline, Cloud Driver, Orca

### Description:

We are using a Helm template to deploy a v2 manifest to Kubernetes. Most of the time, this completes the whole process within a minute or two. However, sometimes, it takes much longer than expected because the "Force Cache Refresh" step takes just over 12 minutes to complete as shown below:

```
Task                            Duration
Deploy Manifest                 00:00
Monitor Deploy                  00:05
Promote Outputs                 00:00
Force Cache Refresh             12:03
Wait For Manifest To Stabilize  00:00
Cleanup Artifacts               00:00
Bind Produced Artifacts         00:00
```

Normally, the "Force Cache Refresh" step takes less than 1 minute and is often less than 15 seconds to complete. We are seeing the slow "Force Cache Refresh" once every 10 to 20 runs of the pipeline.

There have been similar reported issues that have seemed to have been caused by high CPU usage. This is not the case for our Kubernetes cluster as the cluster has plenty of available CPU and memory resources available.

### Steps to Reproduce:

1. Create a Pipeline that deploys a v2 manifest that contains multiple Kubernetes resources (e.g. deployment, ingress, config map, service, secret). In our case, there were 6 items that were deployed to Kubernetes
1. Run the pipeline and wait for it to complete
1. Check the details for the "Deploy Manifest" stage and check how long the "Force Cache Refresh" step takes.
1. keep on re-running the pipeline until the "Force Cache Refresh" takes approximately 12 minutes.

**Comment by mcombell-cafex** [comment] 2018-09-21 15:13
Unfortunately, I cannot attach log files. Sorry.


### Overview of code behaviour

Having looked in the code, the force cache refresh is managed by the `ManifestForceCacheRefreshTask` class in Orca. In that code, there is a 12 minute timeout for force cache refreshes. For whatever reason, we are occasionally hitting this 12 minute timeout.

```
private final long autoSucceedAfterMs = TimeUnit.MINUTES.toMillis(12);
```

Looking further at the code, the timeout is only triggered if Orca believes one or more of the force cache refresh requests to the cloud driver has not finished processing.



In the `ManifestForceCacheRefreshTask` class in Orca, the `execute()` contains the following code:

```
if (refreshManifests(cloudProvider, account, stageData)) {
  return new TaskResult(SUCCEEDED, toContext(stageData));
} else {
  return checkPendingRefreshes(cloudProvider, account, stageData, startTime);
}
```

Orca calls the `refreshManifests()` method to tell the cloud driver to refresh the requested manifests using the Cache Service `forceCacheUpdate()` method. This can return a HTTP 200 if the response is processed immediately or a HTTP 202 if the refresh is being done asynchronously. 

If Orca gets a HTTP 200, the refresh request is added to the `processedManifests Set` on the `StageData`.

For Kubernetes, we are always seeing a HTTP 202 response as the refresh is being handled asynchronously. This means that the `refreshManifests()` method will return false as not all the manifests have been refreshed synchronously.


At this point, Orca knows there are outstanding refreshes so it calls the `checkPendingRefreshes()` method every few seconds which checks the status of each of the outstanding requests. (main code lines shown below with some less relevant code snipped out)

```
    Collection<PendingRefresh> pendingRefreshes = objectMapper.convertValue(
        cacheStatusService.pendingForceCacheUpdates(provider, REFRESH_TYPE),
        new TypeReference<Collection<PendingRefresh>>() { }
    );

    // snip

    for (Map.Entry<String, List<String>> entry : deployedManifests.entrySet()) {

        // snip

        if (processedManifests.contains(id)) {   // NOTE: Skips over any already processed manifests
          continue;
        }

        // snip

        if (pendingRefresh.isPresent()) {
          if (!pendingRefreshProcessed(pendingRefresh.get(), refreshedManifests, startTime)) {
            allProcessed = false;
          }
        } else {
          log.warn("No pending refresh of {} in {}", id, account);
          allProcessed = false;
          refreshedManifests.remove(id);
        }
    }
```

The code invokes the `cacheStatusService.pendingForceCacheUpdates()` method to obtain the list of outstanding asynchronous refreshes. Orca then checks each asynchronous refresh to see if they have completed. If any of them have not completed, it will check again a second later. If they all have completed then the force cache refresh has completed successfully.



Looking in the cloud driver code, the force refresh requests will be added to a task queue. This results in the `loadData()` method of the `KubernetesV2OnDemandCachingAgent` class being invoked. This appears to be run every 30 seconds and has 2 main activities:

* Keep any tasks that have not yet completed
* evict any completed tasks that have been in the cache for longer than the `cachetime` (30 seconds)




### The bug


I believe this bug happens only occasionally because it is a timing issue between when Orca is sending force cache refreshes to the Cloud Driver and when the cloud driver is processing the pending force cache refreshes.

What appears to be occasionally happening is:

1) Orca requests all the manifest force cache refreshes that it requires but they all return HTTP 202 (asynchronous) so Orca knows they are pending
2) Orca checks whether the pending refreshes have all been processed, it sees that **some of them** have been processed but some have not.
3) Orca will keep polling every few seconds but none of the pending force cache refreshes will be updated as the cloud driver only checks every 30 second for completed tasks.
4) After 30 seconds, the cloud driver task runs, and evicts the previously processed force cache refreshes (from step 2) and marks the rest as completed.
5) Orca will poll the pending force cache refreshes again and see that the remaining pending refreshes have now finished.
6) BUG: The problem is that Orca has "forgotten" about the earlier force cache refreshes that completed in step 2 and thinks they have not been refreshed.

It appears to be a timing issue.


### Proposed bug fix


In the `refreshManifests()` method, if a force cache refresh completes synchronously, it is added to the `stageData.processedManifests` list.

For asynchronous refreshes, the code should be updated to also add the completed refresh to the `stageData.processedManifests` list when an asynchronous refresh completes.

The code was:

```
if (pendingRefresh.isPresent()) {
  if (!pendingRefreshProcessed(pendingRefresh.get(), refreshedManifests, startTime)) {
    allProcessed = false;
  }
} else {
```

But it should become:

```
if (pendingRefresh.isPresent()) {
  if (pendingRefreshProcessed(pendingRefresh.get(), refreshedManifests, startTime)) {
    processedManifests.add(id);
  } else {
    allProcessed = false;
  }
} else {
```


### Effect of using this proposed bug fix


Most cache refreshes now take less than 30 seconds. Occasionally, a force cache refresh takes up to 33 seconds. It all depends on the timing of when Orca sends the cache refresh requests and when the 30 second Cloud Driver update task runs.

**Comment by mcombell-cafex** [comment] 2018-09-21 15:14
I have implemented this proposed fix at https://github.com/mcombell-cafex/orca/commit/3bea999200bc5915085251f61171219bb4eadf6f

This is based off the version-1.0.0 tag of Orca

**Comment by lwander** [comment] 2018-09-24 16:56
Nice work! Thanks for the detailed writeup & PR :)

**Comment by NaranKPatel** [comment] 2018-09-24 17:36
> Nice work! Thanks for the detailed writeup & PR :)

Hi Lars,
WIll the fix be included in upcoming 1.94 release or still needs to go through regression tests so later?

**Comment by lwander** [comment] 2018-09-24 18:13
I can cherry pick into the 1.9 branch, we run an integration test suite a few times a day which should catch any lingering issues.

**Comment by lwander** [comment] 2018-09-24 20:01
Thanks again @mcombell-cafex -- I'm going to close this.

This will be going into the next 1.9 release as well as 1.10 pending integration tests

**Closed by lwander** 2018-09-24 20:01 UTC

**Comment by indrayam** [comment] 2018-10-04 00:03
Cannot wait to test this one out!

**Comment by tonyg4864** [comment] 2019-01-18 00:11
I am running Spinnaker 1.11.x and I still see this issue. Any recommendations?

**Comment by NaranKPatel** [comment] 2019-01-18 01:18
Try to leverage omit kinds to reduce the addressable namespaces and references that have to be traversed. If that doesn't help raise an issue with clear reproducibility steps, hopefully, someone will take a look at it.

**Comment by tonyg4864** [comment] 2019-01-21 19:44
I noticed that the Force Cache Refresh task takes about 5 minutes on a Spinnaker instance running on Kubernetes 1.11.5. This is better than 12 minutes when running on Kubernetes 1.9.5.

**Comment by lwander** [comment] 2019-01-23 14:53
Spinnaker 1.12 (release candidate is out this week) has a number of changes to the caching culminating in this PR https://github.com/spinnaker/clouddriver/pull/3227 to allow you skip the cache during pipeline runs. This turns forceCacheRefresh time down to the order of seconds, and ensures all stability checks are run against live resources.

**Comment by MrBlaise** [comment] 2019-05-15 15:34
This issue just surfaced for us using 1.13.6.

Exactly 12 minutes :/

**Comment by edubacco** [comment] 2019-05-30 12:25
same error here.

spinnaker version: 1.12.5
orca version: gcr.io/spinnaker-marketplace/orca:2.4.0-20190308182538
k8s version: 1.12

12:02 minutes to flush caches

it does not seems to happen on a cluster with k8s version 1.11, managed with the same spinnaker instance

**Comment by neakor** [comment] 2019-07-30 21:45
We are seeing the same issue on version 1.14.9.

**Comment by skolomiiets** [comment] 2019-09-24 14:41
Same error.
Force Cache Refresh 04:43
Spinnaker version: 1.16.1
k8s version: 1.14.3

**Comment by linjmeyer** [comment] 2019-09-30 18:01
I ran into this today and was able to fix it.  Same issue, manifests were deploying but the cache step was exactly 12 min every time.  The solution/problem may vary, but for me I was getting cache related exceptions in clouddriver.  This log file shows it was related to the `podPreset` kind which cloud driver was trying to get from my cluster.  That kind doesn't exist, leading to exceptions, leading to failed cache.


c.n.s.c.k.v.c.a.KubernetesV2CachingAgent : my-cluster-name/**KubernetesCoreCachingAgent**[1/1]: Failed to read kind [apiService, clusterRole, clusterRoleBinding, configMap, controllerRevision, customResourceDefinition, cronJob, daemonSet, deployment, event, horizontalpodautoscaler, ingress, job, mutatingWebhookConfiguration, namespace, networkPolicy, persistentVolume, persistentVolumeClaim, pod, podPreset, podSecurityPolicy, podDisruptionBudget, replicaSet, role, roleBinding, secret, service, serviceAccount, statefulSet, storageClass, validatingWebhookConfiguration] from namespace ingress-nginx: Failure running list on [apiService, clusterRole, clusterRoleBinding, configMap, controllerRevision, customResourceDefinition, cronJob, daemonSet, deployment, event, horizontalpodautoscaler, ingress, job, mutatingWebhookConfiguration, namespace, networkPolicy, persistentVolume, persistentVolumeClaim, pod, podPreset, podSecurityPolicy, podDisruptionBudget, replicaSet, role, roleBinding, secret, service, serviceAccount, statefulSet, storageClass, validatingWebhookConfiguration]: error: **the server doesn't have a resource type "podPreset"**

Updating the kubernetes account to omit podPreset did the trick.  
`hal config provider kubernetes account edit my-kubernetes-account --omit-kinds=podPreset`

That's pretty specific so I expect most people finding this issue won't have that exact problem, but take a look at orca and clouddriver logs to find the real problem.

**Comment by gtpark** [comment] 2019-10-25 10:17
i have same error
kuberentes v2
force cache refresh 11:xx
spinnaker version 1.16.4

**Comment by geek876** [comment] 2019-12-13 23:55
I have same error too. Kubernetes v2. Spinnaker version 1.16.0. The 'force cache' takes 10 - 12 minutes but the stage passes without errors. 

For us, orca seems to keep waiting as we can see these message repeating for 10 min or so. 

```
2019-12-13 23:19:05.410  INFO 1 --- [    handlers-12] .s.o.c.t.m.ManifestForceCacheRefreshTask : [xxxx] Pending refresh of ManifestForceCacheRefreshTask.PendingRefresh(scopedManifest=ManifestForceCacheRefreshTask.ScopedManifest(account=xxx-aks-v2-account, location=default, name=replicaSet myapp-frontend-v000), processedTime=-1, cacheTime=1576279134947, processedCount=0) was cached as a part of this request, but not processed
....
...
2019-12-13 23:29:05.410  INFO 1 --- [    handlers-12] .s.o.c.t.m.ManifestForceCacheRefreshTask : [xxxx] Pending refresh of ManifestForceCacheRefreshTask.PendingRefresh(scopedManifest=ManifestForceCacheRefreshTask.ScopedManifest(account=xxx-aks-v2-account, location=default, name=replicaSet myapp-frontend-v000), processedTime=-1, cacheTime=1576279134947, processedCount=0) was cached as a part of this request, but not processed
2019-12-13 23:29:32.769  INFO 1 --- [    handlers-15] c.n.s.orca.clouddriver.OortService       : [xxx] ---> HTTP GET http://spin-clouddriver.spinnaker:7002/manifests/xxx-aks-v2-account/default/replicaSet%20myapp-frontend-v000?includeEvents=false
2019-12-13 23:29:32.830  INFO 1 --- [    handlers-15] c.n.s.orca.clouddriver.OortService       : [xxx] <--- HTTP 200 http://spin-clouddriver.spinnaker:7002/manifests/xxx-aks-v2-account/default/replicaSet%20myapp-frontend-v000?includeEvents=false (60ms)
2019-12-13 23:29:39.002  INFO 1 --- [    handlers-12] c.n.s.orca.clouddriver.OortService       : [xxx] ---> HTTP GET http://spin-clouddriver.spinnaker:7002/applications/test/clusters/xxx-aks-v2-account/replicaSet%20myapp-frontend/kubernetes
2019-12-13 23:29:39.151  INFO 1 --- [    handlers-12] c.n.s.orca.clouddriver.OortService       : [xxx] <--- HTTP 200 http://spin-clouddriver.spinnaker:7002/applications/test/clusters/xxx-aks-v2-account/replicaSet%20myapp-frontend/kubernetes (148ms)
```

However, we can see in clouddriver logs that the cache request did complete successfully without error 

```
2019-12-13 23:18:54.946  INFO 1 --- [0-7002-exec-139] k.v.c.a.KubernetesV2OnDemandCachingAgent : xxx-aks-v2-account/KubernetesCoreCachingAgent[1/1]: Storing on demand 'kubernetes.v2:infrastructure:replicaSet:xxx-aks-v2-account:default:myapp-frontend-v000'
2019-12-13 23:18:54.949  INFO 1 --- [0-7002-exec-139] k.v.c.a.KubernetesV2OnDemandCachingAgent : xxx-aks-v2-account/KubernetesCoreCachingAgent[1/1]: On demand cache refresh of (data: {account=xxx-aks-v2-account, location=default, name=replicaSet myapp-frontend-v000}) succeeded
2019-12-13 23:18:54.989  INFO 1 --- [0-7002-exec-139] c.n.s.c.cache.CatsOnDemandCacheUpdater   : kubernetes/com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.agent.KubernetesCoreCachingAgent@550244cb?.onDemandAgentType handled Manifest in 1644 millis. Payload: [account:xxx-dev01-aks-v2-account, location:default, name:replicaSet myapp-frontend-v000]

**Comment by vuxuanlai** [comment] 2020-06-01 03:28
Same error in version 1.20.2
------
![Screenshot from 2020-06-01 10-28-26](https://user-images.githubusercontent.com/1458400/83373484-a8f0fc00-a3f2-11ea-9530-b7a35cf4251d.png)

**Comment by notetook** [comment] 2020-06-02 08:14
i also have same issue
kubernetes v2, spinnaker 1.20.4

**Comment by vuxuanlai** [comment] 2020-06-04 09:59
I followed this guide (https://community.spinnaker.io/t/wait-for-manifest-to-stabilize-in-deploy-manifest-takes-a-long-time/1163/4) and the problem was resolved.

**Comment by shiwano** [comment] 2021-01-31 03:13
If your Spinnaker version is less than 1.23 and the `Force Cache Refresh` step is taking a long time, upgrading the version to 1.23 or higher may solve the problem.
That solved the problem for me.

ref: https://github.com/spinnaker/spinnaker/issues/6079#issuecomment-720784502

**Comment by sprutner** [comment] 2021-12-16 03:40
The guide linked above (https://community.spinnaker.io/t/wait-for-manifest-to-stabilize-in-deploy-manifest-takes-a-long-time/1163/4) is now a dead link.

**Comment by dbyron-sf** [comment] 2021-12-16 04:33
@sprutner sorry that that link doesn't work.  I believe https://web.archive.org/web/20200613133332/https://community.spinnaker.io/t/wait-for-manifest-to-stabilize-in-deploy-manifest-takes-a-long-time/1163 has the same contents.  What version of spinnaker are you running?  I definitely recommend upgrading to >= 1.23, ideally to 1.26.x / the latest.  May be easier to discuss/get help on [spinnaker slack](http://join.spinnaker.io/).
