### ISSUE TITLE
Unrecognized field for halyard version 1.8.2 and higher

### ISSUE THREAD

**Issue by bo-tu** [spinnaker/spinnaker#5654] opened 2020-04-08 03:36 UTC
Hi team, 

I got error as below for "armory/halyard-armory:1.8.4-rc570",  "armory/halyard-armory:1.8.3",  and "armory/halyard-armory:1.8.2".  It works fine for "armory/halyard-armory:1.8.1".

bash-4.4$ hal deploy apply
 Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "plugins" (class
  com.netflix.spinnaker.halyard.config.model.v1.node.ArmoryDeploymentConfiguration),
  not marked as ignorable (19 known properties: "security", "artifacts",
  "providers", "pubsub", "persistentStorage", "ci", "notifications", "repository",
  "name", "deploymentEnvironment", "webhook", "version", "timezone", "armory",
  "features", "stats", "metricStores", "canary", "spinnaker"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  io.armory.halyard.config.model.v1.node.ArmoryHalconfig["deploymentConfigurations"]-java.util.ArrayList[0]-com.netflix.spinnaker.halyard.config.model.v1.node.ArmoryDeploymentConfiguration["plugins"])
Failed to get deployment name.

**Comment by bo-tu** [comment] 2020-04-08 03:57
this is about `halyard-armory`,  I might raise this issue in wrong place.  I'm sorry for that,  and please feel free to close this issue.

**Comment by maggieneterval** [comment] 2020-04-08 15:59
Closing this as a duplicate of https://github.com/spinnaker/spinnaker/issues/5606

cc @link108 in case you need to pull @plumpy's [fix](https://github.com/spinnaker/halyard/pull/1583) into Armory Spinnaker.

**Closed by maggieneterval** 2020-04-08 15:59 UTC
