### ISSUE TITLE
MissingMethodException when executing Deploy stage to kubernetes cluster

### ISSUE THREAD

**Issue by philsttr** [spinnaker/spinnaker#1220] opened 2016-10-10 23:57 UTC
_Title_

MissingMethodException when executing Deploy stage to kubernetes cluster

_Cloud Provider_

Kubernetes

_Environment_

I'm running all spinnaker components on a local Ubuntu 14.04 vm to try it out.

```
# dpkg -l | grep spinnaker
ii  spinnaker                                             0.63.0-3                                            all          spinnaker
ii  spinnaker-clouddriver                                 1.361.0                                             all          spinnaker-clouddriver
ii  spinnaker-deck                                        2.844.0-3                                           all          spinnaker-deck
ii  spinnaker-echo                                        1.110.0-3                                           all          spinnaker-echo
ii  spinnaker-fiat                                        0.11.0                                              all          spinnaker-fiat
ii  spinnaker-front50                                     1.48.0-3                                            all          spinnaker-front50
ii  spinnaker-gate                                        2.79.0-3                                            all          spinnaker-gate
ii  spinnaker-igor                                        1.53.0-3                                            all          spinnaker-igor
ii  spinnaker-orca                                        1.230.0-3                                           all          spinnaker-orca
ii  spinnaker-rosco                                       0.60.0-3                                            all          spinnaker-rosco
```

_Feature Area_

Pipelines - Deployment stage

_Description_

When executing a pipeline with a deployment stage that deploys to a kubernetes cluster, an exception is received (see below) and the pipeline fails.

_Steps to Reproduce_

I have a simple pipeline with only a deploy stage in it (see below).  When executing the pipeline, the exception below is output by orca.

_Additional Details_

Pipeline:

```
{
  "appConfig": {},
  "keepWaitingPipelines": false,
  "limitConcurrent": true,
  "parallel": true,
  "parameterConfig": [],
  "stages": [
    {
      "application": "foo",
      "cloudProvider": "kubernetes",
      "cloudProviderType": "kubernetes",
      "cluster": "foo-3886942430",
      "clusters": [
        {
          "account": "my-kubernetes-account",
          "application": "foo",
          "cloudProvider": "kubernetes",
          "containers": [
            {
              "_uiSelectChoiceDisabled": false,
              "args": [],
              "command": [],
              "envVars": [],
              "imageDescription": {
                "account": "registry-docker",
                "imageId": "registry-docker/simpleapp:5.50.0",
                "registry": "registry-docker",
                "repository": "simpleapp",
                "tag": "5.50.0"
              },
              "imagePullPolicy": "IFNOTPRESENT",
              "limits": {
                "cpu": null,
                "memory": null
              },
              "livenessProbe": null,
              "name": "simpleapp",
              "ports": [],
              "readinessProbe": null,
              "requests": {
                "cpu": null,
                "memory": null
              },
              "volumeMounts": []
            }
          ],
          "interestingHealthProviderNames": [
            "KubernetesContainer",
            "KubernetesPod"
          ],
          "namespace": "playground",
          "provider": "kubernetes",
          "region": "playground",
          "strategy": "",
          "targetSize": 1,
          "useAutoscaler": false,
          "volumeSources": []
        }
      ],
      "comments": "",
      "credentials": "my-kubernetes-account",
      "failPipeline": true,
      "judgmentInputs": [],
      "name": "Deploy",
      "namespaces": [],
      "notifications": [],
      "onlyEnabled": true,
      "pipeline": null,
      "refId": "1",
      "requisiteStageRefIds": [],
      "selectionStrategy": "LARGEST",
      "type": "deploy",
      "user": "[anonymous]"
    }
  ],
  "triggers": []
}

```

Exception:

```
2016-10-10 16:23:10.347 ERROR 22064 --- [0.1-8083-exec-4] c.n.spinnaker.orca.batch.StageBuilder    : Exception occurred while building flow builder

groovy.lang.MissingMethodException: No signature of method: java.lang.String.get() is applicable for argument types: (java.lang.String) values: [providerType]
Possible solutions: getAt(java.lang.String), next(), grep(), next(), getAt(int), getAt(int)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
        at com.netflix.spinnaker.orca.kato.pipeline.ParallelDeployStage.clusterContext(ParallelDeployStage.groovy:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1073)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1080)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:2348)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:2318)
        at org.codehaus.groovy.runtime.dgm$63.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.netflix.spinnaker.orca.kato.pipeline.ParallelDeployStage.parallelContexts(ParallelDeployStage.groovy:171)
        at com.netflix.spinnaker.orca.kato.pipeline.ParallelDeployStage.buildFlows(ParallelDeployStage.groovy:58)
        at com.netflix.spinnaker.orca.pipeline.ParallelStage.buildInternal(ParallelStage.groovy:49)
        at com.netflix.spinnaker.orca.batch.StageBuilder.buildParallel(StageBuilder.groovy:191)
        at com.netflix.spinnaker.orca.batch.StageBuilder.build(StageBuilder.groovy:89)
        at com.netflix.spinnaker.orca.batch.StageBuilder$_buildDependentStages_closure9.doCall(StageBuilder.groovy:247)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
        at com.netflix.spinnaker.orca.batch.StageBuilder.buildDependentStages(StageBuilder.groovy:212)
        at com.netflix.spinnaker.orca.batch.StageBuilder.buildParallel(StageBuilder.groovy:192)
        at com.netflix.spinnaker.orca.batch.StageBuilder.build(StageBuilder.groovy:89)
        at com.netflix.spinnaker.orca.pipeline.PipelineJobBuilder.createStage(PipelineJobBuilder.groovy:121)
        at com.netflix.spinnaker.orca.pipeline.PipelineJobBuilder.buildFlowParallel(PipelineJobBuilder.groovy:114)
        at com.netflix.spinnaker.orca.pipeline.PipelineJobBuilder.build(PipelineJobBuilder.groovy:49)
        at com.netflix.spinnaker.orca.pipeline.PipelineJobBuilder.build(PipelineJobBuilder.groovy)
        at com.netflix.spinnaker.orca.pipeline.ExecutionStarter.createJob(ExecutionStarter.groovy:96)
        at com.netflix.spinnaker.orca.pipeline.ExecutionStarter.startExecution(ExecutionStarter.groovy:65)
        at com.netflix.spinnaker.orca.pipeline.ExecutionStarter.start(ExecutionStarter.groovy:61)
        at com.netflix.spinnaker.orca.pipeline.ExecutionStarter$start.call(Unknown Source)
        at com.netflix.spinnaker.orca.controllers.OperationsController.startPipeline(OperationsController.groovy:168)
        at com.netflix.spinnaker.orca.controllers.OperationsController.this$2$startPipeline(OperationsController.groovy)
        at com.netflix.spinnaker.orca.controllers.OperationsController$this$2$startPipeline$0.callCurrent(Unknown Source)
        at com.netflix.spinnaker.orca.controllers.OperationsController.orchestrate(OperationsController.groovy:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:867)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:841)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:300)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.netflix.spinnaker.orca.web.config.WebConfiguration$1.doFilter(WebConfiguration.groovy:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at javax.servlet.FilterChain$doFilter.call(Unknown Source)
        at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by ttomsu** [comment] 2016-10-11 13:03
Lars is out today, but he should be able to look at it tomorrow.

**Comment by lwander** [comment] 2016-10-12 16:47
This is a great bug report btw @philsttr, thank you.

Did you make any manual edits to the pipeline JSON outside of the UI?

**Comment by philsttr** [comment] 2016-10-12 17:23
Yes.  I changed the value of the container image tag.  (Was mainly just testing out editing as JSON)

Additionally, I did change a few names to obfuscate it prior to pasting it in this issue.  Does something look out of the ordinary in it?

BTW, yesterday, I deleted the problem pipeline and created a new one.  The new one is working.  That unblocks me, but doesn't help root causing the issue I ran into.

Here's the new pipeline (again with the same obfuscations applied):

```
{
  "keepWaitingPipelines": false,
  "limitConcurrent": true,
  "parallel": true,
  "stages": [
    {
      "clusters": [
        {
          "account": "my-kubernetes-account",
          "application": "foo",
          "cloudProvider": "kubernetes",
          "containers": [
            {
              "_uiSelectChoiceDisabled": false,
              "args": [],
              "command": [],
              "envVars": [],
              "imageDescription": {
                "account": "registry-docker",
                "imageId": "registry-docker/simpleapp:5.50.0",
                "registry": "registry-docker",
                "repository": "simpleapp",
                "tag": "5.50.0"
              },
              "imagePullPolicy": "IFNOTPRESENT",
              "limits": {
                "cpu": null,
                "memory": null
              },
              "livenessProbe": null,
              "name": "simpleapp",
              "ports": [],
              "readinessProbe": null,
              "requests": {
                "cpu": null,
                "memory": null
              },
              "volumeMounts": []
            }
          ],
          "freeFormDetails": null,
          "interestingHealthProviderNames": [
            "KubernetesContainer",
            "KubernetesPod"
          ],
          "loadBalancers": [],
          "namespace": "pclay",
          "provider": "kubernetes",
          "region": "pclay",
          "restartPolicy": null,
          "securityGroups": [],
          "stack": null,
          "strategy": "",
          "targetSize": 4,
          "volumeSources": []
        }
      ],
      "name": "Deploy",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "deploy"
    }
  ],
  "triggers": []
}
```

I definitely see a few differences there.  Perhaps that will provide a clue.

**Comment by lwander** [comment] 2016-10-12 17:36
There's quite a few fields different from what I got when trying to reproduce this, and the second pipeline JSON you posted is basically what I see when creating a pipeline. Do you remember making any changes with the UI before running the pipeline, even if you didn't intentionally save them?

**Comment by philsttr** [comment] 2016-10-12 17:52
I was messing with the old pipeline for a few hours in the UI trying to get it to work.  So yes, I definitely changed a lot of things (adding/removing tiggers, adding/removing server groups, changing server group configuration, removing/adding deploy stages.... pretty much the whole gamut).  However, that was _after_ I originally ran into the issue.  So those changes might be moot, because it was probably already in a bad state.

Prior to getting the error, I don't remember doing much to the pipeline.  The error happened on my first attempt at running a pipeline.  IIRC, all I did was create the pipeline with a deploy stage with a server group.  I used an existing server group as a template.  Hmm.  that might actually be something... because the server group I used as a template was one that was discovered from kubernetes, rather than being created through spinnaker.

**Comment by lwander** [comment] 2016-10-12 18:07
hey @danielpeach any insight into why those extra fields may have been added by deck?

**Comment by danielpeach** [comment] 2016-10-14 14:50
I don't have any good ideas, though I will look around. My best guess is that we're not deep copying pipeline JSON where we should be, similar to the situation where we ended up with backing data in pipeline JSON.

**Comment by ethanfrogers** [comment] 2017-11-17 17:24
@philsttr i'm going to close this since there hasn't been any activity. if anyone runs into this again, we can repoen.

**Closed by ethanfrogers** 2017-11-17 17:24 UTC
Labels: bug, provider/kubernetes
