### ISSUE TITLE
Patch (Manifest) stage applies update on the wrong Deploy (Manifest)

### ISSUE THREAD

**Issue by jacogreyling** [spinnaker/spinnaker#5563] opened 2020-03-12 10:14 UTC
### Issue Summary:

When Spinnaker deploys a new replicaSet (Spinnaker manages traffic plus Strategy = None), and on the next stage I try to patch that same deployment, the update is wrongly applied to the second newest. However... if I add a 5 second delay between the steps it successfully update the latest replicaSet.

### Cloud Provider(s):

Kubernetes v1.13.9 

### Environment:

Spinnaker 1.17.6

### Feature Area:

Kubernetes V2

### Description:

When Spinnaker deploys a new replicaSet (Spinnaker manages traffic plus Strategy = None), and on the next stage I try to patch that same deployment, the update is wrongly applied to the second newest (aka current active version).

We're trying to do a dark launch where no client traffic is send to the new version. Then what I do is patch that manifest so my testers can test that new deployment on a separate service/ingress. This works brilliantly however, without any delay between those two stages, the patch operation goes and apply the new labels on the current active (aka second newest) manifest which is wrong.

However if I add a 5 second delay between the steps it successfully update the latest replicaSet. It almost like Spinnaker cache doesn't update quickly enough and when the next stage starts, Spinnaker 'thinks' that the previous deployment is still the latest one. Not sure if it's because I'm setting my deployment strategy to None? I need this however to simulate a dark deployment...

### Steps to Reproduce:

My Deploy (Manifest) step:

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/22909784/76509620-019aa380-6459-11ea-8e80-f55d7041e54a.png">

YAML: 
metadata:
  name: example-api-v028
kind: replicaSet
...

My Patch (Manifest) step:

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/22909784/76509737-2a229d80-6459-11ea-9e15-2471813afe2d.png">

YAML:
metadata:
  name: example-api-v027 <--- WRONG
kind: replicaSet

**Comment by ezimanyi** [comment] 2020-03-21 00:54
@jacogreyling : Do you have `liveManifestCalls: true` set on the account in question?

(Actually, I think the answer is yes, because I also have #5451 in my inbox which I've been meaning to reply to...I'll reply on that one right after this, sorry for the delay.)

The big problem with `liveManifestCalls` is that it makes stages complete a lot faster, but at the expense of not waiting for clouddriver's cache to update.  This means that operations don't leave the cache in a consistent state, and subsequent operations that use the cache to decide what to do will fail (or do the wrong thing).

In general any operation that requires figuring out and grouping workloads relies on the cache, and will not work well with `liveManifestCalls` enabled.  Two particular examples are:
* Spinnaker traffic management, as it requires doing operations on the newest/oldest/etc. server group right after a deploy
* Dynamic target selection, which also relies on the same logic

I unfortunately don't have a great answer right now other than to not use `liveManifestCalls`; it was added initially as a quick fix to some pretty bad performance issues (which are much better now) but without fully considering how it would break workflows like this.  There are plans in the near future to greatly improve this situation...essentially eliminate the `liveManifestCalls` but automatically make live calls where possible, and wait for the cache when necessary.  But in the meantime I don't have an answer other than to disable `liveManifestCalls` for the account.

==

**Comment by ezimanyi** [comment] 2020-03-21 01:27
Closing in favor of #5607, which will fix the underlying issue; happy to help out with workarounds/etc. on this issue (though I don't think I'll have a lot beyond disabling `liveManifestCalls` for the moment unfortunately).

**Closed by ezimanyi** 2020-03-21 01:27 UTC
Labels: sig/kubernetes

**Comment by jacogreyling** [comment] 2020-03-22 04:48
@ezimanyi  Thank you go the detailed response. So then one last question. What is the implications of disabling liveManifestCalls? Could something else break? I have custom jobs which as far as I can tell require this setting. If I disable it, it can’t ‘find’ my job after it has started and therefor the stage fails. I also confirmed this through a separate GitHub issue.

**Comment by ezimanyi** [comment] 2020-03-23 14:41
@jacogreyling : Nothing else *should* break if you disable `liveManifestCalls`; all features should be compatible with having the flag disabled.  If there is a feature that only works with the flag enabled, then it's a bug in that feature that should be addressed there.

Do you have more details on what's happening with your custom job and/or a link to the Github issue?  There might be something we need to fix in custom jobs, but I'd need to understand a bit better exactly what the issue is.  Thanks!
