### ISSUE TITLE
(Openstack) Destroy server group hangs on "Waiting for not up instances"

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1158] opened 2016-09-20 21:57 UTC
I am unable to destroy a server group via the UI. The task hangs on "Waiting for not up instances".
The openstack UI does not indicate that the instances are being destroyed.
If I suspend the stack via the openstack UI, then the task continues to completion.

From orca log:

2016-09-20 17:37:46.316  INFO 29121 --- [TaskExecutor-21] c.n.s.o.b.StageStatusPropagationListener : Task SUCCEEDED but not all other tasks are complete (stageId: b0f5efcb-e2ab-478a-a528-3b71abeebe23, nonBookEndTaskStatus: NOT_STARTED) ... tasks: [{"id":"2","name":"disableServerGroup","startTime":1474407463990,"endTime":1474407464141,"status":"SUCCEEDED"}, {"id":"3","name":"monitorServerGroup","startTime":1474407464168,"endTime":1474407466314,"statu
s":"SUCCEEDED"}, {"id":"4","name":"waitForNotUpInstances","startTime":null,"endTime":null,"status":"NOT_STARTED"}, {"id":"5","name":"forceCacheRefresh","startTime":null,"endTime":null,"status":"NOT_STARTED"}, {"id":"6","name":"destroyServerGroup","startTime":null,"endTime":null,"status":"NOT_STARTED"}
, {"id":"7","name":"monitorServerGroup","startTime":null,"endTime":null,"status":"NOT_STARTED"}, {"id":"8","name":"waitForDestroyedServerGroup","startTime":null,"endTime":null,"status":"NOT_STARTED"}]

then several occurrences of

2016-09-20 17:37:46.389  INFO 29121 --- [TaskExecutor-21] c.n.s.orca.clouddriver.OortService       : ---> HTTP GET http://10.209.9.155:7002/applications/jeffwpune1/clusters/my-openstack-account/jeffwpune1-0920-1430/openstack
2016-09-20 17:37:46.396  INFO 29121 --- [TaskExecutor-21] c.n.s.orca.clouddriver.OortService       : <--- HTTP 200 http://10.209.9.155:7002/applications/jeffwpune1/clusters/my-openstack-account/jeffwpune1-0920-1430/openstack (6ms)

**Comment by jcwest** [comment] 2016-09-20 22:35
The same issue seems to exist for "destroy" action on server groups.

**Comment by derekolk** [comment] 2016-09-26 18:32
Same root cause as #1153, so closing.

**Closed** 2016-09-26 18:32 UTC
Labels: duplicate, OpenStack
