### ISSUE TITLE
Error fetching new jobs from Travis and Travis trigger stop working after upgrading to >= 1.16

### ISSUE THREAD

**Issue by CB-GuangyaoXie** [spinnaker/spinnaker#5459] opened 2020-02-18 18:11 UTC
### Issue Summary:
Travis pipeline trigger stopped working for us after upgrading to 1.16.

### Cloud Provider(s):
N/A

### Environment:
Trigger pipeline run after Travis(travis-ci.com) builds finish.

### Feature Area:
Travis service of Igor

### Description:
Travis pipeline triggers stopped working for us after upgrading to >= 1.16. 
Tried 1.17 and 1.18, both have the same issue. We used to put Travis configs in igor-local.yaml but the issue persists after we re-apply the config with halyard.
Igor logs have this error all the time:
```
2020-02-18 17:57:40.957  WARN 1 --- [ix-travis-ci-10] c.n.s.igor.travis.service.TravisService  : An error occurred while fetching new jobs from Travis.

retrofit.RetrofitError: 500 Internal Server Error
	at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
	at com.sun.proxy.$Proxy160.jobs(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.igor.travis.service.TravisService.lambda$null$6(TravisService.java:317) ~[igor-web.jar:na]
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[na:na]
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:108) ~[na:na]
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.netflix.spinnaker.igor.travis.service.TravisService.lambda$getJobs$8(TravisService.java:327) ~[igor-web.jar:na]
	at com.netflix.spinnaker.hystrix.SimpleJava8HystrixCommand.run(SimpleJava8HystrixCommand.java:52) ~[kork-hystrix-7.5.1.jar:7.5.1]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302) ~[hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298) ~[hystrix-core-1.5.18.jar:1.5.18]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) ~[rxjava-1.3.8.jar:1.3.8]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[hystrix-core-1.5.18.jar:1.5.18]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

### Steps to Reproduce:
Downgrade to 1.15 the Travis trigger would fix the issue. The issue resumes after changing to >= 1.16.

**Comment by gal-yardeni** [comment] 2020-02-26 18:40
Hi @jervi , we noticed that you had worked around this area in your previous pr (https://github.com/spinnaker/igor/pull/467). 
Can you please take a look at this? Thanks!

**Comment by jervi** [comment] 2020-02-26 18:56
I’ll have a look 👍

**Comment by jervi** [comment] 2020-02-27 09:43
The Travis integration changed between 1.15 and 1.16, so before 1.16 we used another way to fetch jobs from Travis. From 1.16 and onwards, we've used the `/jobs` endpoint. Something has happened to the Travis API because this endpoint only returns something like this now:
```
Sorry, we experienced an error.

request_id:8be797ab-6992-4152-b89f-d72629a1d9ea
```
no matter what arguments I send it. I'm not sure when it happened at the Travis side, but I hadn't noticed because we use Travis Enterprise, so I only against travis-ci.org/com when doing changes to the integration. I'll contact Travis support and ask them.

**Comment by jervi** [comment] 2020-02-27 09:51
Haha, I suspect this is an easy fix. In your config, are you using travis-ci.**org**? Just change `org` to `com` and it should work. The org environment is deprecated.

**Comment by CB-GuangyaoXie** [comment] 2020-02-27 17:56
@jervi Hi, we are always on travis-ci.com as Github Apps. Here's our igor Travis config:
```
travis:
  enabled: true
  masters:
  - name: ci
    permissions: {}
    address: https://api.travis-ci.com
    baseUrl: https://travis-ci.com
    githubToken: xxxxxxxxxxxxxxxxxxxxxxxx
```
Will caches on Spinnaker's Redis affect this? We've been using the caches across many versions.

**Comment by jervi** [comment] 2020-02-27 18:42
The caches shouldn't really affect this. Can you try to run the following command?
```
curl --location --request GET 'https://api.travis-ci.com/jobs?state=passed,started,errored,failed,canceled&include=job.build,build.log_complete&limit=100&offset=0' \
--header 'Travis-API-Version: 3' \
--header 'Authorization: token xxxxxxxxxxxxxxxxxxxx'
```
This is the exact same call that Igor will perform, and where it crashes according yo your stacktrace.

Note that the token in question is a Travis token, not a Github token. If you don't have one, you can exchange a Github token for a Travis token like this:

```
curl --location --request POST 'https://api.travis-ci.com/auth/github?github_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

**Comment by CB-GuangyaoXie** [comment] 2020-02-27 21:58
@jervi I got 500 when calling this endpoint:
```
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Server: nginx
Date: Thu, 27 Feb 2020 21:44:32 GMT
Content-Type: text/plain
Content-Length: 81
X-Request-Id: d221ebe2-bc54-4bd3-be5a-bc7f630006ba
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified, X-Request-ID
Via: 1.1 vegur

Sorry, we experienced an error.

request_id:d221ebe2-bc54-4bd3-be5a-bc7f630006ba
```
Somehow if I remove `state` parameter from the request, it works:
```
https://api.travis-ci.com/jobs?include=job.build,build.log_complete&limit=5&offset=0
...
```
Have you experienced this before? Maybe I should contact Travis support for this...

**Comment by jervi** [comment] 2020-02-27 22:34
Nice, should be easy to fix then. I guess we can either remove the `state` param or find some permutation that works. I don’t have the context of this in my head at the moment, so I’ll check tomorrow (I’m in Europe, so it’s late here).
Does it work for you with any other permutation of the state params, or with just a single state?

**Comment by CB-GuangyaoXie** [comment] 2020-02-27 23:16
Thanks!
I tried a couple of times. None of the permutation of the state params work. 
I also submitted a ticket to Travis asking about the error.

**Comment by CB-GuangyaoXie** [comment] 2020-02-28 21:22
@jervi Hi, I got this confirmation back from Travis support:
_"In summary, the issue is that there are a bunch of complex database queries, which crash the entire system when left to run beyond a specific time frame thus making the entire system unusable for everyone. We have explored options to optimize this, however, there are so many interconnected parts that it will require significant engineering work to improve this as it is."_
Looks like we should just remove the state param to work around this?

**Comment by jb31890** [comment] 2020-03-09 17:48
my org is also experiencing this issue and I was wondering if anyone has a workaround that doesn't involve downgrading versions?

**Comment by codersofthedark** [comment] 2020-03-14 21:53
@jervi @gal-yardeni Any progress on this? We are also facing the same 5xx @CB-GuangyaoXie faced

**Comment by jervi** [comment] 2020-03-15 10:11
We can rewrite Igor to use the old way of fetching jobs, but it is extremely much more resource intensive (e.g. fetching 50 jobs will cause 51 calls to Travis, vs 1 call in the new integration (this is without fetching logs). I’d say this is something Travis should fix ASAP, as there is something wrong with their public API. I’ll nudge my contact in Travis again.

**Comment by jervi** [comment] 2020-03-15 10:19
Also, just removing the `state` param is probably not enough. In my testing, any call to `/jobs` (even without any parameters at all) will fail with the same error.

**Comment by jervi** [comment] 2020-03-16 09:16
I got the following response from Travis support:

> We are working on this issue. We will let you know asap. Thanks.

Hopefully they'll have this fixed on their end soon.

**Comment by codersofthedark** [comment] 2020-03-19 19:20
Thanks @jervi I am going to downgrade our setup to 1.15 till this is fixed. Would be great if someone can update it here, once it starts working again.

**Comment by gal-yardeni** [comment] 2020-04-21 20:42
@jervi is there any update on this issue? thanks!

**Comment by jervi** [comment] 2020-04-21 21:04
I haven’t seen any errors in ours logs lately. We currently have integrations against both travis.com and an internal enterprise Travis, so maybe they have fixed it? I have not seen any communication from Travis. @CB-GuangyaoXie what about you?

**Comment by jervi** [comment] 2020-04-22 07:42
I tested against the public Travis API just now, and my query that previously failed was now OK. What is your experience? @codersofthedark @jb31890

**Comment by jervi** [comment] 2020-04-22 08:35
I asked our support guy from Travis in Slack, and I just got confirmation they have fixed it at their end, so I'm gonna close this issue. Please re-open if you still have issues!

**Closed by jervi** 2020-04-22 08:35 UTC
Labels: sig/ci

**Comment by bmurphey** [comment] 2020-04-22 20:02
Confirmed this is fixed for us as well.  @jb31890

**Comment by CB-GuangyaoXie** [comment] 2020-04-22 20:55
Hi we haven't seen the issue recently. Thanks for your help!

**Comment by bmurphey** [comment] 2020-04-27 20:20
This issue has actually continued happening periodically since my last comment, and happened quite a bit on the 25th.

**Comment by CB-GuangyaoXie** [comment] 2020-04-28 01:01
Another issue is on-going today related to Travis API or Igor. I wonder if you guys are also seeing it: 
We can't select builds from pipeline trigger as it gives: "Error loading builds!"
The 404 logs from Gate: 
```
HTTP 404 http://spin-igor.spinnaker-prod:8088/builds/all/travis-ci/myOrg/repo (88ms)
```

**Comment by jervi** [comment] 2020-04-28 07:46
@CB-GuangyaoXie Is this in the build dropdown when you do a manual execution of a pipeline? In that case, maybe it is related to https://github.com/spinnaker/igor/pull/670?

**Comment by CB-GuangyaoXie** [comment] 2020-04-29 17:20
@jervi Yes looks like it. Thank you. And I'll try out once the fix is released.

**Comment by CB-GuangyaoXie** [comment] 2020-06-09 19:29
@jervi Hi, we found our "Error loading builds" is actually caused by two problems:
First is Travis API had been returning empty results(see below) to our Github bot account that used to work fine. So I used the bot account to log in travis-ci.com and the Travis API responses are now working again.
Two is the API timeout you fixed in https://github.com/spinnaker/igor/pull/670

```
{
  "@type": "repositories",
  "@href": "/repos",
  "@representation": "standard",
  "@pagination": {
    "limit": 100,
    "offset": 0,
    "count": 0,
    "is_first": true,
    "is_last": true,
    "next": null,
    "prev": null,
    "first": {
      "@href": "/repos",
      "offset": 0,
      "limit": 100
    },
    "last": {
      "@href": "/repos?limit=100&offset=-100",
      "offset": -100,
      "limit": 100
    }
  },
  "repositories": [

  ]
}
```
