### ISSUE TITLE
Jenkins job get artifact related bug introduced in Spinnaker 1.32.4

### ISSUE THREAD

**Issue by dprangnell** [spinnaker/spinnaker#6948] opened 2024-04-25 16:53 UTC
### Issue Summary:
Successfully executed Jenkins jobs can be erroneously marked as `Terminal` in Spinnaker.

### Environment:
Problem not seen in 1.32.3 or previous versions.  Problem confirmed in 1.32.4, 1.33.2 and 1.34.2.

### Feature Area:
Calling jenkins jobs.

### Description:
If you call a jenkins job that produces a 0 byte artifact, Spinnaker fails to retrieve the artifact and erroneously marks the job as failed.
```
Exception ( Get Build Artifacts )
404 Not Found
```

### Steps to Reproduce:
1. Create a jenkins job that creates an empty artifact. You can do this by adding the following to your Jenkinsfile:
```
sh "touch build.properties"
archiveArtifacts 'build.properties
```
2. Run the jenkinsjob to confirm it succeeds and produces a 0 bit artifact called build.properties:
![Screenshot 2024-04-24 at 10 06 53 PM](https://github.com/spinnaker/spinnaker/assets/1494862/53e8e974-ded1-454a-adfe-75132b833812)

4. Call the job from a spinnaker pipeline.
5. The Jenkins job should succeed, but the stage will fail in spinnaker trying to retrieve this empty artifact:

![Screenshot 2024-04-24 at 9 45 16 PM](https://github.com/spinnaker/spinnaker/assets/1494862/b9638c2c-dfd2-4acd-b6fa-1beeaedda290)

**Comment by christosarvanitis** [comment] 2024-05-13 08:57
This issue has the same root cause as the issue https://github.com/spinnaker/spinnaker/issues/6949

The fix has been merged and backported https://github.com/spinnaker/orca/pull/4722

**Closed** 2024-05-13 14:40 UTC
