### ISSUE TITLE
Rerun of pipeline fails: Passing parameters in artifact url fetched from Artifactory

### ISSUE THREAD

**Issue by ganguay** [spinnaker/spinnaker#5845] opened 2020-06-16 06:00 UTC
### Description: 
We are trying to pass aparameter using the artifact url " http://<artifactory ip>:8082/artifactory/${parameters['manifest']}/miniosecret.yml"

When the pipeline is run initially it works fine,it also works fine when we manually execute the pipeline or trigger the pipeline 2nd time, but when we use the rerun button in spinnaker UI the pipeline fails with error
" Failed on startup: Illegal repetition near index 38 http://<artifactory IP>:8082/artifactory/${parameters['manifest']}/miniosecret.yml ".

### Steps to Reproduce: we can take any manifest file as artifact from Artifactory and try to pass any parameter in the artifact url and then rerun the pipeline.
To test what we did was create a folder in artifactory containing a manifest file miniosecret.yml, then configuring the pipeline to fetch this file and in the artifact url we are passing the folder as parameter
http://<artifactory ip>:8082/artifactory/${parameters['manifest']}/miniosecret.yml

any folder or manifest filecan be taken from artifactory to reproduce this error

**Comment by maggieneterval** [comment] 2020-07-10 18:08
Hi @ganguay!

I am unable to reproduce this problem. I've configured a pipeline with an expected artifact whose reference contains a parameter value referenced with SpEL, and am able to re-run it successfully. It has the following expected artifact and parameter configuration:

```
{
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "artifactAccount": "my-gcs-account",
        "id": "dc1082e6-db87-4f3a-9c08-ab342b1c79c0",
        "name": "gs://spinnaker-kubernetes-demo/manifests/${parameters['name']}.yaml",
        "reference": "gs://spinnaker-kubernetes-demo/manifests/${parameters['name']}.yaml",
        "type": "gcs/object"
      },
      "displayName": "serious-bird-47",
      "id": "c15ad4bc-dd72-423a-9b16-50e858c9c9fc",
      "matchArtifact": {
        "artifactAccount": "my-gcs-account",
        "id": "96b0c794-f9aa-4995-8522-908d28d41d0b",
        "name": "gs://spinnaker-kubernetes-demo/manifests/replicaset.yaml",
        "type": "gcs/object"
      },
      "useDefaultArtifact": true,
      "usePriorArtifact": false
    }
  ],
  "parameterConfig": [
    {
      "default": "replicaset",
      "description": "",
      "hasOptions": false,
      "label": "",
      "name": "name",
      "options": [
        {
          "value": ""
        }
      ],
      "pinned": false,
      "required": false
    }
  ]
```

The execution details of the re-run have the following `trigger` section as expected, with the artifact section fully resolved:

```
trigger: {
  type: "manual",
  user: "[anonymous]",
  parameters: {
    name: "replicaset"
  },
  artifacts: [
  {
    customKind: false,
    reference: "gs://spinnaker-kubernetes-demo/manifests/replicaset.yaml",
    metadata: {
      id: "dc1082e6-db87-4f3a-9c08-ab342b1c79c0"
    },
    name: "gs://spinnaker-kubernetes-demo/manifests/replicaset.yaml",
    artifactAccount: "my-gcs-account",
    type: "gcs/object"
  }
],
```

Does anything in either the configuration or execution JSON appear different from what you are seeing on your end? Are you able to suggest any changes to my configuration JSON in order to better replicate your setup and reproduce this issue?

I tested this on the most recent [release](https://spinnaker.io/community/releases/versions/#latest-stable), so you might also want to try upgrading.

Thanks!

**Comment by ganguay** [comment] 2020-07-13 05:16
@maggieneterval thank you for getting back... am checking the configuration.. will update more details regarding the same

**Comment by ganguay** [comment] 2020-07-14 06:29
Hi @maggieneterval have added the pipeline json along with the screenshot of the error,let meknow if this helps.. 
![Screenshot from 2020-07-14 11-49-37](https://user-images.githubusercontent.com/48548084/87391719-e12a5380-c5c8-11ea-887e-8185f6d37ff7.png)
[pipelinejson.docx](https://github.com/spinnaker/spinnaker/files/4916962/pipelinejson.docx)

**Comment by maggieneterval** [comment] 2020-07-14 18:52
Hi @ganguay, thanks for sharing your pipeline JSON!

I think the issue here can be resolved if you remove the pipeline expression from your `matchArtifact`; although regular expressions are supported in `matchArtifact` fields, I do not think that SpEL expressions are (Please see [this comment](https://github.com/spinnaker/spinnaker/issues/3926#issuecomment-460392167) on a similar issue for more context.). If you are always falling back to your parameterized `defaultArtifact` URL anyway, is there a reason you need to parameterize the `matchArtifact` as well or would a regular expression work? There are some documented examples for using regular expressions in expected artifacts [here](https://spinnaker.io/reference/artifacts/in-pipelines/#expected-artifacts) that might be helpful.

Going to close this issue for now but please feel free to reopen if removing the SpEL expression from the `matchArtifact`'s URL does not resolve this issue. Thanks!

**Closed by maggieneterval** 2020-07-14 18:52 UTC
Labels: sig/ui-ux
