### ISSUE TITLE
Warning while running a shell script which is inside ConfigMap

### ISSUE THREAD

**Issue by rajusharma** [spinnaker/spinnaker#4965] opened 2019-09-27 08:12 UTC
### Issue Summary:
While running a shell script which is inside configmap causes warning in spinnaker pipeline
```
Warning
Failed to evaluate [check-sidecar.sh] EL1041E: After parsing a valid expression, there is still more data in the expression: 'colon(:)'
```

### Cloud Provider(s):
GKE 

### Environment:
I am using spinnaker to deploy manifests from github to kubernetes(GKE)

### Description:
I want to run a script before starting kubernetes pod, to do this i have written the script in configmap and attached it to deployment using volume. The script and pods are running successfully but there is a warning message after pipelines ends.

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: script
  namespace: default
data:
  check-sidecar.sh: while true; do STATUS=$(wget --spider -S --quiet 'http://localhost:15020/healthz/ready' 2>&1 | grep 'HTTP/' | awk '{print $2}'); if [ ${STATUS:-0} -eq 200 ]; then exec /bin/api; break; else sleep 1; fi; done;
```
Inside deployment i have attached this configmap using volumes and running like below
```
        command:
        - sh
        args:
        - "/tmp/check-sidecar.sh"
        - /bin/api
```

### Steps to Reproduce:
- Create above config map
- Attach it to kubernetes deployment using volume
- Call the script using command like
```
        command:
        - sh
        args:
        - "/tmp/check-sidecar.sh"
        - /bin/api
```
- Deploy this configmap and deployment using spinnaker pipeline

### Additional Details:
The pipelines succeeds but there is always this warning message

**Comment by maggieneterval** [comment] 2019-09-27 20:40
Hi @rajusharma, thanks for taking the time to open this issue!

I think you are running into that warning because Spinnaker attempts to parse any `${}`-wrapped expressions as SpEL. Have you tried wrapping any `${}`-wrapped expressions in the bash script _not_ intended to be evaluated by Spinnaker in quotes? For example, you could try writing `${ENV_VAR}` as `${"${ENV_VAR}"}`. Going to close this for now, but please let me know if that workaround doesn't help!

**Closed by maggieneterval** 2019-09-27 20:40 UTC
Labels: provider/kubernetes-v2, sig/kubernetes

**Comment by rajusharma** [comment] 2019-09-30 06:14
Thank you @maggieneterval for suggesting the workaround.
I replaced `${ENV_VAR}` to `${"${ENV_VAR}"}` but still the result is same.
My new configmap is like below
```
data:
  check-sidecar.sh: |-
    while true
    do
      STATUS=$(wget --spider -S --quiet 'http://localhost:15020/healthz/ready' 2>&1 | grep 'HTTP/' | awk '{print $2}')
      if [[ ${"${STATUS}"} -eq 200 ]]; then
        exec ${"${1}"}
        break
      else
        sleep 1
      fi
    done
```

Result:
The pipelines succeeds with following warning message
```
Warning
Failed to evaluate [check-sidecar.sh] : while true do STATUS=$(wget --spider -S --quiet 'http://localhost:15020/healthz/ready' 2>&1 | grep 'HTTP/' | awk '{print $2}') if [[ STATUS -eq 200 ]]; then exec 1 break else sleep 1 fi done not found
```

Would you please kindly confirm, if i have missed anything 🙏

**Comment by maggieneterval** [comment] 2019-09-30 13:38
Unfortunately I think the warning is expected since Spinnaker tries to evaluate any `${}`-wrapped expressions in the pipeline JSON. I tried deploying your ConfigMap with Spinnaker and am getting the same warning. However, the ConfigMap is deploying successfully and correctly. I think there is a longer-term effort to rethink expression evaluation in Spinnaker since it is the cause of a lot of confusing behavior such as the behavior you've experienced. You can track it [here](https://github.com/spinnaker/spinnaker/issues/3500). Thank you!

**Comment by zackb** [comment] 2020-04-15 19:24
I am having the same problem with nginx ingress yaml definitions. Particularly the `nginx.ingress.kubernetes.io/server-snippet` label which contains a bunch of nginx config. I see the linked RFC is closed. Is there a new way to track this kind of thing?
