### ISSUE TITLE
Confusing Orca message for Bake Manifest stage

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5624] opened 2020-03-27 13:47 UTC
### Issue Summary:
Confusing Orca message for the Bake Manifest stage when no artifact is specified in the "Produces artifact" section

> 
_Exactly one expected artifact must be supplied. Please ensure that your Bake stage config's expectedArtifacts list contains exactly one artifact._

### Cloud Provider(s):
kubernetes

### Environment:
all spinnakers up to the latest (current 1.19.2)

### Feature Area:
orca

### Description:
Expected Artifacts are provided alright. It's the Produced Artifact that is missing. But Spinnaker reports nonetheless:
> 
_Exactly one expected artifact must be supplied. Please ensure that your Bake stage config's expectedArtifacts list contains exactly one artifact._

### Steps to Reproduce:
Use the attached pipeline with one expected artifact specified and missing output artifact
`
{
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "artifactAccount": "embedded-artifact",
        "id": "cb258977-4685-4aac-9eb7-1f279b12f446",
        "name": "Selenium server manifest",
        "reference": "YXBpVmVyc2lvbjogbmV0d29ya2luZy5rOHMuaW8vdjFiZXRhMQpraW5kOiBJbmdyZXNzCm1ldGFkYXRhOgogIG5hbWU6IHNlbGVuaXVtLWNocm9tZQpzcGVjOgogIHJ1bGVzOgogICAgLSBob3N0OiBzZWxlbml1bS1jaHJvbWUubG9jYWwKICAgICAgaHR0cDoKICAgICAgICBwYXRoczoKICAgICAgICAgIC0gYmFja2VuZDoKICAgICAgICAgICAgICBzZXJ2aWNlTmFtZTogc2VsZW5pdW0tY2hyb21lLXN2YwogICAgICAgICAgICAgIHNlcnZpY2VQb3J0OiA0NDQ0Ci0tLQphcGlWZXJzaW9uOiB2MQpraW5kOiBTZXJ2aWNlCm1ldGFkYXRhOgogIG5hbWU6IHNlbGVuaXVtLWNocm9tZS1zdmMKc3BlYzoKICBwb3J0czoKICAgIC0gbmFtZTogaHR0cAogICAgICBwb3J0OiA0NDQ0CiAgICAgIHByb3RvY29sOiBUQ1AKICBzZWxlY3RvcjoKICAgIGFwcDogc2VsZW5pdW0tY2hyb21lCi0tLQphcGlWZXJzaW9uOiBhcHBzL3YxCmtpbmQ6IERlcGxveW1lbnQKbWV0YWRhdGE6CiAgbGFiZWxzOgogICAgYXBwOiBzZWxlbml1bS1jaHJvbWUKICBuYW1lOiBzZWxlbml1bS1jaHJvbWUtZGVwbG95bWVudApzcGVjOgogIHJlcGxpY2FzOiAxCiAgc2VsZWN0b3I6CiAgICBtYXRjaExhYmVsczoKICAgICAgYXBwOiBzZWxlbml1bS1jaHJvbWUKICB0ZW1wbGF0ZToKICAgIG1ldGFkYXRhOgogICAgICBsYWJlbHM6CiAgICAgICAgYXBwOiBzZWxlbml1bS1jaHJvbWUKICAgIHNwZWM6CiAgICAgIGNvbnRhaW5lcnM6CiAgICAgICAgLSBpbWFnZTogJ3NlbGVuaXVtL3N0YW5kYWxvbmUtY2hyb21lLWRlYnVnOjMuMTQxLjU5JwogICAgICAgICAgbmFtZTogbmdpbngKICAgICAgICAgIHBvcnRzOgogICAgICAgICAgICAtIGNvbnRhaW5lclBvcnQ6IDQ0NDQKICAgICAgICAgIHZvbHVtZU1vdW50czoKICAgICAgICAgICAgLSBtb3VudFBhdGg6IC9kZXYvc2htCiAgICAgICAgICAgICAgbmFtZTogZHNobQogICAgICB2b2x1bWVzOgogICAgICAgIC0gZW1wdHlEaXI6CiAgICAgICAgICAgIG1lZGl1bTogTWVtb3J5CiAgICAgICAgICBuYW1lOiBkc2htCg==",
        "type": "embedded/base64"
      },
      "displayName": "Selenium server manifest",
      "id": "a2a462d2-7a7a-43be-8d04-6060a5cb123b",
      "matchArtifact": {
        "artifactAccount": "embedded-artifact",
        "id": "33041425-001f-4cb9-8bf9-542b09190b5c",
        "name": "Selenium server manifest",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": true,
      "usePriorArtifact": false
    }
  ],
  "keepWaitingPipelines": false,
  "lastModifiedBy": "alexandert",
  "limitConcurrent": true,
  "parameterConfig": [],
  "spelEvaluator": "v4",
  "stages": [
    {
      "evaluateOverrideExpressions": true,
      "expectedArtifacts": [],
      "inputArtifacts": [
        {
          "account": "embedded-artifact",
          "id": "a2a462d2-7a7a-43be-8d04-6060a5cb123b"
        },
        {
          "account": "embedded-artifact",
          "id": "a2a462d2-7a7a-43be-8d04-6060a5cb123b"
        }
      ],
      "name": "Bake Chrome Selenium Server Manifest",
      "namespace": "",
      "outputName": "",
      "overrides": {},
      "refId": "4",
      "requisiteStageRefIds": [],
      "templateRenderer": "HELM3",
      "type": "bakeManifest"
    }
  ],
  "triggers": [],
  "updateTs": "1585316226000"
}
`

**Comment by maggieneterval** [comment] 2020-04-02 14:57
Hey @atyutyunnik, thanks for taking the time to open this issue! This is indeed confusing, and in fact it is a regression that the Bake (Manifest) stage does not automatically configure a default produced base64 artifact, since the stage is invalid without one. We've replaced the defaulting behavior, and additionally added a validation warning in Deck so it's clearer at configuration time that a single "produced artifact" (which lives under the stage's `expectedArtifacts` list) is required. This will be released with Spinnaker 1.20.

Thanks again!

**Closed by maggieneterval** 2020-04-02 14:57 UTC
Labels: sig/kubernetes
