### ISSUE TITLE
Clouddriver not refreshing Spring Cloud Config properties  

### ISSUE THREAD

**Issue by kirangodishala** [spinnaker/spinnaker#6128] opened 2020-10-22 19:23 UTC
### Issue Summary:
Spring Cloud Config properties are not getting refreshed in Spinnaker 1.23.0

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.23.0. 

### Feature Area:
Spring Cloud Config refresh

### Description:
With the latest clouddriver(release 1.23.0), the classes related to refreshing cloud config are moved to a new module clouddriver-configserver.  For some reason the CloudConfigRefreshConfig(a configuration class) seems to be undetected and the scheduler bean defined inside is not getting created.

### Steps to Reproduce:
Add few Kubernetes accounts in clouddriver-local.yml and check in the file in git. In spinnakerconfig.yml, add the configuration similar to the one given in the link - [https://spinnaker.io/setup/configuration/#using-a-git-backend](https://spinnaker.io/setup/configuration/#using-a-git-backend). Restart the clouddriver. The accounts get loaded at startup but they never get refreshed.

**Comment by tompa911** [comment] 2020-10-27 16:22
Bug affects vault backend as well.

**Comment by clanesf** [comment] 2020-10-29 16:40
Hey guys, so I recently had a commit merged that impacts the way that this code works. I don't *think* it's related to your Bean loading problems, but I figured I would at least mention it.

https://github.com/spinnaker/clouddriver/pull/4699

Previously the CloudConfigRefreshConfig had 3 separate initializers. The default was to schedule the refresher to run every 60 minutes, but that was supposed to be superseded by the DefaultAgentIntervalProvider.class bean which is normally loaded for Redis.

When I tested the code, I couldn't get the Redis based path to execute no matter what my settings were. I confirmed with the original author Scott that he never really tested that the DefaultAgentIntervalProvider class was loaded, and after talking to Rob Z who has more Spring experience than I do, he was in favor of taking out the DefaultAgentIntervalProvider and making it so you either expressly configure how of to run the refresh by adding this to your clouddriver-local.yml
```
cloud:
  config:
    enabled: true
    refreshInterval: 180   # refresh cloud config every 3 minutes. 
```

From the testing that I did, even if I didn't include this bit then it would go ahead and load the default bean, the defaultIntervalConfigRefreshScheduler path, as long as the RemoteConfigSourceConfigured.class is present. You can see the code here 

https://github.com/clanesf/clouddriver/blob/3eb38317aeaa6a855b571941ccf1a3a8ef206116/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CloudConfigRefreshConfig.java#L39-L57

I tested this thoroughly, but I am using a native backend for cloud config server, not vault or git, so it's possible there's something I missed. 

To track this down, it might be helpful to put the following code into clouddriver-local.yml 
```
management:
  endpoints:
    web:
      exposure:
        include: "*"
```
and then do a get request to clouddriver to any of the following endpoints and you should get an explanation of why the CloudConfigRefreshConfig bean isn't being triggered.
```
curl http://spin-clouddriver.spinnaker:7002/beans
curl http://spin-clouddriver.spinnaker:7002/env
curl http://spin-clouddriver.spinnaker:7002/configprops
```

Please let me know what you find out. My changes were introduced in either 1.21 or 1.22, so there might be some other problem, but I wanted to mention it because you called out the CloudConfigRefreshConfig class and I was the last person to make changes to that file. 

Cheers!

**Comment by tompa911** [comment] 2020-10-29 21:32
@clanesf Did you really mean "every 60 minutes"? Maybe seconds?

**Comment by kirangodishala** [comment] 2020-11-02 10:09
@clanesf I have verified again with both 1.22.2 and 1.23.0. Here are some observations: 1) CloudConfigRefreshConfig is not created in 1.23.0 but present in 1.22.2. (this is the stated problem)

**Comment by kirangodishala** [comment] 2020-11-02 10:23
@clanesf, I have attached the beans, env and configProps for 1.23.0 and 1.22.2.
[beans_env_configProps.zip](https://github.com/spinnaker/spinnaker/files/5474232/beans_env_configProps.zip)

**Closed** 2020-11-11 14:58 UTC
Labels: sig/kubernetes
