### ISSUE TITLE
Region missing when creating a server group in "Deploy" stage with GCE

### ISSUE THREAD

**Issue by MansoorMajeed** [spinnaker/spinnaker#5864] opened 2020-06-24 08:37 UTC
### Issue Summary:
While trying to create a server group in the deploy stage of a GCE pipeline, the region drop down is empty.
This is the same case for new and existing pipelines. Because the region is empty, even the existing pipelines stopped working

### Cloud Provider(s):
Google Compute Engine

### Environment:
Kubernetes (GKE)

### Feature Area:
Pipeline stage creation

### Description:
While trying to create a server group in the deploy stage of a GCE pipeline, the region drop down is empty. It should actually show the supported regions to choose from
This is the same case for new and existing pipelines. Because the region is empty, even the existing pipelines stopped working

### Steps to Reproduce:

1. Create a new pipeline with GCE account
2. Add a `Deploy` stage
3. Add a server group, it will have the region field empty 

### Additional Details:
![spinnaker-issue](https://user-images.githubusercontent.com/12676196/85523014-0b20d380-b624-11ea-9ddf-24a8b884a9e6.PNG)

---

**Comment by maggieneterval** [comment] 2020-06-24 13:39
@MansoorMajeed thanks for reporting. Are you seeing any errors in your browser console? What version of Spinnaker are you using? Was this working for you on a previous version?

**Comment by MansoorMajeed** [comment] 2020-06-24 13:52
@maggieneterval I'm using Spinnaker version `1.18.12`. It was working few versions before. However, I should note that I have seen this same behavior many months ago on an older version of Spinnaker when I was trying it out, but I did not pursue it because that was not in production yet. 

There is nothing on the console at all.

**Comment by maggieneterval** [comment] 2020-06-25 12:51
@MansoorMajeed are you able to confirm that there is a populated list of `regions` on your GCE account as received by Deck from Gate? Can check out the response to `your_gate_endpoint/credentials?expand=true` for the account(s) in question.

**Comment by MansoorMajeed** [comment] 2020-06-25 14:57
Okay, so I do see something odd. I can see the `regionToZonesMap` but `regions` is an empty list.

```
  {
    "name": "xxxxxx",
    "type": "gce",
    "providerVersion": "v1",
    "requiredGroupMembership": [
      
    ],
    "skin": "v1",
    "permissions": {
      
    },
    "accountType": "xxxxx",
    "environment": "xxxx",
    "challengeDestructiveActions": false,
    "primaryAccount": false,
    "cloudProvider": "gce",
    "regionToZonesMap": {
      "asia-east1": [
----snip----
      "us-west4": [
        "us-west4-c",
        "us-west4-a",
        "us-west4-b"
      ]
    },
    "regions": [
      
    ],
```

**Comment by maggieneterval** [comment] 2020-06-26 13:00
@MansoorMajeed thanks for checking! I'm not super familiar with the GCE credentials initialization code, but my understanding is the following:

- If you've specified `google.defaultRegions` in your Clouddriver config (which corresponds to `providers.google.defaultRegions` in your halconfig), this set of regions will be assigned to each account. So if you've set this to an empty list, or a list of regions that are not included in the account's `regionToZonesMap`, an individual account's regions could end up as an empty list ([source code](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy#L47)).
- If you've specified `google.accounts.$YOUR_ACCOUNT_NAME.regions`, this will override the list set at `google.defaultRegions`, including if you've set this to an empty list or a list of regions that are not included in the account's `regionToZonesMap` ([source code](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy#L35)).
- I believe the `regionToZoneMap` is constructed from a live lookup against the GCE API for your project ([source code](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy#L356)), which could fail with this [error message](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy#L365).

Since I don't think any of this logic has changed in any supported release, I am guessing this is either a configuration issue or Clouddriver having an issue communicating with your GCP project. As next steps, I would suggest the following:
- Enabling DEBUG logging in Clouddriver and checking for any error or warning messages, particularly around credential initialization.
- Posting in the #google or #general Slack channel in [Spinnaker Slack](join.spinnaker.io) to see if any other users have encountered a similar issue.
- [Attaching a debugger to Clouddriver](https://www.youtube.com/watch?v=DG5BO3PB5a0) (in a dev environment) and stepping through the GCE credentials initialization (can use the source code I linked above as a starting point).

Since we're not able to reproduce this issue, I'm going to close it for now. Of course, please feel free to comment or reopen if you discover the root cause and would like to share, or if you find a place where error messaging could be improved. Thanks so much!

**Closed by maggieneterval** 2020-06-26 13:00 UTC

**Comment by MansoorMajeed** [comment] 2020-06-29 14:30
@maggieneterval Wow! That was enough information to figure out the issue. Thanks a lot.
So, this is what happened, looking at the halyard config, 

```
----snip----
google:
      enabled: true
      accounts:
      - name: xxxxxx
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        project: xxxxxx
        jsonPath: /etc/gcp-creds/config.json
        alphaListed: false
        imageProjects: []
        consul:
          enabled: false
          agentEndpoint: localhost
          agentPort: 8500
          datacenters: []
        regions: []
----snip----
```

`regions: []` is an empty list. Cross verifying with a halyard config backup from January, I do not see the `regions` key in it at all. So, I guess it was added somewhere along the line and that caused the issue.
Adding the appropriate regions to the `regions` list fixed the issue.

Again, thanks a lot for the detailed breakdown of the issue, couldn't have figured it out with that. :)
