### ISSUE TITLE
Add support for GCE http load balancers and url maps

### ISSUE THREAD

**Issue by JorritSalverda** [spinnaker/spinnaker#711] opened 2016-02-02 13:57 UTC
We run different applications on separate paths in the same http load balancer. Being able to create the http load balancer - as opposed to the network load balancer - helps to accomplish this through Spinnaker.

**Comment by duftler** [comment] 2016-02-02 13:59
Yes, we plan to complete the support for this during the first quarter.

This issue is tracked here: https://github.com/spinnaker/spinnaker/issues/680

**Comment by duftler** [comment] 2016-02-27 19:57
Closing this as a duplicate of the referenced issue.

**Closed by duftler** 2016-02-27 19:57 UTC
Labels: google
