### ISSUE TITLE
Manifest status flashes on and off in v2 deploy execution tab

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2743] opened 2018-05-04 12:02 UTC
![image](https://user-images.githubusercontent.com/4874941/39626798-73d5c6c2-4f71-11e8-9b96-85e256e303f6.png)

The events & manifest status keep appearing & reappearing when viewing the pipeline.

**Comment by lwander** [comment] 2018-05-04 17:17
Using an intentionally bad manifest (to keep the stage running & show failed checks) the issues persists at HEAD

```yaml
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: nginx
    name: nginx-deployment
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - image: 'nginx:.9'
            name: nginx
            ports:
              - containerPort: 80
```

**Comment by sbwsg** [comment] 2018-05-07 14:13
I still can't reproduce this in Chrome 66 on Mac OS X.  What browser / operating system are you experiencing this in?

**Comment by lwander** [comment] 2018-05-07 14:16
Try it on your workstation w/ the latest chrome

**Comment by sbwsg** [comment] 2018-08-10 14:31
This issue hasn't _manifest_ed in a while so I'm closing this out for the time being. If anyone stumbles across this seeing the same problem then please reopen or create a new issue.

**Closed by sbwsg** 2018-08-10 14:31 UTC
Labels: artifacts, bug, ui
