### ISSUE TITLE
Apply Manifest stage does not store history of executed YAML

### ISSUE THREAD

**Issue by oahayder** [spinnaker/spinnaker#5534] opened 2020-03-03 22:18 UTC
### Issue Summary:
When clicking an Apply Manifest stage in a previous execution, you don't get the YAML that was applied. You get the YAML in its current state in the k8s cluster.

I would expect to see the YAML that that specific pipeline execution applied. Helps debugging and having observability into history of deployments and change.

### Cloud Provider(s):
AWS, Kubernetes 1.9

### Environment:
Running spinnaker in the same k8s cluster it deploys to. Our own k8s cluster on AWS EC2 machines.

### Feature Area:
Pipelines, UI, clouddriver

### Steps to Reproduce:
Apply Manifest in a pipeline with text, not an artifact. Edit the manifest in k8s manually. Then view the YAML in the execution view. You'll observe your manual changes in that YAML.

<img width="860" alt="Screen Shot 2020-03-03 at 2 14 16 PM" src="https://user-images.githubusercontent.com/6406141/75825056-83077d00-5d59-11ea-9c68-8b263c15029b.png">

**Comment by ezimanyi** [comment] 2020-03-04 15:14
@oahayder : Thanks for reporting this!  This looks like a duplicate of #5254 which we are aware of and agree should be fixed.

**Closed by ezimanyi** 2020-03-04 15:14 UTC
Labels: sig/kubernetes
