### ISSUE TITLE
S3: ERROR Failed to ensure the required bucket exists: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden;

### ISSUE THREAD

**Issue by imriss** [spinnaker/spinnaker#4556] opened 2019-06-20 19:40 UTC
When trying to add an S3 bucket, using the following command:
```
hal config storage s3 edit \
    --access-key-id $ACCESS_KEY_ID \
    --secret-access-key \
    --region $REGION; 
```
Faced this error:
```
Problems in default.persistentStorage:
- WARNING Your deployment will most likely fail until you configure
  and enable a persistent store.

Problems in default.persistentStorage.s3:
! ERROR Failed to ensure the required bucket "spin-46-456-345-2345"
  exists: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403
  Forbidden; Request ID: 67BD9FE5234505690673; S3 Extended Request ID:
  vMnfY+kUYtnGOiGjLee3m0STFk234g52345q14FFv7xA3oGjTFYh2ozm/ziveH3ko8coBonidqu2ETNE9TuyA=)

- Failed to edit persistent store "s3".
```

*ENV*
`hal` deployed using `Docker` :
```
docker run -p 8084:8084 -p 9000:9000 \
    --name halyard --rm \
    -v ~/.hal:/home/spinnaker/.hal \
    -v ~/.kube:/home/spinnaker/.kube \
    -e ACCESS_KEY_ID=ACCESS_KEY_ID \
    -e REGION=us-west-2 \
    -d \
    gcr.io/spinnaker-marketplace/halyard:stable
```

Thanks

**Comment by ezimanyi** [comment] 2019-06-21 14:52
Duplicate of #4554

**Closed by ezimanyi** 2019-06-21 14:52 UTC
