### ISSUE TITLE
Can't turn on SSL for gate service

### ISSUE THREAD

**Issue by usrleon** [spinnaker/spinnaker#2886] opened 2018-06-08 21:13 UTC
### Issue Summary:
SSL configured for Deck and Gate via halyard, Deck works fine, but gate still work on http

### Cloud Provider(s):
N/A

### Environment:
local ubuntu 14.04

### Steps to Reproduce:
Deploy spinnaker using halyard (1.2.0-20180509113540)
Spinnaker version 1.6.1 (also tried 1.7.6)
SSL configured as show here https://www.spinnaker.io/setup/security/authentication/ssl/
Expected:  gate service become https
Actual result:
```
root@spinnaker-test:~# openssl s_client -connect 127.0.0.1:8084
CONNECTED(00000003)
140246294525600:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---


### Additional Details:


---

```
cat /opt/spinnaker/config/gate.yml
```
## WARNING
## This file was autogenerated, and _will_ be overwritten by Halyard.
## Any edits you make here _will_ be lost.

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false

server:
  ssl:
    clientAuth: want
    enabled: true
    keyAlias: spinnaker
    keyStore: /home/username/.hal/default/staging/dependencies/1035009097-keystore2.jks
    keyStoreType: jks
    keyStorePassword: qwerty
    trustStore: /home/username/.hal/default/staging/dependencies/1035009097-keystore2.jks
    trustStoreType: jks
    trustStorePassword: qwerty
  port: '8084'
  address: 0.0.0.0
security:
  basic:
    enabled: true
  user: {}
  oauth2:
    enabled: true
    client:
      preEstablishedRedirectUri: https://spinnaker.example.com:8084/login
      useCurrentUri: true
    resource: {}
    userInfoMapping: {}
cors: {}

# halconfig

redis:
  connection: ${services.redis.baseUrl:redis://localhost:6379}

```

**Comment by sbwsg** [comment] 2018-06-11 13:06
Hi @usrleon, thanks for the issue report.  I've just run copy/pasted the commands from the SSL tutorial you linked and Gate is now responding to `openssl s_client -connect 127.0.0.1:8084` over HTTPS.  So to help track down the issue a couple of questions:

Just to confirm - did you run `hal deploy apply` after applying all of the SSL changes?
Can you add your Gate instance's log output to this issue?

**Comment by sbwsg** [comment] 2018-06-11 19:56
Thanks for the log output, it confirms that the server is launching as http and i don't see any obvious problems.  Your gate configuration matches mine almost exactly (mine doesn't have the `clientAuth: want` field and has "localhost" instead of "0.0.0.0") and my server is launching with https.

Could you provide your `hal config` with any sensitive information removed?  Many thanks!

**Comment by usrleon** [comment] 2018-06-12 19:42
Option 'clientAuth: want' is just my desperate attempt to copy options from old spinnaker deploymnt you can just ignore it. Config attached.
[hal_config.txt](https://github.com/spinnaker/spinnaker/files/2095574/hal_config.txt)

**Comment by sbwsg** [comment] 2018-06-13 17:19
Ok, thanks!

I set up a new vm with ubuntu 14.04, halyard 1.2 and then deployed a LocalDebian spinnaker 1.6.1.  I then went through the steps described in https://www.spinnaker.io/setup/security/authentication/ssl/ and `openssl s_client -connect 127.0.0.1:8084` recognized the connection was secured.

Can you check whether `/home/username/.hal/default/staging/dependencies/1035009097-keystore2.jks` exists?  It's the keystore and truststore file mentioned in your gate.yml above.

Additionally, can you confirm that the keystore password works as expected (qwerty in your pasted gate.yaml)?  You can check this by running `keytool -list -v -keystore /path/to/your/keystore` and then entering the password when prompted.

**Comment by usrleon** [comment] 2018-06-13 18:46
It exists and I actually recreated keystore after first attept (that's why it's keystore2) and I already checked storage it's ok, I can list it password works, file belongs to spinnaker:spinnaker
Contents is like that:
```
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 2 entries

Alias name: ca
Creation date: Jun 7, 2018
Entry type: trustedCertEntry
<skipped>
Alias name: spinnaker
Creation date: Jun 7, 2018
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
<skipped>

```

**Comment by usrleon** [comment] 2018-06-13 22:19
I just created new VM and carefully repeated all steps from guide, and I got same issue.

**Comment by sbwsg** [comment] 2018-06-14 12:47
OK, thanks, I'm still trying to track this down.  Can you provide the `ls -lah` output for `/opt` showing perms and users/groups for all the certificate files?  Something like this:

```bash
$ ls -lah /opt/*.{crt,key,jks}

-rw-r-----  1 sbwsg users 1.9K Jun 11 08:50 /opt/ca.crt
-rw-------  1 sbwsg users 3.3K Jun 11 08:50 /opt/ca.key
-rw-r-----  1 sbwsg users 5.1K Jun 11 08:51 /opt/keystore.jks
-rw-r-----  1 sbwsg users 1.8K Jun 11 08:51 /opt/server.crt
-rw-------  1 sbwsg users 3.3K Jun 11 08:50 /opt/server.key
```

**Comment by usrleon** [comment] 2018-06-14 17:02
maxim_lvov@spinnaker-test:~$ ls -lah /opt/*.{crt,key,jks}
-rw-r----- 1 spinnaker spinnaker 5.4K Jun  7 20:56 /opt/keystore2.jks
-rw-r----- 1 spinnaker spinnaker 5.4K Jun  6 17:20 /opt/keystore.jks
-rw-r----- 1 spinnaker spinnaker 2.0K Jun  6 17:21 /opt/server.crt
-rw-r----- 1 spinnaker spinnaker 3.3K Jun  6 17:21 /opt/server.key

On new VM:
maxim_lvov@spinnaker-test3:~$ sudo ls -lah ~/*.{crt,key,jks}
-rw-r----- 1 maxim_lvov users 2.1K Jun 13 22:07 /home/maxim_lvov/ca.crt
-rw-r----- 1 maxim_lvov users 3.3K Jun 13 22:05 /home/maxim_lvov/ca.key
-rw-r----- 1 maxim_lvov users 5.4K Jun 13 22:09 /home/maxim_lvov/keystore.jks
-rw-r----- 1 maxim_lvov users 2.0K Jun 13 22:08 /home/maxim_lvov/server.crt
-rw-r----- 1 maxim_lvov users 3.3K Jun 13 22:07 /home/maxim_lvov/server.key

**Comment by lwander** [comment] 2018-06-15 12:09
@usrleon maybe the logs can tell us something... could you put 

```
logging.level.root=DEBUG
```

into ~/.hal/default/profiles/gate-local.yml

and send us the startup output in a [gist](https://gist.github.com)?

**Comment by usrleon** [comment] 2018-06-15 18:09
https://gist.github.com/usrleon/47d7618061781ab19d86d1a677196f10

**Comment by lwander** [comment] 2018-06-15 18:16
I don't see any DEBUG entries, can you confirm that gate change was applied?

**Comment by usrleon** [comment] 2018-06-18 17:55
As you said I added line in ~/.hal/default/profiles/gate-local.yml and ran hal deploy apply
then checked if changes applied:
maxim_lvov@spinnaker-test:~$ sudo cat /opt/spinnaker/config/gate-local.yml
logging.level.root=DEBUG

**Comment by sbwsg** [comment] 2018-06-19 19:48
Hey @usrleon sorry, try this in the gate-local.yml:

```
logging:
  level:
    root: DEBUG
```

You should see a *lot* of DEBUG message in the gate log output.  If you only see INFO messages after this change then it looks like there is a problem with gate picking up config.  Otherwise, add your log output to a gist as described by @lwander.  Thanks!

**Comment by usrleon** [comment] 2018-06-19 20:45
@sbwsg seems like you're right, I proper added lines, but no debug in log file
here is what config look like:
root@spinnaker-test:~# cat /opt/spinnaker/config/gate-local.yml 
logging:
  level:
    root: DEBUG
I also tried to add this directly to /opt/spinnaker/config/gate.yml and restart, but also no luck

**Comment by sbwsg** [comment] 2018-06-22 12:14
OK I think we can work around this:

1. Kill the gate process by finding the pid with `sudo netstat -nlp | grep 8084` and then running `kill -15 $GATE_PID`
2. find the gate bin directory.  On my local debian install it's at `/opt/gate/bin`.
3. launch gate with `DEBUG=1 ./gate`

After this you should see a lot of debug messages, including which config files it's reading at startup.  If you then share the log in a gist or text file I can take a further look.  Thanks!

**Comment by usrleon** [comment] 2018-06-22 17:33
Ok, now I've got something https://gist.github.com/usrleon/e6faadd4ee9b474f3230a39fb43b6b87
I skipped rest of the log because tomcat already started on http. I'm not sure what does mean line
`Skipped (empty) config file 'file:/opt/gate/config/gate.yml' (classpath:/gate.yml) for profile`
but this file is not empty. I can attach full log if you need it

**Comment by usrleon** [comment] 2018-06-25 19:08
I used another 14.04 image and gate stared as ssl service (clouddriver failed to start completely, but thats another story) I checked java versions they are match, what can be different and cause this behavior?

**Comment by sbwsg** [comment] 2018-06-25 19:32
Hm, to be honest I don't have a good answer to that question.  Are the two different VM images publicly available?  I'd be interested to take a look at them to see what the differences are.  Thanks for the update.

**Comment by usrleon** [comment] 2018-06-26 21:16
Unfortunately one of them our own built image is private, the working one just public AMI image. I tried to install all missed packages to our image still no luck. I wonder if http/https conditionally switched why I don't see any debug messages or errors?

**Comment by sbwsg** [comment] 2018-06-27 14:59
Which Java version is each image using?  Could it be a difference between OpenJDK and Oracle?  It is also curious that logging changes to the gate configuration was never picked up by halyard in the private image.

I'm closing this issue now that we've identified the problem is somehow related to the VM image.    Unless we can pin down exactly what is causing the difference I don't think there is much value in keeping it open since it's not possible to determine whether the problem lives in Spinnaker or externally.

**Closed by sbwsg** 2018-06-27 14:59 UTC
Labels: component/gate

**Comment by alex25555** [comment] 2018-10-17 21:48
@sbwsg I don't see any subsequent changes to the certs being updated after a `hal deploy apply`, the contents of /home/username/.hal/default/staging/dependencies/, remain unchanged and file
 dates correlate to the original inception.

**Comment by alex25555** [comment] 2018-10-17 23:09
@sbwsg nvm, I realized the files backed up and pushed to Spinnaker are placed in /home/username/.hal/.backup/.
