### ISSUE TITLE
(spinnaker/deck) UI state is reverted to last save on pressing "Save Changes"

### ISSUE THREAD

**Issue by mmlac** [spinnaker/spinnaker#5018] opened 2019-10-11 06:33 UTC
### Issue Summary:
On a fresh simple Spinnaker deploy with halyard to a K8s cluster, Spinnaker version 1.16.2, Deck resets to the state presumably present before the edits on pressing the "Save Changes" button.

### Cloud Provider(s):
GCE & GKE

### Environment:
Spinnaker 1.16.2
K8s 1.14 - latest GKE
Istio 1.3.1 and no istio
halyard 1.24.0-20191002142815

### Feature Area:
Deck

### Description:

When creating a pipeline, on the Configuration item, add a new "Expected Artifact" — any type, base64 and GCS for me — and hit "Save Changes".
The artifact disappears from the UI.
Navigate away from the pipeline without saving it.
Click "Configure" on the pipeline
The artifact that was created is present as it should be.

My coworker found a similar behavior:

> I've found similar weird UI behavior:
> - Create new pipeline
> - Create CRON trigger
> - Click Save Changes. Trigger disappears from UI
> - Click arrow (left to pipeline name) to go back to the pipeline list
> - The message pops-up saying that there are unsaved changes (??!)
> - Click OK twice, to navigate away
> - Click Configure pipeline
> - The trigger is back in the UI

I also have to click OK twice on the unsaved changes popup, btw.
The call to the backend returns with a 200, no errors in the Chrome Console.

**Comment by maggieneterval** [comment] 2019-10-14 14:50
@mmlac thanks so much for taking the time to open this issue!

@christopherthielen @Jammy-Louie I'm unable to reproduce this behavior at HEAD, is this one of the issues your recent commits ([here](https://github.com/spinnaker/deck/commit/912ac90070946e799e56da6643701903f0e0c934) and [here](https://github.com/spinnaker/deck/commit/20d38f0958649ddad2ef43bbb702558046f53118)) were meant to address? If so, this should be resolved in our next patch release of 1.16!

**Comment by Jammy-Louie** [comment] 2019-10-15 14:36
@maggieneterval yes this issue should be resolved in the commits you mentioned.

**Comment by maggieneterval** [comment] 2019-10-15 15:24
Great, thanks @Jammy-Louie. @mmlac, going to close this for now, but please feel free to reopen if you're still seeing this problem after upgrading to 1.16.3.

**Closed by maggieneterval** 2019-10-15 15:24 UTC
Labels: component/deck, sig/ui-ux

**Comment by mmlac** [comment] 2019-10-16 07:51
Looks fixed in 1.16.3. Thanks! 👍
