### ISSUE TITLE
Gate failing after upgrading to 1.3.0

### ISSUE THREAD

**Issue by bernardoVale** [spinnaker/spinnaker#1947] opened 2017-09-11 02:39 UTC
**Title**

Gate failing after upgrading to 1.3.0

**Cloud Provider**

Kubernetes

**Environment**

Spinnaker running version 1.3.0 on Azure.

Halyard version: 0.34.0-20170908160431

**Feature Area**

Gate

**Description**

The following error is throw during `auth/redirect`:

```
{"error":"Internal Server Error","exception":"org.springframework.data.redis.serializer.SerializationException","message":"Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 320, local class serialVersionUID = 420","status":500,"timestamp":1505096874507}
```

**Steps to Reproduce**

Upgrade to 1.3.0?

**Additional Details**

```
Caused by: java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 320, local class serialVersionUID = 420
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1843) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_141]
	at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 72 common frames omitted

2017-09-11 02:33:17.359 ERROR 10361 --- [0.0-8084-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 320, local class serialVersionUID = 420
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:82) ~[spring-data-redis-1.8.4.RELEASE.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:338) ~[spring-data-redis-1.8.4.RELEASE.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashMap(AbstractOperations.java:282) ~[spring-data-redis-1.8.4.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:227) ~[spring-data-redis-1.8.4.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:102) ~[spring-data-redis-1.8.4.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:432) ~[spring-session-1.3.1.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:402) ~[spring-session-1.3.1.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:245) ~[spring-session-1.3.1.RELEASE.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:327) ~[spring-session-1.3.1.RELEASE.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:344) ~[spring-session-1.3.1.RELEASE.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:217) ~[spring-session-1.3.1.RELEASE.jar:na]
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.springframework.security.web.context.HttpSessionSecurityContextRepository.loadContext(HttpSessionSecurityContextRepository.java:110) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:100) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
```

```
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 320, local class serialVersionUID = 420
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:78) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:36) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:80) ~[spring-data-redis-1.8.4.RELEASE.jar:na]
	... 70 common frames omitted
Caused by: java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 320, local class serialVersionUID = 420
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1843) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_141]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_141]
	at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 72 common frames omitted
```

**Comment by bernardoVale** [comment] 2017-09-11 02:48
I've rolled it back to 1.2.2 and everything is working fine now.

**Comment by ethanfrogers** [comment] 2017-09-11 02:54
@bernardoVale try flushing your sessions in Redis. I'm not sure which iteration of Gate was released with 1.3.0, but I do know there was a breaking change that caused old sessions to fail deserialization.  Though, I would expect Halyard to handle that. @lwander might be able to shed more light on this.

**Comment by bernardoVale** [comment] 2017-09-11 02:56
I will try upgrading it again tomorrow @ethanfroger following your instructions.

**Comment by ethanfrogers** [comment] 2017-09-11 02:58
According to the Gate versions, it looks like that's the issue. See [this issue](https://github.com/spinnaker/gate/releases/tag/v4.0.0) for further info. I do believe that flushing your sessions will clear that error up!

**Comment by ethanfrogers** [comment] 2017-09-12 17:42
@bernardoVale were you able to get Spinnaker upgraded?

**Comment by bkruger99** [comment] 2017-09-20 18:32
I was able to upgrade.  Clearing redis sessions seemed to do the job.

This is making assumptions you're using ubuntu
Off of the gate server (yeah, I know, but I know it can talk to redis)

`sudo apt-get install redis-tools` -- this installs redis-cli

`netstat -an | grep 6379` -- grab the host ip that's using 6379 (or your redis port) -- use ss or if you know your redis server host + port,s kip to next step.

`redis-cli -h <host> (-p port) keys "spring:session*" | xargs redis-cli -h <host> (-p port) del`

Force reload your browser and you should be good to go.

**Comment by bggpoort** [comment] 2017-09-21 12:18
I can confirm this solution works.

**Comment by bernardoVale** [comment] 2017-10-02 13:15
Hey @ethanfrogers it's working now. Thanks @ethanfrogers and @bkruger99.

But I had to rollback again. Now I'm getting this error, also on gate:

```
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1029) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	... 16 common frames omitted
Caused by: java.lang.IllegalArgumentException: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:85) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:978) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:628) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1022) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	... 17 common frames omitted
```

Should we close this issue and open a new one?

**Comment by ethanfrogers** [comment] 2017-10-02 13:36
@bernardoVale glad it's working. yes, let's close this issue and open one for the issue you're now seeing.

**Closed** 2017-10-02 13:38 UTC

**Comment by bernardoVale** [comment] 2017-10-02 13:41
Done: https://github.com/spinnaker/spinnaker/issues/2001

**Comment by kevinawoo** [comment] 2018-03-23 19:03
I think this problem will present itself again on the next upgrade.

There's a couple of options present here: https://github.com/spring-projects/spring-session/issues/280.

They tried to fix it by [`Provide reliable serialization mechanism (not objectstream)`](https://github.com/spring-projects/spring-session/issues/348), but it looks like its been bumping it a lot, and now its `2.1.0.M1` now. Current version is `v2.0.2.RELEASE`.

Should we:
- try to wait for the new serialization and just flush caches for now?
- try to amend gate with deleting the key if it errors?
- try to make deck understand the error and reauth?

**Comment by cfieber** [comment] 2018-03-26 00:46
Next major dependency bump will come with spring-boot 2.0, I'd suggest see if there's a better option to fix session serialization there and if not I like the suggestion to delete the key on a serialization error

**Comment by idiamant** [comment] 2020-07-05 08:02
We have just encountered the same when upgrading from 1.17.6 to 1.20.6.
The actions from comment https://github.com/spinnaker/spinnaker/issues/1947#issuecomment-330941210  (removing sessions keys) resolved the issue and succeeded to progress with upgrade.

**Comment by tsuna** [comment] 2022-12-16 14:43
Just ran into the same issue when upgrading from 1.28.1 to 1.29.2
