### ISSUE TITLE
kubernetes v2 provider: Empty entries get removed from Kubernetes manifest

### ISSUE THREAD

**Issue by justinrlee** [spinnaker/spinnaker#5151] opened 2019-11-20 05:17 UTC
If you are deploying Kubernetes resources that have null entries, those get removed from the Kubernetes manifest.  In some situations, this is undesirable.

For example, if you have this in a Spinnaker deploy manifest stage:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-route
spec:
  host: hello-world
  to:
    kind: Service
    name: hello-service
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
```

When you save, it'll be reduced to this:

```
piVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-route
spec:
  host: hello-world
  to:
    kind: Service
    name: hello-service
    weight: 100
  wildcardPolicy: None
status: {}
```

This is problematic in this specific situation because for some reason, the OpenShift API validator is expecting the spec.status.ingress field to be present (side note, this occurs with `kubectl` in the CLI, but not with `oc`).

I would argue that in the generic, items should not be removed unless they are explicitly null (or not removed at all, ideally).

**Comment by ezimanyi** [comment] 2019-11-26 20:10
@justinrlee : Can you clarify exactly where this field is being deleted?  Is it happening when you save the manifest in the UI upon reload (which I can't reproduce) or somewhere in the processing before it gets sent to the cluster by clouddriver?

Also, I'm not sure I fully understand what you mean by:
> this occurs with `kubectl` in the CLI, but not with `oc`
Do you mean that `kubectl` also strips out the empty `ingress` when you try to apply the above manifest but `oc` doesn't?  Or do you mean that `kubectl` performs the validation that requires `spec.status.ingress` to be present bug `oc` doesn't?

Also, can you check if this occurs for things that aren't in the status field, which may have some kinds of special logic as it's in general meant for output only?

**Comment by maggieneterval** [comment] 2019-12-16 16:29
@justinrlee apologies for the slow followup! We discussed this issue at our last Kubernetes SIG issue triage meeting and decided that although at times this behavior can be confusing, ultimately it would be more confusing if Spinnaker deviated from the way `kubectl` handles empty entries. Going to close this for now.

**Closed by maggieneterval** 2019-12-16 16:29 UTC
Labels: provider/kubernetes-v2, sig/kubernetes
