### ISSUE TITLE
Unable to create server group in the Getting Started guide due to UI error(deck)

### ISSUE THREAD

**Issue by hiradha** [spinnaker/spinnaker#756] opened 2016-02-18 20:10 UTC
I am unable to create the 2nd stage (Deploy) of the pipeline in the Getting Started guide.
This seems to be due to a UI error in deck when addding a server group in the "Deploy" stage.

The error seems to be happening in the localSSDCount of cloneServerContrl.js;
The localSSDCount for some reason seems to be undefined when the execution reaching line 162 and hence the Array of persistent+local disks cannot be initialized.

129             $scope.command.persistentDiskSizeGb = defaultSettings.persistentDiskSizeGb;
130             $scope.command.localSSDCount = defaultSettings.localSSDCount;
… 
162       $scope.command.disks = Array($scope.command.localSSDCount + 1);
163       $scope.command.disks[0] = persistentDiskDescriptor;

**Comment by anotherchrisberry** [comment] 2016-02-18 20:13
@duftler can you take a look at this?

**Comment by duftler** [comment] 2016-02-18 20:26
Are you running a Spinnaker instance provisioned via the Cloud Launcher?

**Comment by duftler** [comment] 2016-02-18 20:39
I provisioned a new Spinnaker instance via [Cloud Launcher](https://cloud.google.com/launcher/solution/click-to-deploy-images/spinnaker?q=spinnaker) and worked through the steps in this [guide](http://spinnaker.io/documentation/getting_started.html).
I was able to get through step 2 and created the Deploy stage.
Can you provide steps to reproduce?

**Comment by hiradha** [comment] 2016-02-18 20:40
No. I am running on local machine via the docker instructions.

Thanks,
Radha.

**Comment by duftler** [comment] 2016-02-18 20:40
I stopped at this point, but would like to dig further once I have more details:
![image](https://cloud.githubusercontent.com/assets/8437718/13157429/e0429bc4-d655-11e5-8c8e-95a5303635f9.png)

**Comment by duftler** [comment] 2016-02-18 20:41
Ok, got it. Can you please provide the version numbers of the spinnaker services you are running? You mentioned running containers, so can you list out the tags of the running containers?

**Comment by hiradha** [comment] 2016-02-18 20:41
The steps are the same as in the Getting started guide except that

1) I am running a local machine spinnaker  using the provided docker setup
instructions.
2) My Cloud provider is GCE.

Thanks,
Radha.

**Comment by hiradha** [comment] 2016-02-18 20:44
How do I find the version numbers?

Thanks,
Radha.

**Comment by hiradha** [comment] 2016-02-18 20:46
The error happens when I click on "Add" button in the wizard before the
ServerGroup can be saved.

Thanks,
Radha.

**Comment by duftler** [comment] 2016-02-18 20:49
If you are following these instructions (https://github.com/spinnaker/spinnaker/tree/master/experimental/docker-compose) I think you can use kitematic to see the details of the running containers.

Hm. I just peeked at the container images (https://quay.io/organization/spinnaker) and they do appear to be up-to-date.

**Comment by duftler** [comment] 2016-02-19 03:44
In trying to reproduce this, I've been working through the docker compose instructions. Seems to hang for me at this spot:
```
bash-3.2$ DOCKER_IP=`docker-machine ip default` docker-compose up -d
rush is up-to-date
deck is up-to-date
redis is up-to-date
rosco is up-to-date
clouddriver is up-to-date
Pulling echo (quay.io/spinnaker/echo:latest)...
latest: Pulling from spinnaker/echo
9a24697294e3: Pull complete
bd4ebe1858b1: Pull complete
945ca1af4ff2: Pull complete
5404fd35cdec: Pull complete
a3405db8ea92: Pull complete
8a9132d0feca: Pull complete
04b9808d4bf4: Pull complete
e97bb94cbd3d: Pull complete
a023277e75e5: Pull complete
95f7865f80fe: Downloading [================================>                  ] 31.69 MB/48.15 MB
95170ae98734: Download complete
```

Will try some more tomorrow.

**Comment by leelasharma** [comment] 2016-02-22 13:36
The deck image on dockerhub is 3 months old. The recent builds seemed to have all failed
https://hub.docker.com/r/spinnaker/deck/builds/

**Comment by duftler** [comment] 2016-02-22 13:38
Looks like @tomaslin switched to using quay a while back: https://github.com/spinnaker/spinnaker/commit/84655c81da03f54c14a1d112e29b61f73d71b32c

**Comment by leelasharma** [comment] 2016-02-22 14:23
Thanks @duftler that makes sense. But the other modules are still successfully pushing to docker hub. For example: https://hub.docker.com/r/spinnaker/clouddriver/

**Comment by tomaslin** [comment] 2016-02-23 09:52
I've removed the repos from docker hub since there has been consistent issues with building deck. Please use the images from quay.io

**Comment by tomaslin** [comment] 2016-03-11 16:12
@hiradha is this still an issue?

**Comment by wemu** [comment] 2016-04-15 07:50
not sure if its related. I followed the instructions to run spinnaker locallly using docker-compose. The containers start fine. But the container based on quay.io/spinnaker/deck disappears after a few minutes - could not yet find out why :/

**Comment by lwander** [comment] 2018-05-16 15:26
Closing since this is largely obsolete with all the UI changes that have happened in the last 2-3 years

**Closed by lwander** 2018-05-16 15:26 UTC
Labels: component/deck
