### ISSUE TITLE
Clouddriver Caching Agent SQL Error

### ISSUE THREAD

**Issue by battlecow** [spinnaker/spinnaker#5838] opened 2020-06-15 02:14 UTC
### Environment:
Using Spinnaker 1.19.11 in Kubernetes with MySQL backends setup for clouddriver, orca, and front50 in AWS Aurora.
Running with Clouddriver in HA mode.

### Description:
Getting a sql error: 

```
2020-06-15 02:07:52.115 ERROR 1 --- [utionAction-410] c.n.spinnaker.cats.sql.cache.SqlCache    : Error inserting forward relationships for artifact -> ServiceMonitor.monitoring.coreos.com

org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [insert into cats_v1_artifact_rel (uuid, id, rel_id, rel_agent, rel_type, last_updated) values (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?) -- agentClass: cloud-engineering-jpro-services-cicd-use1/KubernetesUnregisteredCustomResourceCachingAgent[1/1] putCacheResult]; Data truncation: Data too long for column 'rel_agent' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'rel_agent' at row 1
	at org.jooq_3.12.3.MYSQL.debug(Unknown Source) ~[na:na]
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at com.netflix.spinnaker.kork.sql.JooqToSpringExceptionTransformer.exception(JooqToSpringExceptionTransformer.kt:33) ~[kork-sql-7.25.13.jar:7.25.13]
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:261) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:383) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:119) ~[jooq-3.12.3.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache$storeInformative$$inlined$forEach$lambda$1$1.invoke(SqlCache.kt:774) ~[cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache$storeInformative$$inlined$forEach$lambda$1$1.invoke(SqlCache.kt:49) ~[cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCacheKt$sam$java_util_function_Supplier$0.get(SqlCache.kt) ~[cats-sql.jar:na]
	at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$2(Retry.java:177) ~[resilience4j-retry-1.0.0.jar:1.0.0]
	at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.0.jar:na]
	at io.vavr.control.Try.ofSupplier(Try.java:92) ~[vavr-0.10.0.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache.withRetry(SqlCache.kt:1463) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache.access$withRetry(SqlCache.kt:49) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache$storeInformative$$inlined$forEach$lambda$1.invoke(SqlCache.kt:773) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache$storeInformative$$inlined$forEach$lambda$1.invoke(SqlCache.kt:49) [cats-sql.jar:na]
	at kotlin.collections.CollectionsKt___CollectionsKt.windowed(_Collections.kt:2396) [kotlin-stdlib-1.3.70.jar:1.3.70-release-328 (1.3.70)]
	at kotlin.collections.CollectionsKt___CollectionsKt.chunked(_Collections.kt:2147) [kotlin-stdlib-1.3.70.jar:1.3.70-release-328 (1.3.70)]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache.storeInformative(SqlCache.kt:754) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.cache.SqlCache.mergeAll(SqlCache.kt:151) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.SqlProviderCache.cacheDataType(SqlProviderCache.kt:331) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.SqlProviderCache.cacheDataType(SqlProviderCache.kt:308) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.SqlProviderCache.putCacheResult(SqlProviderCache.kt:234) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.storeAgentResult(CachingAgent.java:139) [cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:78) [cats-core.jar:na]
	at com.netflix.spinnaker.cats.sql.cluster.AgentExecutionAction.execute(SqlClusteredAgentScheduler.kt:293) [cats-sql.jar:na]
	at com.netflix.spinnaker.cats.sql.cluster.AgentJob.run(SqlClusteredAgentScheduler.kt:312) [cats-sql.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

**Comment by maggieneterval** [comment] 2020-06-24 13:43
Thanks for reporting, @battlecow! Closing since this is a duplicate of https://github.com/spinnaker/spinnaker/issues/5600 -- a fix is underway.

**Closed by maggieneterval** 2020-06-24 13:43 UTC
