### ISSUE TITLE
Spinnaker doesn't show Infrastructure info

### ISSUE THREAD

**Issue by vuxuanlai** [spinnaker/spinnaker#5765] opened 2020-05-14 04:25 UTC
### Issue Summary:
Spinnaker doesn't show Infrastructure info

### Cloud Provider(s):
K8S

### Environment:
spinnaker 1.20.1

### Description:
Sometimes, Spinnaker doesn't show deployment information in Infrastructure tab. After some minutes, It's return to working normally.

![Screenshot from 2020-05-14 11-06-38](https://user-images.githubusercontent.com/1458400/81892576-a65e6c00-95d5-11ea-94bc-874d4ab51222.png)

**Comment by ezimanyi** [comment] 2020-05-14 16:10
Closing as a duplicate of #5611, which has some details on why this happens and some ideas about how to fix it.

**Closed by ezimanyi** 2020-05-14 16:10 UTC
