### ISSUE TITLE
Kubernetes Provider V2: LoadBalancer Service does not exist

### ISSUE THREAD

**Issue by tonyg4864** [spinnaker/spinnaker#5040] opened 2019-10-17 23:25 UTC
### Issue Summary:
I am currently facing an issue where a Deploy (Manifest) stage fails to find a pre-existing Kubernetes service/loadbalancer. This happens while I have enabled Red/Black Rollout Strategy.

### Cloud Provider(s):
Kubernetes

### Environment:

1. Spinnaker v1.16.2 with no MYSQL enabled. 
2. Spinnaker v1.16.3 with MYSQL enabled for Orca, Front50 and Clouddriver.
3. liveManifestCalls = true

### Feature Area:

- Kubernetes Provider V2
- CloudDriver
- Pipelines
- Rollout Strategies
- Red/Black

### Description:

- I am currently facing an issue where a Deploy (Manifest) stage fails to find a pre-existing Kubernetes service/loadbalancer. This happens while I have enabled Red/Black Rollout Strategy. I am using the Kubernetes V2 provider. 

- I noticed that this happens while I'm using a Helm Chart Artifact to deploy the ReplicaSet. If I copy paste the rendered replicaset.yaml file out of the HelmChart into a raw text Deploy(Manifest ) stage, the issue does not happen.

- I see a potential issue with a clouddriver query. It seems it’s using the Spinnaker application name where the service name is supposed to be used instead. In the query below san-tony-bluegreen is my Spinnaker application name , not my Kubernetes service name. :

```2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Executing query          : SELECT id FROM cats_v1_loadBalancers WHERE id LIKE 'kubernetes:loadBalancers:%:%:san-tony-bluegreen'```

Here is my Spinnaker Deployed Load Balancer:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    artifact.spinnaker.io/location: san-tony-bluegreen
    artifact.spinnaker.io/name: mediastreaming-ovsys-22644-bluegreen
    artifact.spinnaker.io/type: kubernetes/service
    moniker.spinnaker.io/application: san-tony-bluegreen
    moniker.spinnaker.io/cluster: service mediastreaming-ovsys-22644-bluegreen
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: san-tony-bluegreen
  name: mediastreaming-ovsys-22644-bluegreen
  namespace: san-tony-bluegreen
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    frontedByInstance: ovsys-22644-bluegreen
    frontedByName: mediastreaming
  type: NodePort
```

- In the query , it seems that the first wildcard is meant for the kubernetes account name, the second wildcard is meant for the Spinnaker application name, and the 3rd field should be the name of the Loadbalancer which in this case is “mediastreaming-ovsys-22644-bluegreen” .

The log shows 0 records found for that query .

But I know my loadbalancer does exist in the DB. If I manually run the following query, I get a matching record:
    SELECT id FROM cats_v1_loadBalancers where id like '%san-tony-bluegreen%';

Found Record:
    kubernetes:loadBalancers:my-k8s-account:san-tony-bluegreen:mediastreaming-ovsys-22644-bluegreen

### Steps to Reproduce:
1. Deploy a Kubernetes Service/ Spinnaker LoadBalancer using the "Create Load Balancer" Option under a Spinnaker Application in Infrastructure->LoadBalancers. Use the Kubernetes V2 provider. 
Sample Service:
 ```
apiVersion: v1
kind: Service
metadata:
  name: mediastreaming-ovsys-22644-bluegreen
  namespace: san-tony-bluegreen
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    frontedByInstance: ovsys-22644-bluegreen
    frontedByName: mediastreaming
  type: NodePort
```
2. Create a Pipeline that contains a Deploy (Manifest) stage. Configure the Stage to deploy a ReplicaSe using a Helm Chart artifact. 
3. Enable the Red/Black Rollout Strategy functionality. Select the service previously created. 
4. Run the pipeline to deploy the application. 
5. Notice that the deployment stage fails with the following error:
```
Exception ( Monitor Deploy )
Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist
```
![ServiceNotFound](https://user-images.githubusercontent.com/25211037/67055879-a4dfca80-f0fe-11e9-9ad9-72ac4e01a7e9.png)

### Additional Details:

1. My Deployment Manifest stage uses a Helm Chart artifact to deploy the ReplicaSet.
2. Although Im testing this by deploying the Service separately and manually...It'll be great if this scenario also works when including the deployment of the Service in the HelmChart. In practice we use one HelmChart to deploy most of our Kubernetes manifest/resources . Example: We use 1 HelmChart to deploy the ingress, service, secrets, configmaps and replica sets for a particular application.
3.  The sample log message from clouddriver that I feel is performing the incorrect query is : 
```2019-10-17 20:33:14.346 DEBUG 1 --- [0.0-7002-exec-3] o.a.c.loader.WebappClassLoaderBase       :     findClass(com.netflix.spinnaker.clouddriver.search.SearchProvider$search)
2019-10-17 20:33:14.347 DEBUG 1 --- [pool-8-thread-3] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@462ea3ed
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched result           : +----+
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : |id  |
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : +----+
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched row(s)           : 0
2019-10-17 20:33:14.347 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Executing query          : SELECT id FROM cats_v1_loadBalancers WHERE id LIKE 'kubernetes:loadBalancers:%:%:san-tony-bluegreen'
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2019-10-17 20:33:14.347 DEBUG 1 --- [pool-8-thread-3] org.jooq.impl.DefaultConnectionProvider  : commit
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-3] o.a.c.loader.WebappClassLoaderBase       :     --> Returning ClassNotFoundException
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@14505491
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : Executing query          : delete from cats_agent_locks where (agent_name = ? and lock_expiry = ?)
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : -> with bind values      : delete from cats_agent_locks where (agent_name = 'SqlTableMetricsAgent' and lock_expiry = '1571344390184')
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@462ea3ed
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched result           : +----+
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : |id  |
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : +----+
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched row(s)           : 0
2019-10-17 20:33:14.349 DEBUG 1 --- [pool-8-thread-3] org.jooq.impl.DefaultConnectionProvider  : setting auto commit      : true
2019-10-17 20:33:14.350 DEBUG 1 --- [0.0-7002-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Using 'application/json;charset=UTF-8', given [application/json;charset=UTF-8] and supported [application/json]
2019-10-17 20:33:14.350 DEBUG 1 --- [0.0-7002-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Writing [[KubernetesV2LoadBalancer(serverGroups=[], manifest={metadata={annotations={artifact.spinnaker.io/lo (truncated)...]
2019-10-17 20:33:14.350 DEBUG 1 --- [0.0-7002-exec-1] o.s.web.servlet.DispatcherServlet        : Completed 200 OK
2019-10-17 20:33:14.351 DEBUG 1 --- [pool-8-thread-3] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@4119dd79
2019-10-17 20:33:14.351 DEBUG 1 --- [pool-8-thread-3] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2019-10-17 20:33:14.351 DEBUG 1 --- [0.0-7002-exec-1] o.a.c.http11.filters.GzipOutputFilter    : Flushing the compression stream!
2019-10-17 20:33:14.351 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
2019-10-17 20:33:14.352 DEBUG 1 --- [0.0-7002-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Chain processed normally
2019-10-17 20:33:14.352 DEBUG 1 --- [pool-8-thread-3] org.jooq.impl.DefaultConnectionProvider  : setting auto commit      : false
2019-10-17 20:33:14.352 DEBUG 1 --- [gentScheduler-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.```

**Comment by maggieneterval** [comment] 2019-10-30 19:29
Hi @tonyg4864, thank you for the detailed issue report.

I think the Clouddriver error you are seeing (`Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist`) originates [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java#L272). Could you verify this by looking for a stack trace in the failed execution's JSON (Execution Details --> Source)? We are shelling out to `kubectl` here to fetch the full manifest of your service. For this call, we are using the namespace of the target ReplicaSet. Are you explicitly specifying a namespace on your ReplicaSet manifest, even when deploying with Helm? You mentioned that this is not a problem when copying the ReplicaSet manifest from the Helm chart into the Deploy Manifest textbox -- are you adding a namespace in this case or is it exactly the same YAML?

I'm not sure where the seemingly malformed SQL queries are originating from, since we make a live call instead of reading from the cache when attaching a service to a workload.

**Comment by tonyg4864** [comment] 2019-10-30 23:10
Hi @maggieneterval , thanks for looking into this. 
You appear to be correct. See the JSON (Execution Details --> Source) response below.

Are you explicitly specifying a namespace on your ReplicaSet manifest, even when deploying with Helm? : 
    For ReplicaSet, I am setting the namespace value in the Bake (Manifest) stage . There is an input field for "Namespace" value in there. My Helm service.yaml file has the following token: 
```
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
.....
```
    The bake stage renders my replicaset file with all tokens replaced with the actual values. 

You mentioned that this is not a problem when copying the ReplicaSet manifest from the Helm chart into the Deploy Manifest textbox -- are you adding a namespace in this case or is it exactly the same YAML: 

- What I do is a copy the rendered manifest file by the Bake stage and paste it into a Deploy Manifest stage textbox without leveraging Helm Artifacts. I'm not changing anything. So yes it already includes the namespace set correctly inline in the yaml manifest file for the replicaset. 

JSON (Execution Details --> Source):
```
kato.tasks: [
{
exception: {
cause: "Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist",
details: [
{
message: "Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist"
}
],
message: "Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist",
type: "EXCEPTION",
operation: "KubernetesDeployManifestOperation"
},
resultObjects: [
{
cause: "Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist",
details: [
{
message: "Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist"
}
],
message: "Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist",
type: "EXCEPTION",
operation: "KubernetesDeployManifestOperation"
}
],

...
...

{
phase: "ORCHESTRATION",
status: "Orchestration failed: KubernetesDeployManifestOperation | IllegalArgumentException: [Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist]"
}
],
```

**Comment by tonyg4864** [comment] 2019-10-30 23:22
Also, just as a side note....as of not many releases ago, it is now possible to Override the Namespace value in the Deploy Manifest Stage via the "Override Namespace" input field. I've also tried that and no luck.

**Comment by maggieneterval** [comment] 2019-10-31 15:53
> What I do is a copy the rendered manifest file by the Bake stage and paste it into a Deploy Manifest stage textbox without leveraging Helm Artifacts. I'm not changing anything. So yes it already includes the namespace set correctly inline in the yaml manifest file for the replicaset.

Hmm, if you're deploying exactly the same ReplicaSet manifest with the only difference being that in the Helm case, the Deploy stage receives it as a base64 artifact, and in the non-Helm case, it's just the same text inline, I'm really not sure why you'd only be getting the error in the first case only.

I can try to reproduce locally if you're able to share some minimal example that reproduces the issue including:
- Full pipeline JSON
- Helm .tgz artifact you're supplying to the Bake Manifest stage

**Comment by maggieneterval** [comment] 2019-12-03 16:22
Going to close this for now, but please feel free to reopen if you're still facing this issue and able to provide an example for me to reproduce it!

**Closed by maggieneterval** 2019-12-03 16:22 UTC
Labels: provider/kubernetes-v2, sig/kubernetes

**Comment by dpolicastro** [comment] 2020-03-13 00:51
I'm having the exactly same problem right now, any news on this?

**Comment by lersouza** [comment] 2020-06-30 17:58
Hey Guys. I'm facing this issue, but for first deployments. Since the service does not exist (it will be created in the baked manifest for the first time), it raises this error. It seems the service **must** be already created when using the Deployment Strategies. Is that right? If so, any suggestions on how to organize services/replicaset manifests? I'm currently using one HELM chart for all.

**Comment by mtaylor98** [comment] 2020-07-24 21:13
I am also running into this exact issue. I am deploying a single manifest that contains a namespace, service and replicaSet. The initial deployment works with no problem as long as my pipeline is not configured with any sort of deployment strategy (highlander or red/black). But if I push a change to that manifest that updates something about the replicaSet and my pipeline runs, and is configured with either a red/black or highlander roll out strategy it fails with "Load Balancer does not exist" error despite the service having already been created. I am able to get this working with a roll out strategy if I push ONLY the replicaSet manifest through the pipeline not the entire manifest that contains the namespace, service and replicaset.

**Comment by alessiotrivisonno** [comment] 2021-03-04 16:57
I use helmfile to generate the template and then I deploy the rendered manifest with Spinnaker. 
I got it working doing these steps: 
- In the pipeline step Deploy override the namespace with your desired one ( Create it if it doesn't exist ) 
- Deploy the service without rollout stragegy
- Apply the Rollout strategy you want
- Re-Deploy the service

Although it's painful and not well streamlined it's not so bad as it has to be done only the first time

**Comment by anshchauhan** [comment] 2022-03-22 06:29
Facing same issue...
