### ISSUE TITLE
Configure Project Windows is closed abruptly if 'Add Cluster' is clicked.

### ISSUE THREAD

**Issue by dvropsmx** [spinnaker/spinnaker#5160] opened 2019-11-21 13:16 UTC
### Issue Summary:
Configure Project Windows is closed abruptly if 'Add Cluster' is clicked. Since Iam unable to create a new Project with cluster details in Spinnaker v1.17.2. Though I could create a Project successfully with in Spinaker v1.16.1.

### Cloud Provider(s):
N/A

### Environment:
1.17.2

### Feature Area:
Deck

### Description:
When we tried to create a new Project in Spinnaker v1.17.2,  the 'Configure Project' windows is closed abruptly upon clicking 'Add Cluster' button.

### Steps to Reproduce:
1.  Install Spinnaker v1.17.2
2.  Navigate to Applications window and create some sample applications from its Actions.
3.  Then Navigate to Projects windows and Create a sample Project from Actions. If 'Add Cluster' button is clicked then the new Configure Project window will be closed.

### Additional Details:
N/A

**Comment by sanopsmx** [comment] 2019-12-02 07:49
I will be working on this issue.

**Comment by sanopsmx** [comment] 2019-12-04 06:24
This issue is a duplicate of spinnaker/spinnaker#5174. We can close this issue.

**Closed** 2020-01-06 15:52 UTC
Labels: sig/ui-ux
