### ISSUE TITLE
Baked Artifact No Longer an Option in Spinnaker 1.15.0/1.15.1

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4691] opened 2019-07-30 00:24 UTC
### Issue Summary:

Base64 artifacts from a previous stage no longer appear as an option in the Manifest Artifact dropdown on a Deploy Manifest stage for Kubernetes V2 in Spinnaker 1.15.0. Spinnaker 1.15.1 did not fix this.

### Cloud Provider(s):

GKE

### Environment:

Spinnaker 1.15.1

### Feature Area:

@spinnaker/ui-ux

### Steps to Reproduce:

1. Create a pipeline with a Bake Helm 2 stage that produces a Base64 artifact.
2. Add a Deploy Manifest stage and try to select the artifact from the Bake stage to deploy. It does not appear in the dropdown.

**Comment by ethanfrogers** [comment] 2019-07-30 00:27
I saw this report today. Will take a look this week.

**Comment by judexzhu** [comment] 2019-07-30 01:57
We've upgraded into 1.15.1 this morning.

The issue is still there.

Just FYI

**Comment by prestonvanloon** [comment] 2019-08-05 03:20
Duplicate of https://github.com/spinnaker/spinnaker/issues/4656 which was closed as fixed, although the problem still exists.

**Comment by ethanfrogers** [comment] 2019-08-05 14:35
I think this is a separate bug from #4656 though they are related to the same area.

**Closed** 2019-08-06 12:37 UTC
Labels: provider/kubernetes-v2, sig/kubernetes
