### ISSUE TITLE
[Pipeline Template] - Render object variables results in malformed key/value pairs

### ISSUE THREAD

**Issue by PerGon** [spinnaker/spinnaker#2217] opened 2018-01-03 14:43 UTC
*Feature Area*

Declarative Pipelines, Pipeline Templates

*Description*

When trying to render variable objects in a templated pipeline, the result is a wrongly formed pipeline.
Consider the following pipeline template:
<pre>
schema: '1'

variables:
  - name: deploy_config
    type: object
    defaultValue:
      dev:
        <b>key1_1: value1_1
        key1_2: value1_2 </b>

stages:
- id: deploy_dev
  type: deploy
  config:
    whatever: "{{ deploy_config['dev']}}"
</pre>
As of Orca `v5.6.1`, the pipeline definition that results of the above pipeline template is the following:
<pre>
{
  "keepWaitingPipelines": false,
  "limitConcurrent": true,
  "application": "myapp",
  "parameterConfig": [],
  "name": "Unnamed Execution",
  "stages": [{
    "requisiteStageRefIds": [],
    "name": "deploy_dev",
    "id": "3ca68778-ca87-4563-aff7-ab3fe7440493",
    "refId": "deploy_dev",
    "type": "deploy",
    "whatever": {
     <b> "key1_1=value1_1": null,
      "key1_2=value1_2": null </b>
    }
  }],
  "id": "unknown",
  "notifications": []
}
</pre>
(highlighted in bold what is wrong)

*Steps to Reproduce*

Check the [top commit](https://github.com/PerGon/orca/commit/7f092bb2d2a94aace5ac0ba656a1adb7482b3136) of [this branch](https://github.com/PerGon/orca/commits/pipe_template_var_object). Running that test will show the behavior described above.

*Additional Details*

This is what I would expect:
<pre>
{
  "keepWaitingPipelines": false,
  "limitConcurrent": true,
  "application": "myapp",
  "parameterConfig": [],
  "name": "Unnamed Execution",
  "stages": [{
    "requisiteStageRefIds": [],
    "name": "deploy_dev",
    "id": "3ca68778-ca87-4563-aff7-ab3fe7440493",
    "refId": "deploy_dev",
    "type": "deploy",
    "whatever": {
     <b> "key1_1":"value1_1",
      "key1_2":"value1_2" </b>
    }
  }],
  "id": "unknown",
  "notifications": []
}
</pre>

I did spend some time trying to figure this out, but I couldn't come up with a good solution. Thoughts?

**Comment by rajachawat** [comment] 2018-02-05 14:24
I had the same issue few days ago. @jervi helped me resolve it. 
I had to replace 
```config:
         parameters:
               {{ params }}
``` 
with 
```
config: 
  parameters:
        {{ '{' }}{% for k, v in params.items() %}{{ k }}: {{ v }}{% if not loop.last %}, {% endif %}{% endfor %}{{ '}' }}```

**Comment by prondeau** [comment] 2018-02-05 22:43
Thanks for the workaround @rajachawat, worked for me, but while experimenting, I also found that piping the object into the json filter worked for me:

From:
```
parameters:
    {{ params }}
```
To:
```
parameters:
    {{ params|json }}
```

**Comment by jervi** [comment] 2018-02-05 22:44
That is so much nicer, thanks @prondeau

**Comment by prondeau** [comment] 2018-02-28 19:27
So I've come up with another scenario that I believe is caused by the same issue, this time I can't come up with any workarounds. I have this template:
```
- imageDescription: |
    {% if environment == 'dev' %}
    account: my-account
    fromTrigger: true
    registry: us.gcr.io
    repository: my-registry/my-image
    tag: null
    {% else %}
    fromContext: true
    stageId: "findImage"
    {% endif %}
```
However, this is being parsed in the false case (and similarly for the true case) as: `"\"\\nfromContext: true\\nstageId: \\\"findImage\\\"\\n\\n\"",`

Anyone have any solutions for this?

**Comment by jtk54** [comment] 2018-04-30 21:36
The last comment in this thread was addressed by https://github.com/spinnaker/spinnaker/issues/2515. Closing this out since there are workarounds in Jinja.

**Closed by jtk54** 2018-04-30 21:36 UTC
