### ISSUE TITLE
Permission propagating for application is delayed and based on request frequency

### ISSUE THREAD

**Issue by BrianBerzins** [spinnaker/spinnaker#2066] opened 2017-10-26 19:29 UTC
*Title*

Permission propagating for application is delayed and based on request frequency

*Cloud Provider*

Openstack

*Environment*

Halyard version 1.4.2 openstack and k8s providwrs

*Feature Area*

API, FIAT

*Steps to Reproduce*

1. Create an application via the API (POST to /tasks) -- note: the application has permissions
1. Poll the task until it has completed
1. Update the application (POST to /applications/{application}/tasks)
1. Poll the task until it has completed
1. Delete the application (POST to /tasks)
1. Poll the task until it has completed.

*Description*

Step #3 fails with a 403 permission denied. The application comes included with permissions, and it seems like fiat takes awhile (even after the task to create is completed) for the permissions to be set correctly.

The testing harness I'm using makes it very easy to retry requests, so I tried having it retry the update (POST to /applications/{application}/tasks) until a 403 isn't received.

There are two things I would normally expect here:

1. I would not expect to continuously receive 403 responses on subsequent attempts to update over a long period of time. A slowly loop demonstrates the correct permissions are eventually getting there.
1. On a larger scale: I wouldn't expect the "create" task to finish successfully until the permissions are fully wired: thereby preventing the 403 case from every arising. 

*Additional Details*

Additional information such as screenshots and exception logs.

**Comment by jtk54** [comment] 2017-11-02 20:08
Are you guys scripting against the endpoints in 1-3? Just clarifying the use case.

> 1. I would not expect to continuously receive 403 responses on subsequent attempts to update over a long period of time. A slowly loop demonstrates the correct permissions are eventually getting there.

The Fiat clients in the Spinnaker services use a local read-through cache to cut down on network traffic to Fiat. The cache is keyed _by user_ and configured with a default TTL of 20 seconds. Since the same user is doing step (1) and step (3), the user key is in the cache, and since the time between (1) and (3) is < 20 seconds, the newly created application hasn't propagated to the cache yet (but eventually does as you mentioned).

> On a larger scale: I wouldn't expect the "create" task to finish successfully until the permissions are fully wired: thereby preventing the 403 case from every arising.

Reiterating: the create finishes because Fiat itself stores and updates the user permissions. The user caches are eventually consistent with Fiat as described above.

You have a few options:

1. Set the TTL to 0 [with this property](https://github.com/spinnaker/fiat/blob/master/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java#L39) in each service.

2. Add a `sleep(1.5 * TTL)` in your script

**Comment by BrianBerzins** [comment] 2017-11-03 15:10
> Are you guys scripting against the endpoints in 1-3?

Yes.

> The client caches are eventually consistent with Fiat as described above.

So, if I'm understanding this correctly: as long as I'm making a request to the a resource (or in this case: making the post to the tasks) and there was something return within that TTL (default 20 seconds), then that previous value will be returned. The part that really throws me about this, is that the subsequent requests are effectively reseting the TTL. 

I guess in this case I would expect to see 20 seconds (TTL) of 403... but after that, I expect the cache to have been evicted? I guess I don't expect a "cache hit" to extend the life of the value in the cache.

**Comment by jtk54** [comment] 2017-11-03 15:37
My understanding is that the Fiat client cache should be re-synced every 20 (by default) seconds regardless of how many reads occur (@ttomsu please confirm). If you loop (3) and there is < 20s between each retry, will the operation continue to 403 for you (indicating the TTL is reset)?

Regardless, Fiat was designed with the assumption that applications are not updated frequently (more than once per 20s) which should be sufficient. You still have the option of setting the TTL to zero.

**Comment by BrianBerzins** [comment] 2017-11-03 16:16
> If you loop (3) and there is < 20s between each retry, will the operation continue to 403 for you (indicating the TTL is reset)?

When I did ran with a 3 second sleep between attempts: it I would continuously receive 403s for at least 2 hours.
When I did the run with a 30 second sleep between attempts, the request was successful after the first 30 second wait.

> Regardless, Fiat was designed with the assumption that applications are not updated frequently (more than once per 20s) which should be sufficient.

I hear where you're coming from on this one. The test I have is pushing things through a lifecycle very fast to validate that our automation (of which spinnaker is one dependent component).

**Comment by jtk54** [comment] 2017-11-06 19:21
@BrianBerzins do you have a path forward for your use case? Any problem with closing this?

**Comment by jtk54** [comment] 2017-11-06 20:08
Closing, feel free to reopen if needed.

**Closed by jtk54** 2017-11-06 20:08 UTC
Labels: component/fiat

**Comment by BrianBerzins** [comment] 2017-11-08 16:39
Found a different offending component. I still don't really like the idea that a backend update doesn't invalidate an entry in the cache, but I understand why it was done. Thanks, and sorry for the run around.
