### ISSUE TITLE
RFC: Helm 3 Rendering Engine 

### ISSUE THREAD

**Issue by evansb** [spinnaker/spinnaker#5474] opened 2020-02-20 01:42 UTC
This issue serves as RFC as well as progress tracker for adding Helm 3 support to Spinnaker.

[Feature Request Issue](https://github.com/spinnaker/spinnaker/issues/5106)

## Key Decisions Taken/Considerations

- Helm 3 binary will be installed alongside Helm 2 binary in Rosco image.
  While Helm 3 might be able to render most Helm 2 chart, quick testing shows that there are few corner cases that makes `helm template`
  behave differently on 2 vs 3. For instance, the `Capabilities` built-in object is simplified in Helm 3 and not backwards compatible with Helm 2.
- Allow `helm` executable path to be configured using `helm.v3ExecutablePath` for Spinnaker deployments not using official container images.
- `helm template` will validate final values file against `values.schema.json` in the chart, if any. Make sure the error is propagated to the user

## Changes

* [x] ([rosco/536](https://github.com/spinnaker/rosco/pull/536)) Install `helm3` binary alongside `helm` (v2) in container image.
* [x] ([rosco/537](https://github.com/spinnaker/rosco/pull/537)) Allow choosing between helm 3 and helm 2  binary in `HelmBakeManifestService`.
* [x]  ([deck/7924](https://github.com/spinnaker/deck/pull/7924)) Add HELM3 render engine type in Bake Manifest Stage UI (Deck).
* [x] ([orca/3460](https://github.com/spinnaker/orca/pull/3460) Add HELM3 render engine type in Orca

## Out of Scope
- **OCI Registry** Support of downloading and listing charts from [OCI Registry](https://helm.sh/docs/topics/registries/) will be split to different RFC (it is currently experimental).
- **Helm Deployment** The absence of Tiller in Helm 3 aligns Helm auth mechanism with Spinnaker, increasing the feasibility of adding `helm` as an additional way to deploy in Clouddriver on top of `kubectl`
to manage Helm releases and to support Helm Install features such as Hooks. This is something of a larger scope that can be explored in the future.

## References

- [Changes in Helm 3](https://v3.helm.sh/docs/faq/#changes-since-helm-2)

## Changelog

19/2 - Initial Version

**Comment by dpolicastro** [comment] 2020-03-04 18:42
Hi @evansb , this feature is already available to use? I recently installed spinnaker via Helm but only Helm 2 is available to use as a template render for a `Bake (Manifest)` step in the UI. I'm new to Spinnaker, I need to enable it via Halyard or something?

**Comment by evansb** [comment] 2020-03-05 00:48
@dpolicastro it is currently in master, will only be available in 1.19 the earliest.

to test, set the Spinnaker version to `master-latest-unvalidated`

**Comment by vivekanandg** [comment] 2020-03-09 07:08
When is this expected to be released?

**Comment by ansraliant** [comment] 2020-03-19 01:18
Confirmed it has been released in version 1.19 of Spinnaker
https://www.spinnaker.io/community/releases/versions/1-19-0-changelog

**Comment by maggieneterval** [comment] 2020-03-25 17:47
Thanks for all your work on this, @evansb! Since this feature was released with Spinnaker 1.19, I'm going to close this issue now.

**Closed by maggieneterval** 2020-03-25 17:47 UTC
Labels: sig/kubernetes

**Comment by justinrlee** [comment] 2020-04-03 14:39
Does this use git/repo or does this still rely on the helm chart being a tarball?

**Comment by evansb** [comment] 2020-04-03 15:05
@justinrlee it's agnostic on the artifact, Artifact downloading is delegated to `clouddriver` so it depends whether clouddriver supports downloading `git/repo` artifact or not.

**Comment by evansb** [comment] 2020-04-03 15:07
It seems does: https://github.com/spinnaker/clouddriver/blob/4aa6378c74930851b578ece5dd618cc8e2d336c3/clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactCredentials.java#L98, you can try it and report back any issues

**Comment by justinrlee** [comment] 2020-04-03 15:11
Awesome, thank you!  Sorry, I realize I should've just spun up a Spinnaker instance first to try.  Thanks for the response!

**Comment by maggieneterval** [comment] 2020-04-03 15:44
@justinrlee I was under the impression that git/repo artifact support for Helm was not implemented yet; I think we're tracking that feature request [here](https://github.com/spinnaker/spinnaker/issues/5249).

**Comment by justinrlee** [comment] 2020-04-05 17:37
Okay, yeah.  As far as I can tell, this does not support git/repo - could/should be added, but not there yet.
