### ISSUE TITLE
Clouddriver fails to finish initialize if a K8s cluster is unreachable

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4502] opened 2019-06-07 16:33 UTC
### Issue Summary:

Clouddriver is failing to open port 7002 on its pod on GKE. No errors in the logs.

### Cloud Provider(s):

GKE

### Environment:

Halyard 1.20.2
Spinnaker 1.14.1

### Feature Area:

@spinnaker/clouddriver

### Description:

Prometheus metrics are enabled, so the metrics sidecar is attempting to get `localhost:7002/spectator/metrics`, but since clouddriver isn't opening 7002, it's erroring out.

There isn't a clouddriver exception or crash in the logs, and both individual containers are green. The pod as a whole is not green however, since the metrics container can't get metrics from clouddriver.

### Steps to Reproduce:

Enable prometheus metrics, use `hal deploy apply`

**Comment by milesmatthias** [comment] 2019-06-07 17:28
Update -- I've narrowed this down to a misconfigured K8s v2 account. Our instance has about a dozen, and if I remove all of them and re-deploy, the clouddriver initialization process is able to finish and start listening on port 7002.

**Comment by milesmatthias** [comment] 2019-06-07 23:51
Update -- the actual issue with the timeout was that the cluster wasn't publicly available.

**Comment by maggieneterval** [comment] 2019-06-10 13:59
Thanks for the detailed report, Miles! We are working on the issue of Clouddriver failing on startup if one cluster/account is unreachable, going to close this one as a duplicate of https://github.com/spinnaker/spinnaker/issues/4407

**Closed by maggieneterval** 2019-06-10 13:59 UTC

**Comment by milesmatthias** [comment] 2019-06-10 15:24
Thanks, subscribed there!

(Also submitted https://github.com/spinnaker/clouddriver/pull/3769 to help debug the logs for this.)

**Comment by maggieneterval** [comment] 2019-06-10 16:25
Ah amazing, thanks Miles! :zap:
