### ISSUE TITLE
Cannot see details for deployment in deck (Cannot read property 'moniker' of null)

### ISSUE THREAD

**Issue by aldor007** [spinnaker/spinnaker#5760] opened 2020-05-12 20:59 UTC
### Issue Summary:
Unable to see details about deployment object in spinnaker UI. Please see screenshot below

![image](https://user-images.githubusercontent.com/2446168/81746042-1c63b580-94a6-11ea-87f1-6a32d1078af9.png)

```js
angular.js:14961 TypeError: Cannot read property 'moniker' of null
    at Function.buildManagerClusterTargets (clusterTargetBuilder.ts:42)
    at KubernetesServerGroupManagerDetailsController.configureEntityTagTargets (details.controller.ts:187)
    at KubernetesServerGroupManagerDetailsController.extractServerGroupManager (details.controller.ts:182)
    at details.controller.ts:47
    at angular.js:17330
    at angular.js:17378
    at Scope.$digest (angular.js:18514)
    at Scope.$apply (angular.js:18903)
    at angular.js:19207
    at completeOutstandingRequest (angular.js:6439) "Possibly unhandled rejection: {}"
```

### Cloud Provider(s):
Azure

### Environment:

spinnaker Version 1.20.1
Kubernetes - AKS

### Feature Area:
Deck/UI

### Description:

Getting console error when trying to load Kubernetes Deployment. ReplicaSet or Statefulset are working fine 

### Steps to Reproduce:

Go to infrastructure -> Clusters -> deployment

**Comment by maggieneterval** [comment] 2020-05-13 14:10
Thanks for reporting, @aldor007! Closing as a duplicate of https://github.com/spinnaker/spinnaker/issues/5754. This will be resolved in the next patch release of 1.20 (1.20.2), due to be released on Monday.

**Closed by maggieneterval** 2020-05-13 14:10 UTC
