### ISSUE TITLE
Print apache2 logs when gate fails to start

### ISSUE THREAD

**Issue by ashhwani** [spinnaker/spinnaker#5496] opened 2020-02-26 07:31 UTC
Issue Summary:
Print apache2 logs when gate fails to start

Cloud Provider(s):
AWS

Environment:
EKS / helm installation

Feature Area:
gate, logging, error handling

Description:
I recently was struggling to get gate configured properly (due to cert key strength), and had to:

modify the deployment to sleep
exec in
try to run the entrypoint by hand
find and view logs
Could we print the apache error logs if it errors out?

Thanks!

**Comment by maggieneterval** [comment] 2020-02-26 15:03
Closing as duplicate of https://github.com/spinnaker/spinnaker/issues/5495

**Closed by maggieneterval** 2020-02-26 15:03 UTC
