### ISSUE TITLE
Failed to create Load Balancer following Manage Traffic Guide

### ISSUE THREAD

**Issue by dpolicastro** [spinnaker/spinnaker#5572] opened 2020-03-13 22:56 UTC
### Issue Summary:
I'm trying to follow [this guide](https://www.spinnaker.io/guides/user/kubernetes-v2/traffic-management/) from the website but I'm getting an error.

The output from the logs:
```
[spin-orca-5897d6ddfb-mhk5q] 2020-03-13 22:53:15.318  INFO 1 --- [0.0-8083-exec-5] c.n.s.o.c.OperationsController           : [anonymous] requested task:
{
	"application": "spin-example",
	"name": "Deploy manifest",
	"stages": [{
		"cloudProvider": "kubernetes",
		"manifests": [{
			"kind": "Service",
			"apiVersion": "v1",
			"metadata": {
				"name": "my-service"
			},
			"spec": {
				"selector": {
					"app": "myapp"
				},
				"ports": [{
					"protocol": "TCP",
					"port": 80
				}]
			}
		}],
		"relationships": {
			"loadBalancers": [],
			"securityGroups": []
		},
		"moniker": {
			"app": "spin-example"
		},
		"account": "default",
		"manifestArtifactAccount": "kubernetes",
		"type": "deployManifest",
		"user": "[anonymous]",
		"refId": "0",
		"requisiteStageRefIds": []
	}],
	"trigger": {
		"type": "manual",
		"user": "anonymous",
		"parameters": {},
		"artifacts": [],
		"expectedArtifacts": [],
		"resolvedExpectedArtifacts": []
	},
	"origin": "deck"
}
```

This is the json output from the task:
```
{
  "id": "01E3HVD43GJZXHPA57K0X8EX73",
  "name": "Deploy manifest",
  "application": "spin-example",
  "status": "TERMINAL",
  "variables": [
    {
      "key": "exception",
      "value": {
        "exceptionType": "NullPointerException",
        "shouldRetry": false,
        "details": {
          "stackTrace": "java.lang.NullPointerException\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ManifestEvaluator.getManifests(ManifestEvaluator.java:108)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ManifestEvaluator.evaluate(ManifestEvaluator.java:102)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ResolveDeploySourceManifestTask.execute(ResolveDeploySourceManifestTask.java:43)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:129)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:378)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:127)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)\n\tat com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:126)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:208)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:67)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:84)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:93)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:73)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:59)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:201)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:87)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:72)\n\tat com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)\n\tat com.netflix.spinnaker.q.QueueProcessor$callback$1$1.run(QueueProcessor.kt:89)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
          "error": "Unexpected Task Failure",
          "errors": [
            
          ]
        },
        "operation": "resolveDeploySourceManifest",
        "timestamp": 1584368357632
      }
    },
    {
      "key": "relationships",
      "value": {
        "loadBalancers": [
          
        ],
        "securityGroups": [
          
        ]
      }
    },
    {
      "key": "cloudProvider",
      "value": "kubernetes"
    },
    {
      "key": "manifests",
      "value": [
        {
          "metadata": {
            "name": "my-service"
          },
          "apiVersion": "v1",
          "kind": "Service",
          "spec": {
            "selector": {
              "app": "myapp"
            },
            "ports": [
              {
                "protocol": "TCP",
                "port": 80
              }
            ]
          }
        }
      ]
    },
    {
      "key": "moniker",
      "value": {
        "app": "spin-example"
      }
    },
    {
      "key": "manifestArtifactAccount",
      "value": "kubernetes"
    },
    {
      "key": "user",
      "value": "[anonymous]"
    },
    {
      "key": "account",
      "value": "default"
    }
  ],
```

### Cloud Provider(s):
AWS/K8s

### Environment:
Spinnaker 1.19.0

### Feature Area:
Orca

### Additional Details
I installed Spinnaker via Helm, setup external Redis, and MySQL for Clouddriver.

**Comment by maggieneterval** [comment] 2020-04-08 15:54
Closing as a duplicate of https://github.com/spinnaker/spinnaker/issues/5596, for which a fix is included in the latest patch of Spinnaker 1.19.

Thanks!

**Closed by maggieneterval** 2020-04-08 15:54 UTC
Labels: provider/kubernetes-v2, sig/kubernetes
