### ISSUE TITLE
amazon-ebs: E: Unable to locate package hello-karyon-rxnetty

### ISSUE THREAD

**Issue by sameer-shukur** [spinnaker/spinnaker#1374] opened 2017-01-19 04:22 UTC
A descriptive title.

*Cloud Provider*

AWS

*Environment*

I am running Spinnaker using the Amazon images to deploy into AWS 

*Feature Area*

I am facing issue while baking image in Hello Deployment pipeline.

*Description*

amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 587de7bd-93d9-d4e7-d1fb-53894eb881e6
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-01839c3a6fcb2f91f
==> amazon-ebs: Waiting for instance (i-01839c3a6fcb2f91f) to become ready...
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Pausing 30s before the next provisioner...
==> amazon-ebs: Provisioning with shell script: /opt/rosco/config/packer/install_packages.sh
    amazon-ebs: repository=
    amazon-ebs: package_type=deb
    amazon-ebs: packages=hello-karyon-rxnetty=1-1
    amazon-ebs: upgrade=
    amazon-ebs: Ign http://us-west-1.ec2.archive.ubuntu.com trusty InRelease
    amazon-ebs: Get:1 http://us-west-1.ec2.archive.ubuntu.com trusty-updates InRelease [65.9 kB]
    amazon-ebs: Get:2 http://us-west-1.ec2.archive.ubuntu.com trusty-backports InRelease [65.9 kB]
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty Release.gpg
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty Release
    amazon-ebs: Get:3 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/main Sources [388 kB]
    amazon-ebs: Get:4 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/restricted Sources [5,888 B]
    amazon-ebs: Get:5 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/universe Sources [171 kB]
    amazon-ebs: Get:6 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/multiverse Sources [7,535 B]
    amazon-ebs: Get:7 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages [938 kB]
    amazon-ebs: Get:8 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/restricted amd64 Packages [16.4 kB]
    amazon-ebs: Get:9 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packages [392 kB]
    amazon-ebs: Get:10 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/multiverse amd64 Packages [14.0 kB]
    amazon-ebs: Get:11 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/main Translation-en [460 kB]
    amazon-ebs: Get:12 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/multiverse Translation-en [7,340 B]
    amazon-ebs: Get:13 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/restricted Translation-en [3,842 B]
    amazon-ebs: Get:14 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/universe Translation-en [208 kB]
    amazon-ebs: Get:15 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/main Sources [9,636 B]
    amazon-ebs: Get:16 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/restricted Sources [28 B]
    amazon-ebs: Get:17 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/universe Sources [35.3 kB]
    amazon-ebs: Get:18 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/multiverse Sources [1,898 B]
    amazon-ebs: Get:19 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/main amd64 Packages [13.3 kB]
    amazon-ebs: Get:20 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/restricted amd64 Packages [28 B]
    amazon-ebs: Get:21 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/universe amd64 Packages [43.2 kB]
    amazon-ebs: Get:22 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1,571 B]
    amazon-ebs: Get:23 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/main Translation-en [7,493 B]
    amazon-ebs: Get:24 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/multiverse Translation-en [1,215 B]
    amazon-ebs: Get:25 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/restricted Translation-en [28 B]
    amazon-ebs: Get:26 http://us-west-1.ec2.archive.ubuntu.com trusty-backports/universe Translation-en [36.8 kB]
    amazon-ebs: Get:27 http://us-west-1.ec2.archive.ubuntu.com trusty/main Sources [1,064 kB]
    amazon-ebs: Get:28 http://us-west-1.ec2.archive.ubuntu.com trusty/restricted Sources [5,433 B]
    amazon-ebs: Get:29 http://us-west-1.ec2.archive.ubuntu.com trusty/universe Sources [6,399 kB]
    amazon-ebs: Get:30 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
    amazon-ebs: Get:31 http://us-west-1.ec2.archive.ubuntu.com trusty/multiverse Sources [174 kB]
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/main amd64 Packages
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/restricted amd64 Packages
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/universe amd64 Packages
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/multiverse amd64 Packages
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/main Translation-en
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/multiverse Translation-en
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/restricted Translation-en
    amazon-ebs: Hit http://us-west-1.ec2.archive.ubuntu.com trusty/universe Translation-en
    amazon-ebs: Ign http://us-west-1.ec2.archive.ubuntu.com trusty/main Translation-en_US
    amazon-ebs: Ign http://us-west-1.ec2.archive.ubuntu.com trusty/multiverse Translation-en_US
    amazon-ebs: Ign http://us-west-1.ec2.archive.ubuntu.com trusty/restricted Translation-en_US
    amazon-ebs: Ign http://us-west-1.ec2.archive.ubuntu.com trusty/universe Translation-en_US
    amazon-ebs: Get:32 http://security.ubuntu.com trusty-security/main Sources [123 kB]
    amazon-ebs: Get:33 http://security.ubuntu.com trusty-security/universe Sources [47.3 kB]
    amazon-ebs: Get:34 http://security.ubuntu.com trusty-security/main amd64 Packages [573 kB]
    amazon-ebs: Get:35 http://security.ubuntu.com trusty-security/universe amd64 Packages [148 kB]
    amazon-ebs: Get:36 http://security.ubuntu.com trusty-security/main Translation-en [317 kB]
    amazon-ebs: Get:37 http://security.ubuntu.com trusty-security/universe Translation-en [87.2 kB]
    amazon-ebs: Fetched 11.9 MB in 4s (2,719 kB/s)
    amazon-ebs: Reading package lists... Done
    amazon-ebs: Reading package lists... Done
    amazon-ebs: Building dependency tree
    amazon-ebs: Reading state information... Done
    amazon-ebs: E: Unable to locate package hello-karyon-rxnetty
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 100

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Script exited with non-zero exit status: 100

==> Builds finished but no artifacts were created.

I think the issue I am facing is because of 
**amazon-ebs: repository= **
is empty. Can anybody help me where i have to set my repository details so that it can take .deb
package while baking.

**Comment by duftler** [comment] 2017-01-19 12:25
This is the attribute you'll need to configure to point at your deb repo: https://github.com/spinnaker/rosco/blob/master/rosco-web/config/rosco.yml#L20

You may also find this post on troubleshooting bakes helpful: https://medium.com/@duftler/troubleshooting-spinnaker-rosco-bakes-c0c600aa3598#.mfn45dkz0

**Comment by duftler** [comment] 2017-01-20 17:03
Going to close this as it's a config question and not a bug. Please re-open if there is an ongoing issue.

**Closed by duftler** 2017-01-20 17:03 UTC
