### ISSUE TITLE
Cannot create Load Balancer as part of pipeline execution

### ISSUE THREAD

**Issue by vjames-bmc** [spinnaker/spinnaker#760] opened 2016-02-23 23:22 UTC
If you want to run a pipeline and deploy the application to different environments, then you have to manually pre-create the load balancers where they are going to be deployed. It would be very useful if there is a stage for creating load balancers.

**Comment by bfarrell** [comment] 2016-02-24 21:18
We are looking at two use cases for this.  The first would be a longer pipeline where the entire infrastructure (lb,asg) would be spun up, tested against and then spun down.  So, it would be something that was reused.  We could potentially add a random or date stamp to the detail to ensure unique lb names.  The other use case is for a self service type pipeline where the lb detail would be parameterized to utilize an input from the user invoking it.  We were hoping to make this a first class stage to help our end users build out some of their own pipelines.

Based on a conversation with @tomaslin in slack, we will also be looking to create security groups as part of this issue.

**Comment by duftler** [comment] 2016-02-24 21:32
+1

**Comment by tomaslin** [comment] 2016-02-24 21:46
+1

**Comment by vjames-bmc** [comment] 2016-02-26 02:12
@tomaslin @duftler Here is a preview of the "Create Load Balancer" stage screen. Comments?, Suggestions?...

![pasted image at 2016_02_25 06_04 pm](https://cloud.githubusercontent.com/assets/16142228/13341165/1891c41a-dbeb-11e5-9e4d-f17bdde877c7.png)

**Comment by tomaslin** [comment] 2016-02-26 16:26
@vjames-bmc You want the screen to be more similar to the deploy screen rather than just embedding the create load balancer screen. If we're going to add this stage, it should be able to create more than one load balancer at a time and show each load balancer you're creating as a list. Also, it should be able to take attributes from an existing load balancer and use as a template.

**Comment by vjames-bmc** [comment] 2016-02-26 17:53
@tomaslin Thanks for the comments. That helps.

**Comment by tomaslin** [comment] 2016-02-26 18:24
cc @anotherchrisberry

**Comment by anotherchrisberry** [comment] 2016-02-26 20:06
I have mixed feelings about this feature request - I'll try to write something up in the next day or so explaining my concerns. @vjames-bmc can you hold off on further work until I provide some feedback here?

**Comment by anotherchrisberry** [comment] 2016-02-27 03:52
First off, I want to apologize for not chiming in earlier. I wasn't anticipating anyone starting work on this issue so quickly, but it looks like you've started in on it, which is great. I'd like to clarify why this functionality does not exist currently, why I'm nervous about adding the functionality, and what I'd expect it to look like.

### Why this doesn't exist right now
Frankly, engineers at Netflix haven't asked for it. We've had requests from some folks to include the ability to create a load balancer at the same time they're creating a new server group, but that's almost always a request from someone who is first learning how Spinnaker works. The problem is that we consider load balancers (and security groups) durable infrastructure components, not stateless disposable components (i.e. running instances). With load balancers, we attach DNS records. Security groups connect to other security groups. Both load balancers and security groups span versions of the same code deployed in instances.

Almost always, these are components we configure once. Periodically, we change security groups or certificates. But, as far as I know, nobody here creates new ones via scripts (or pipelines).

### Why I'm nervous about this feature
There are two main concerns I have:
 1. It's a feature we at Netflix probably won't use. But, since we're the de facto maintainers of the AWS functionality, we're on the hook for keeping it working as we update components and functionality throughout Spinnaker. When we break things right now (which we do frequently), we hear about it quickly (and very loudly) from our internal users, and we get it fixed. If we break this, the likelihood of it propagating out to other users is much greater. So it needs to include a thorough suite of tests.

 2. It's going to add complexity to a number of components that are already really messy and complex, and were never written or designed with this functionality in mind. That's not a reason not to do it, just something to consider when diving into this.

### What should the implementation look like?

Parts of this are going to be much simpler than what we did to get server group modals working for both pipelines and one-off deployments. You don't have to worry about images and instance types and all the complication of deciding whether or not to even show those fields and what other data sources need to be filtered based on those selections. My guess is there won't be that much modification to what's in the CreateLoadBalancer controller in its current form.

You'll need to make it opt-in per provider to start. If you look at the code behind the "Create Load Balancer" button, you should get an idea how to hook into existing functionality. It probably makes sense to put a feature flag into each provider's "loadBalancers" config block (in, e.g. aws.module.js) to declare that it supports "pipelineEnabled" or something.

Like Tomas said, you'll want this to look like the Deploy stage, allowing multiple load balancers to be created by the stage, and you'll want to start with a template selection, which just pre-populates everything in the modal from an existing load balancer. You can probably steal much of the code from what we did with the server group modal, only this will be simpler, since you don't need to pick the latest version or warn the user about which fields will and won't be copied over (since they'll all be copied over).

You are going to need to decide what to do about name collisions. If the load balancer already exists, should the pipeline fail? Or should we perform an upsert operation to make it look like what's configured? Or should that option be configurable?

You'll want to figure out up front how to handle this in the server group deployment configuration. How does a user pick these new load balancers? My feeling is you'd add a widget to the load balancers section of the deploy stage to let users pick the load balancer or load balancers that are created upstream. Consider how you're going to filter the options - some users will have parameterized the region or account. Don't worry too much about this, since we frankly do a miserable job throughout the pipeline configuration of handling parameterized fields (we plan to address this in earnest next quarter). But if you handle it now, you'll end up with a much more useful stage.

I can't stress this last bit enough: it is *very, very* important to get solid test coverage around this. You're going to have to write tests anywhere the code happens to branch or do things differently based on the purpose (create vs. edit vs. pipeline config) of the modal. There aren't a lot of tests on this particular controller right now, unfortunately. But we'll need good coverage, or we'll break it and we won't realize it. 

I'm happy to help with design and provide feedback as you work through this - don't hesitate to reach out!

**Comment by vjames-bmc** [comment] 2016-03-01 02:15
@anotherchrisberry Thanks for the input. It is really helpful. I will discuss with our team and update you.

**Comment by vjames-bmc** [comment] 2016-03-02 18:52
@anotherchrisberry We will start with some unit tests and have some incremental check-ins to get your feedback. Thanks for all your help.

**Comment by anotherchrisberry** [comment] 2016-03-02 18:55
Awesome, thanks!

**Comment by duftler** [comment] 2016-03-03 16:10
Sorry for chiming in so late on this issue. @anotherchrisberry's comments make a lot of sense, esp. the concept of 'durable' vs. 'disposable' components. Almost feels like the stages that stray into the 'durable' camp could have some admonitions to the user (e.g. describing the security implications of creating/modifying those kinds of resources, especially in a pipeline triggered in the background).

That writeup would probably make for a useful blog post or stackoverflow answer.

**Comment by vjames-bmc** [comment] 2016-03-08 19:44
@anotherchrisberry I will be using the existing LB modal to add the load balancers to the stage. Currently the dialog box has only submit action, and it directly creates the load balancer. I am adding an option to just return the loadbalancer object from the modal. For that, I will be adding a parameter "isAdd" (just like existing "isNew") and based on that the title will say "Add Load Balancer" and the button will be OK and it will just return the loadbalancer object. Am I on the right track? Please advise.

**Comment by anotherchrisberry** [comment] 2016-03-08 20:39
That sounds right - the only thing I'd change is to make the button say "Done" when editing an existing load balancer configuration and "Add" when creating a new load balancer configuration. This is consistent with the cluster configuration.

**Comment by vjames-bmc** [comment] 2016-03-08 21:48
@anotherchrisberry one more question. Which one do you prefer - re-using the submit-button for add by changing the label, or, adding an addButton.directive (in core.modal.buttons) and use that if isAdd flag is true?

**Comment by vjames-bmc** [comment] 2016-03-08 23:35
Thanks @anotherchrisberry I have made the changes you suggested and sent a PR #2066 Could you take a look when you get a chance. Thanks

**Comment by vjames-bmc** [comment] 2016-03-10 23:04
@anotherchrisberry First of all, thanks for the detailed What should the implementation look like? section above.You mentioned (above) about having a feature flag like "pipelineEnabled" in the "loadbalancers" config block. I suppose the stage registration ( pipelineConfigProvider.registerStage() ) should be done

**Comment by anotherchrisberry** [comment] 2016-03-13 04:16
@vjames-bmc Good questions. Sorry for the late reply.

For now, let's add a field to the `feature` block in settings.js and call it `infrastructureStages`. We can use that field for create/destroy load balancers/security groups, rather than having separate fields. There's talk of radically reworking the build to make all of this easier, but it's down the road a ways; for now, exactly what you're saying is right - only register the stage if that flag is true.

Let's make it look like the deploy stage, with a generic table listing all the load balancers. You can look at the `loadBalancerDetail.html` and `loadBalancerDetails.html` files to get a sense of what the common fields are between the four providers (AWS, Azure, Cloud Foundry, Google) that support load balancers via Spinnaker right now.

**Comment by vjames-bmc** [comment] 2016-03-14 19:54
@anotherchrisberry No Problem. 
The settings.js flag seems to be very useful. I will add the falg and set it to false by default so that most of the users won't get affected.
BTW, I have sent a PR for the editLoadBalancer modal to support editing in the stage. This is similar to the previous change which was for the createLoadBalancer modal. Please take a look when you get a chance.
https://github.com/spinnaker/deck/pull/2089

**Comment by vjames-bmc** [comment] 2016-03-14 22:42
@anotherchrisberry Please find attached a screenshot of the "Create Load Balancer" stage UI. Does it look ok? I am not sure whether Subnet is valid for GCE and CF. Are they? I couldn't find it in loadB
The stage type key that I am planning to use is "upsertLoadBalancers". The stage json will have a property called loadBalancers: [ ] which is the list of individual LB json. Is that OK, or do you prefer it differently?
![lb](https://cloud.githubusercontent.com/assets/16142228/13762310/52089340-e9fb-11e5-94ed-a0b2123c6105.PNG)

**Comment by anotherchrisberry** [comment] 2016-03-15 05:21
@vjames-bmc looks good! 

It makes sense to me to keep subnet in place - there is code in the deploy stage you can probably use as a template: 
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.html

**Comment by bfarrell** [comment] 2016-03-16 18:51
@tomaslin Just wanted to close the loop on the Create Security Group stage.  Based on our conversation, it was something that we were going to do in order to get Create Load Balancer accepted but it seems there was some differences of opinions on whether or not it should be done in a slack discussion between @cholin-bmc and @ajordens.  We are still happy to do it if you guys want it, but its not something we need for our use cases at this point.  Let us know the consensus there and whether to proceed in creating it.

**Comment by vjames-bmc** [comment] 2016-03-16 20:38
@anotherchrisberry I have submitted a PR for the feature - https://github.com/spinnaker/deck/pull/2098
Also @peterpd has added a PR for the ORCA changes - https://github.com/spinnaker/orca/pull/763

**Comment by peterpd** [comment] 2016-03-17 17:45
@anotherchrisberry who would you recommend to review ORCA changes? - spinnaker/orca#763

**Comment by anotherchrisberry** [comment] 2016-07-12 13:56
Closing this issue - the stage has been created.

**Closed by anotherchrisberry** 2016-07-12 13:56 UTC

**Comment by cristim** [comment] 2017-08-07 15:59
I'm not sure if this is the best place to report this, but I've tried this recently and it seems the load balancer is created when configuring the pipeline, instead of on each pipeline execution. Was that the intention of this?

**Comment by thdghgns** [comment] 2018-03-23 08:25
@SteveEasley set variable "infrastructureStages=true" in settings.js. i copied /opt/deck/html/settings.js to ~/.hal/default/profiles/settings.js and set the variable "infrastructureStages=true". now i can use this stage in pipeline.

**Comment by rverma-nikiai** [comment] 2018-08-24 02:04
@anotherchrisberry Wondering if this is available for kubernetes V1 deployments also, running 1.9.0 and I could not find it.
This is pretty much required when we want to create a new service using kubernetes and it only have create servergroup stage.

**Comment by anotherchrisberry** [comment] 2018-08-24 04:53
@rverma-nikiai I would defer to @lwander or @danielpeach - I don't know if there is a corresponding pipeline stage for k8s (but guessing not, per your comment)

**Comment by lwander** [comment] 2018-08-24 12:50
This isn't available for the v1 provider, but we're definitely open to someone adding it as a feature.

**Comment by anup13kumar** [comment] 2018-10-25 07:47
@anotherchrisberry 
I have updated my clouddriver version to 2.89.0. After updating clouddriver, target group showing [obect:object] not listing my target groups

Please let me know what  could be the issue.

**Comment by hridyeshpant** [comment] 2020-10-28 01:21
I am getting an error when trying to add the "Create load balancer" stage in the pipeline. I am using the latest Spinnaker release 1.23. i see other people also facing the same issue https://github.com/spinnaker/spinnaker/issues/2819
```
Error: One of component or template or templateUrl options is required.
    at Object.$modal.open (ui-bootstrap-tpls.js:4476)
    at Object.$delegate.open (uibModalRejections.ts:12)
    at createLoadBalancerStage.js:38
    at angular.js:17330
    at angular.js:17378
    at Scope.$digest (angular.js:18514)
    at angular.js:18835
    at completeOutstandingRequest (angular.js:6439)
    at angular.js:6718 "Possibly unhandled rejection: {}"
```
Any idea what is the possible fix for this. this is blocking to automate of our pipeline.

**Comment by hridyeshpant** [comment] 2020-11-03 03:52
any update on this issue? Just wondering how others are creating LB and Targetgroups as part of automation. 
If this feature not working, either this needs to be removed and need a fix
