### ISSUE TITLE
Docker registry pipeline triggers not enabled if pipeline template trigger has template variables

### ISSUE THREAD

**Issue by jack0** [spinnaker/spinnaker#4714] opened 2019-08-02 19:59 UTC
### Issue Summary:
Pipeline instances of a pipeline template with a Docker registry trigger that takes as input a template variable for the repository name don't see image tags for manual execution until you click into the pipeline itself.

Cloud Provider(s):
n/a

### Environment:
Spinnaker 1.14 deployed to baremetal k8s cluster

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Pipelines/UI

### Description:
We have a pipeline template with a single docker registry trigger. The trigger repository name is a template variable. When we create a pipeline instance with the template and input the variable for the repository name, the pipeline doesn't seem to be enabled in the UI unless you manually click into it (you don't have to edit anything). This means that if you try to do a manual execution, it will never see the image tags.

### Steps to Reproduce:
Create a pipeline template with a Docker registry trigger and set the repository as a template variable. Create a pipeline from that template and input a repository that exists in your registry. If you try to immediately manually execute the template, you will not see tags. Click into the pipeline and click back. Try the manual execution again, this time you will see tags.

**Comment by louisjimenez** [comment] 2019-08-02 20:57
Sounds similar to https://github.com/spinnaker/spinnaker/issues/4565, what version of 1.14.x is this?

**Comment by jack0** [comment] 2019-08-05 12:26
I'm running 1.14.9, would it be fixed in a more recent version?

**Comment by jack0** [comment] 2019-08-05 14:01
I just updated to 1.15.1 and this problem still persists. I can see that the start manual execution bug not detecting image tags is fixed, but the pipeline trigger is not enabled. If I click into the pipeline and out of the pipeline it will cause the pipeline to be enabled.

**Comment by neelimamanubolu** [comment] 2019-08-14 11:54
I have started working on this.

**Comment by neelimamanubolu** [comment] 2019-08-19 11:34
Hi, @jack0  , tested the above issue in latest version (1.15.1), not able to reproduce. Please finnd below screen shots for your reference : 

![Screenshot from 2019-08-19 17-02-02](https://user-images.githubusercontent.com/48236703/63262355-556a5300-c2a3-11e9-8501-e12c731f8a3b.png)
![Screenshot from 2019-08-19 17-02-15](https://user-images.githubusercontent.com/48236703/63262361-57ccad00-c2a3-11e9-93f7-db1176b0ea4d.png)

Pleaselet me know If I miss anything..

**Comment by louisjimenez** [comment] 2019-08-19 21:43
@jack0 @neelimamanubolu that's correct, 1.15.1 was patched to render the tag.

As for the "Trigger Enabled" text, it is not rendered for templated pipelines. Doing so would require Orca to schedule a plan tasks for each templated pipeline and would impact performance. When the text does appear, it is due to the plan being loaded and cached from visiting the configuration view. It does make for inconsistent UX so I am opening an issue for the label. 

The trigger itself should be enabled and work regardless of the UI rendering the helper text. Let me know if you see otherwise.

**Comment by louisjimenez** [comment] 2019-08-19 21:43
Issue for text rendering: https://github.com/spinnaker/spinnaker/issues/4769

**Comment by neelimamanubolu** [comment] 2019-08-20 04:48
@jack0, kindly close the above issue.

**Comment by louisjimenez** [comment] 2019-08-20 14:29
@neelimamanubolu I can close it. @jack0 feel free to re-open if we missed something or to comment on the [issue](https://github.com/spinnaker/spinnaker/issues/4769) for the "Trigger Enabled" text.

**Closed by louisjimenez** 2019-08-20 14:29 UTC
Labels: pipelines/templates, sig/spinnaker-as-code

**Comment by jack0** [comment] 2019-08-20 14:32
Thanks for the clarification @louisjimenez
