### ISSUE TITLE
Unable to use kubernetes manifest based deployment

### ISSUE THREAD

**Issue by amitmindstix** [spinnaker/spinnaker#2641] opened 2018-04-10 13:10 UTC
Spinnaker 1.6.0 deployed in Local mode.
When I try to use Deploy (manifest) stage, I see the Account dropdown is empty - so I am stuck. 
I can very well use normal Deploy stage though and account dropdown shows accounts.

If it is relevant to know - I am using Azure AKS to set this up and on top of this installed Spinnaker on single VM as per instructions from Spinnaker.io (Local install)

**Comment by sbwsg** [comment] 2018-04-10 14:13
Hi, thanks for the issue report!  Could you include here the output of `hal config` with any sensitive information removed?  Additionally it would be helpful to see the output of the `/credentials` endpoint from clouddriver.  Getting this information from a local install would look something like this:

```
curl localhost:7002/credentials
```

**Comment by amitmindstix** [comment] 2018-04-10 15:02
I may be wrong.. but seems the primaryAccount property seems to be the issue in credentials API output. It shows false whereas it should be true for registry and cloud driver account (as per hal config)

**Comment by sbwsg** [comment] 2018-04-10 15:15
The `Deploy (manifest)` stage is only supported by the Kubernetes v2 provider.  The only kubernetes account I see in your config is a v1 account, `my-aks1-account`.  So it appears you don't have a v2 account configured.

Take a look at the instructions here: https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#adding-an-account and add a v2 account.  Once you've followed those, restart your spinnaker deployment with `hal deploy apply` and you should then see the v2 account appear in the `Deploy (manifest)` stage account dropdown.  Let me know how it goes!

**Comment by amitmindstix** [comment] 2018-04-10 15:27
Oh. I did the change and I can see the account now.
But now when I try running a Deploy with manifest, I see below error -

Exception ( Monitor Deploy )
java.lang.NullPointerException at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.KubernetesDeployManifestOperation.operate(KubernetesDeployManifestOperation.java:112) at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.KubernetesDeployManifestOperation.operate(KubernetesDeployManifestOperation.java:51) at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:89) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) at groovy.lang.Closure.call(Closure.java:414) at groovy.lang.Closure.call(Closure.java:408) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82) at java_util_concurrent_Callable$call.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:88) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) at groovy.lang.Closure.call(Closure.java:414) at groovy.lang.Closure.call(Closure.java:408) at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:75) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

The manifest I used is as below -
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-persistent-storage
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/data01"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-persistent-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo

**Comment by sbwsg** [comment] 2018-04-10 16:06
Ah, this problem has been fixed in this PR: https://github.com/spinnaker/clouddriver/pull/2456

That commit hasn't yet made it into a mainline Spinnaker release but there are a couple of options available.

The first is to use the master-latest-unvalidated version of Spinnaker:

```
hal config version edit --version master-latest-unvalidated
hal deploy apply
```

The second option is to use a preview build that we prepared for introducing Kayenta and canary analysis.  First you'll need to update halyard with one of these commands: `sudo update-halyard` or `sudo apt-get update && sudo apt-get install halyard` and then you'll need to run `hal config version edit --version canary-preview` followed by `hal deploy apply`.  More information about this release can be found here: https://www.spinnaker.io/setup/canary/

Finally, if you're unable to try either of these versions of spinnaker then we plan to release Spinnaker 1.7.0 in about 3 weeks, which will include the PR mentioned above.

**Comment by eboumendil** [comment] 2018-04-13 01:55
I have a similar issue when I try to use Deploy (manifest) stage, I see the Account dropdown is empty. However, I am able to create a new Server Group using a manifest.

Here an output of `curl localhost:7002/credentials`

```
[ {
  "accountType" : "quay",
  "challengeDestructiveActions" : false,
  "cloudProvider" : "dockerRegistry",
  "environment" : "quay",
  "name" : "quay",
  "permissions" : { },
  "primaryAccount" : false,
  "providerVersion" : "v1",
  "requiredGroupMembership" : [ ],
  "skin" : "v1",
  "type" : "dockerRegistry"
}, {
  "accountType" : "k8s-phx2",
  "challengeDestructiveActions" : false,
  "cloudProvider" : "kubernetes",
  "environment" : "k8s-phx2",
  "name" : "k8s-phx2",
  "primaryAccount" : false,
  "providerVersion" : "v2",
  "requiredGroupMembership" : [ ],
  "skin" : "v2",
  "type" : "kubernetes"
}, {
  "accountId" : "XXXXXX",
  "accountType" : "my-aws-account",
  "challengeDestructiveActions" : true,
  "cloudProvider" : "aws",
  "environment" : "my-aws-account",
  "name" : "my-aws-account",
  "permissions" : { },
  "primaryAccount" : true,
  "providerVersion" : "v1",
  "requiredGroupMembership" : [ ],
  "skin" : "v1",
  "type" : "aws"
```

**Comment by amitmindstix** [comment] 2018-04-13 02:13
@eboumendil   Your account list shows only v1 accounts. As mentioned in above thread.. you need to add v2.

**Comment by amitmindstix** [comment] 2018-04-13 02:24
Sorry Imissed that one. Looks like a different issue. In my case I could see the account in dropdown after adding a v2 account. I hope you tried usual hal deploy apply and cache refresh.

**Comment by eboumendil** [comment] 2018-04-13 06:40
I am seeing an error related to an ELB named `github-enterprise-public` that I am not seeing in my AWS dev account. I do see the Deploy(manifest) stage in my dev account but not in my prod account. It may not be related but I am running Github enterprise in prod and not in dev. Also, if I create a new Server Group, I can copy/paste a manifest and it will create all the resources in my kubernetes cluster according to the manifest, but still no deploy(manifest) stage.
```
clouddriver.log:2018-04-13 06:25:18.104  INFO 28489 --- [cutionAction-23] com.amazonaws.latency                    : ServiceName=[AmazonElasticLoadBalancing], AWSErrorCode=[LoadBalancerNotFound], StatusCode=[400], ServiceEndpoint=[https://elasticloadbalancing.us-west-2.amazonaws.com], Exception=[com.amazonaws.services.elasticloadbalancing.model.LoadBalancerNotFoundException: There is no ACTIVE Load Balancer named 'github-enterprise-public' (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: LoadBalancerNotFound; Request ID: 6f513074-3ee3-11e8-8c87-93cc06e70c9a)], RequestType=[DescribeInstanceHealthRequest], AWSRequestID=[6f513074-3ee3-11e8-8c87-93cc06e70c9a], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=1, RequestCount=1, Exception=1, HttpClientPoolLeasedCount=0, RequestMarshallTime=[0.003], ClientExecuteTime=[27.251], HttpClientSendRequestTime=[0.051], HttpRequestTime=[7.898], RequestSigningTime=[0.09], CredentialsRequestTime=[0.002, 0.002], HttpClientReceiveResponseTime=[7.765],
```
Any idea?

**Comment by cloudvar** [comment] 2018-08-06 23:48
I added v2 account in spinnaker:

`hal config provider kubernetes account add my-k8s-v2-account \
--provider-version v2 \
--context $(kubectl config current-context)`
Also enabled artifacts:

`hal config features edit --artifacts true`
I can see v2 enabled when I go to server-groups and try to create one and it shows v1 or v2 but I dont see it in pipeline under: `Add stages`.When I run

`curl spin-clouddriver.spinnaker:7002/credentials I can see:  {
        "accountType": "aur-prod-k8s-v2-account",
        "challengeDestructiveActions": false,
        "cloudProvider": "kubernetes",
        "environment": "aur-prod-k8s-v2-account",
        "name": "aur-prod-k8s-v2-account",
        "primaryAccount": false,
        "providerVersion": "v2",
        "requiredGroupMembership": [],
        "skin": "v2",
        "type": "kubernetes"
    }`

Any suggestions

**Comment by lwander** [comment] 2018-08-07 16:27
I'm going to close this as a dupe of https://github.com/spinnaker/spinnaker/issues/3133 since that issue is pointing at the most recent release (1.6.0 is not actively being supported anymore)

**Closed by lwander** 2018-08-07 16:27 UTC
Labels: component/deck, provider/azure, provider/kubernetes-v2
