### ISSUE TITLE
Pipeline execution view continues polling in background tabs

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#4572] opened 2019-06-27 21:30 UTC
### Issue Summary:
The pipeline execution page in Deck continues polling even though it is in a background tab

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
UI/Deck/Pipelines
@spinnaker/ui-ux-team

### Description:
We have noticed increased load in our clusters CloudDriver API servers as more users login to the system, but are not actively using the system. Upon further investigation it seems a large number of requests were coming in for endpoints which users were not actively using. The UI appears to be polling even when it is inside of a unfocused tab. 

### Steps to Reproduce:
1.) Go to pipeline page 
2.) open up browser devtools, go to network tab
3.) navigate to another tab
4.) come back to tab and you will see it has continued polling even in the background tab

**Comment by maggieneterval** [comment] 2019-07-10 15:50
Hey @perek! So far I haven't been able to reproduce this one. I am:

- Opening the pipelines executions page (`/applications/{application_name}/executions`)
- Clearing the Network tab and immediately navigating to another tab
- Waiting 5-10 minutes
- Going back to the pipelines executions page and checking the timestamp on the headers of the oldest request

The oldest request is always from the same minute that I navigated back to the page. Maybe the polling you noticed only happens when you leave a tab open for longer than 5-10 minutes? I will try leaving one in the background overnight tonight to test this out. I also asked @anotherchrisberry at the UI SIG if Netflix had experienced any issues with polling in background tabs, but if I'm remembering correctly he said they had not and that all of the polling requests should be hooking into the Page Visibility API.

**Comment by anotherchrisberry** [comment] 2019-07-10 15:57
Just to clarify: we're talking about browser tabs here, right? Not the "tabs" within the Spinnaker UI?

If it's the latter, e.g. you're seeing polling after navigating to the clusters view, or tasks view, you might be seeing the running executions data getting refreshed. 

Spinnaker's UI does poll for running tasks and pipelines whenever an application is open, regardless of which tab is open. You'll see those requests end with a query string that looks like `statuses=RUNNING,SUSPENDED,NOT_STARTED`.

That data is used to put the little badge on the navigation elements indicating how many active tasks/pipelines are running. It's also used to add an indicator to the clusters view when there is a task or pipeline operating on a server group.

**Comment by maggieneterval** [comment] 2019-07-10 16:25
Thanks for the speedy reply, Chris! I believe we're talking about browser tabs, but I'll let @perek confirm.

**Comment by maggieneterval** [comment] 2019-07-18 19:43
Hey @perek, going to close this one for now, but please feel free to reopen if you are able to note any unexpected background requests and I can definitely investigate further!

**Closed by maggieneterval** 2019-07-18 19:43 UTC
Labels: bug, sig/ui-ux, ui
