### ISSUE TITLE
Project configuration dialogue crashes since 1.17.0

### ISSUE THREAD

**Issue by lukmy** [spinnaker/spinnaker#5221] opened 2019-12-11 08:23 UTC
### Issue Summary:

When upgrading from 1.16.3 to 1.17.0, project creation dialogue will crash when clicking `add cluster` button

### Cloud Provider(s):

- kubernetes v2
- cluster version: 1.13.2

### Environment:

- spinnaker: 1.17.0, 1.17.2
- private kubernetes cluster

### Feature Area:

- UI

### Description:

Chrome console error:

![image](https://user-images.githubusercontent.com/1225713/70603573-cb6b3f00-1c31-11ea-8d4e-062e64b19f97.png)

Chrome debugger:

![image](https://user-images.githubusercontent.com/1225713/70603674-02d9eb80-1c32-11ea-9dde-db400847b724.png)

Each element in the array `clusters` should include a field `applications` and `account`, but it lacks.

Everything alright for 1.16.3

### Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1225713/70603545-babac900-1c31-11ea-9f6d-219d7330086e.png)

**Comment by lukmy** [comment] 2019-12-11 08:36
I rollback version of deck to `2.12.2-20191014135540` (deck version in 1.16.3), no error occued.

**Comment by ezimanyi** [comment] 2019-12-11 15:19
Thanks for reporting this! Looks like this is a duplicate of #5221, which was fixed in spinnaker/deck#7673 and will be released in Spinnaker 1.17.4.

**Closed by ezimanyi** 2019-12-11 15:19 UTC

**Comment by lukmy** [comment] 2019-12-12 07:06
Thanks!
