### ISSUE TITLE
spinnaker 1.19.x does not work with github web hook 

### ISSUE THREAD

**Issue by wli66666** [spinnaker/spinnaker#5647] opened 2020-04-07 06:07 UTC
### Issue Summary:
github trigger hook does not work for spinnaker 1.19.4

### Cloud Provider(s):
aws

### Feature Area:
Github trigger 

### Description:
I upgraded spinnaker from 1.17 to 1.19 ,and the github does not work any more. We set up the github trigger as described here (seesion: Trigger a Pipeline with a Github Commit) : https://docs.armory.io/spinnaker-user-guides/github/ 

### Steps to Reproduce:
use hal 1.33.0 to config spinnaker 1.19.4 

### Additional Details:

<img width="865" alt="Screen Shot 2020-04-06 at 11 04 00 PM" src="https://user-images.githubusercontent.com/51767083/78635590-6defa380-785b-11ea-907e-dedb33790c8d.png">

---

I was able to find the EventID from github side, but not sure where should be trace down to after that
### Log detail in echo:
c.n.s.e.controllers.WebhooksController   : Webhook git:github:[ref:refs/heads/master, before:0c4f78bcb914464b32dc919760aff948cb7e205d, after:362a4bcbbf48581b390a9a9648e2fc6f813cf809, repository:[id:1094, node_id:MDEwOlJlcG9zaXRvcnkxMDk0, name:inf-nagios, full_name:wli/inf-nagios, private:false, owner:[name:wli, email:wli@gmail.com, login:wli, id:172, node_id:MDQ6VXNlcjE3Mg==, avatar_url:https://github.dev.pure.com/avatars/u/172?, gravatar_id:, url:https://github.dev.pure.com/api/v3/users/wli, html_url:https://github.dev.purestorage.com/wli, followers_url:https://github.dev.pure.com/api/v3/users/wli/followers, following_url:https://github.dev.pure.com/api/v3/users/wli/following{/other_user}, gists_url:https://github.dev.pure.com/api/v3/users/wli/gists{/gist_id}, starred_url:https://github.dev.pure.com/api/v3/users/wli/starred{/owner}{/repo}, subscriptions_url:https://github.dev.pure.com/api/v3/users/wli/subscriptions, organizations_url:https://github.dev.pure.com/api/v3/users/wli/orgs, repos_url:https://github.dev.pure.com/a

**Comment by wli66666** [comment] 2020-04-07 08:52
I found this in the echo log :  Received GitEvent from Github without secure signature for trigger configured with a secret 

any recommendation for what I should change for it ? we seems didn't have this issue with spinnaker 1.17

**Comment by gregjones** [comment] 2020-04-07 13:01
This seems a duplicate of #5645

**Comment by maggieneterval** [comment] 2020-04-07 13:47
Yes, closing this since it is a duplicate of #5645

**Closed by maggieneterval** 2020-04-07 13:47 UTC
