### ISSUE TITLE
GCP load balancers can't be updated after creation

### ISSUE THREAD

**Issue by xordspar0** [spinnaker/spinnaker#1717] opened 2017-06-05 19:04 UTC
I am creating load balancers in GCP.

### Description

Google does not allow load balancers to be changed after creation. As such, I would expect either
  1. that Spinnaker would destroy load balancers and create new ones when I try to edit them,
  2. that Spinnaker would not allow me to attempt to edit load balancers, or
  3. at *least* some error message should be shown when updating the load balancer that the changes can't be applied.

Instead, the current behavior is to allow me to edit a load balancer, go through the motions of the task, and report that the operation was successful. In fact, the load balancer remains in its original configuration with no changes.

### Steps to Reproduce

1. Create a new load balancer in Spinnaker. Give the load balancer default settings and some open ports.
2. Open the edit interface from Load Balancers -> Load Balancer Actions -> Edit Load Balancer
3. Change the ports that the load balancer listens on.
4. Click update and watch the task progess.
5. Verify that the ports have changed in Spinnaker and/or the Google Cloud console. Note that the settings have not been changed.

/cc @edwinavalos @varikin @duftler @jtk54

**Comment by jtk54** [comment] 2017-06-05 19:39
Trying to repro -- which type of GCE load balancer was this on?

**Comment by xordspar0** [comment] 2017-06-05 19:43
I reproduced this with an internal load balancer that listened on TCP ports.

**Comment by jtk54** [comment] 2017-06-05 20:27
Ok I reproduced this for an ILB in my project.

We made a decision when implementing the upsert operations that forwarding rules (basically IPs and ports) should not be updated after creation because there is no good story for updating. This was not enforced in the ILB upsert UI (you can still modify the fields).

> no good story for updating

What I mean by this is: if you want to change something about your forwarding rule (ports, IP, protocol) we _have_ to delete and recreate the forwarding rule. This has the effect of *possibly changing the ephemeral IP* of the forwarding rule. For external-facing load balancers, this is unacceptable. To prevent this, we simply made firewall rules read-only after creation and didn't include the UI changes for ILBs.

We can discuss relaxing this constraint on ILBs since they are not external-facing; however, for the time being I think the immediate change needed is to disallow this from the UI so there is no confusion.

An immediate workaround is for you to create the ILB and make it listen on all the ports you will use later on, else create a new ILB with the new set of ports.

**Comment by varikin** [comment] 2017-06-05 20:39
I will check with what would be the best answer for us, but at the least, not offering an update option which will fail would be good.

**Comment by jtk54** [comment] 2017-06-05 20:41
Initial UI fix: https://github.com/spinnaker/deck/pull/3790.

**Comment by kholloway** [comment] 2017-06-06 14:24
ILB ports are updatable in the Google web console manually without delete/recreate like HTTP LB's. IMHO Spinnaker should just properly update the ports instead of disabling what would be an otherwise  usable feature?

**Comment by jtk54** [comment] 2017-06-06 15:03
Can you provide some screenshots of successfully editing the ports through the cloud console? The ports (and IPs) are not editable in the UI I'm seeing.

**Comment by kholloway** [comment] 2017-06-06 16:23
**Edit the ILB:**

![screen shot 2017-06-06 at 11 12 28](https://user-images.githubusercontent.com/744689/26839736-8f8e8c46-4aa9-11e7-9c3b-d3cb75f3f5c8.png)

**View of current ports which includes ability to type new port numbers into the field and an "UPDATE" button at the bottom of the edit box:**

![screen shot 2017-06-06 at 11 12 52](https://user-images.githubusercontent.com/744689/26839762-a3be6a24-4aa9-11e7-8798-8599ee7289af.png)

**Detail confirming this is an INTERNAL load balancer:**

![screen shot 2017-06-06 at 11 19 54](https://user-images.githubusercontent.com/744689/26839867-eae1e4a8-4aa9-11e7-9bad-4851cf3165a7.png)

**Add a new port (5051) to the end of the list**

![screen shot 2017-06-06 at 11 21 53](https://user-images.githubusercontent.com/744689/26839985-50364e0c-4aaa-11e7-844d-3bbe72357dd2.png)

**Click update and Spinnaker goes through the motions to update and says it was successful**

![screen shot 2017-06-06 at 11 22 32](https://user-images.githubusercontent.com/744689/26839998-5b274b2c-4aaa-11e7-81c8-72b5057c7a44.png)

**Comment by kholloway** [comment] 2017-06-06 16:36
@jtk54 sorry I just re-read your comment and realized you wanted GCP cloud console screen shots @xordspar0 will have to provide those.

**Comment by jtk54** [comment] 2017-06-06 16:48
Ok I was confused for a bit :) GCP cloud console screen shots not necessary, I thought you were saying something different than you were.

@kholloway You're correct that you can (currently) modify ILB ports through Spinnaker, but it does not actually update the ports. I disabled editing from the UI in https://github.com/spinnaker/deck/pull/3790 so that Spinnaker doesn't behave

I think the correct/most consistent solution here is to support adding/removing whole listeners (like in HTTP LBs) instead of modifying the existing ones in place. What are you guys' thoughts about that?

**Comment by xordspar0** [comment] 2017-06-06 16:55
Yup, I think that's what we're looking for.

**Comment by edwinavalos** [comment] 2017-06-06 22:11
@jtk54 importantly being able to do the same replacement in place while specifying the IP address (usually the same IP address as before) during the update process.

**Comment by jtk54** [comment] 2017-06-07 14:22
@edwinavalos I'm not sure I understand the requirement you just described, can you add more detail?

**Comment by jtk54** [comment] 2017-06-13 14:28
I have the backend changes done for this, working on the frontend changes. Will cut both PRs together when they are ready.

**Comment by edwinavalos** [comment] 2017-06-13 14:44
@jtk54 When google lets you update the ILB in the GCP Console, you can delete and create a new listener in the same update step of the interface.

The part that I want to make sure is still available is that the IP address that listener that is to be deleted can be used to create the new listener in the same update step.

As far as I can tell that prevent downtime during the update.

**Comment by jtk54** [comment] 2017-06-14 17:37
Is there a reason why you guys need to update the listeners with the same IP address after you initially create the ILB? I _think_ we can support this in a reasonable way, but I just want to understand the use case first.

**Comment by edwinavalos** [comment] 2017-06-14 17:54
We have DNS records pointing to the IP addresses most of the time when we want to go change these load balancers, we'll also have to have teams update their DNS records, which is just an additional step we could avoid.

**Comment by jtk54** [comment] 2017-06-15 15:49
Backend: https://github.com/spinnaker/clouddriver/pull/1693
UI: https://github.com/spinnaker/deck/pull/3832

**Comment by jtk54** [comment] 2017-06-15 20:52
Changes are merged in, checkout master and take them for a spin to validate all the stuff you guys are asking for is there.

**Comment by jtk54** [comment] 2017-06-19 14:52
FYI The UI change broke a bunch of behavior, so we reverted and are looking into what the issues are now. Will submit a fixed-up version of that commit and notify here when we merge it.

**Comment by jtk54** [comment] 2017-06-20 20:06
Here's attempt number two at the UI changes: https://github.com/spinnaker/deck/pull/3859.

**Comment by jtk54** [comment] 2017-06-26 21:16
There's a difference in ILB representations between the backend and the frontend wreaking some havoc. @danielpeach will look in to solving.

**Comment by jtk54** [comment] 2017-06-28 17:06
https://github.com/spinnaker/deck/pull/3879 -- we decided to nix multiple listener support, which was complicating things.

**Comment by jtk54** [comment] 2017-06-29 15:00
This is tested and merged, give it a spin and let us know.

**Comment by xordspar0** [comment] 2017-06-30 16:13
Alright, we'll get back to you soon.

**Closed** 2017-10-02 18:39 UTC
Labels: provider/gce
