### ISSUE TITLE
Failing to resize server group when 2 server groups in 2 regions have the same name

### ISSUE THREAD

**Issue by dylanbernhardt** [spinnaker/spinnaker#3375] opened 2018-09-24 14:43 UTC
### Issue Summary:

When attempting to resize a server group the task fails due to timeout on the "Wait For Capacity Match" task if there are 2 server groups in 2 regions with the same name.

### Cloud Provider(s):

GCP

### Environment:

Spinnaker 1.8.5

### Feature Area: 

Pipelines (Resize Server Group)

### Description:

When using the following configuration for Resize Server Group when there are 2 clusters with the same name in 2 different regions the task times out.

For example, if you have a cluster called awesomeapp-api, and it has the following two server groups:
- awesomeapp-api-v015 in Central
- awesomeapp-api-v015 in East
Then the task will timeout.
![image](https://user-images.githubusercontent.com/30446845/45958237-8b904b80-bfdc-11e8-9557-87859386fd23.png)

Error message:

![image](https://user-images.githubusercontent.com/30446845/45958772-e37b8200-bfdd-11e8-81eb-b5452decc9e7.png)

### Steps to Reproduce:

Deploy 2 images to 2 regions in GCP then resize server groups with the configuration above.

### Additional Details:

A work-around to this is to have the versions in the name of the server groups (-v0XX) offset by 2 versions. This ensures the names of the previous server groups won't match.

**Comment by lwander** [comment] 2018-09-24 16:41
@jtk54 fyi

**Comment by jtk54** [comment] 2018-09-25 14:38
1. How did you get into this state? Generally two regional server groups deployed through Spinnaker would have two different version strings in the name.
2. Is resize the only operation that fails against two server groups with identical names?

**Comment by dylanbernhardt** [comment] 2018-09-25 15:11
@jtk54 
1. The two regional server groups have the same appname-stack-detail and are always deployed in the same deployment step, so both start at v000 and then increment to v001. The deployment configuration looks like: 
![image](https://user-images.githubusercontent.com/30446845/46023732-e3958380-c0aa-11e8-8abd-f63d8b7b3773.png)

2. That's the operation that's been reported to me as failing. I haven't seen anything else fail, but I didn't test other operations.

**Comment by jtk54** [comment] 2018-09-25 16:57
I was able to reproduce the server group state (two server groups in different regions with identical names). I tried an ad-hoc resize which worked properly. I configured a similar pipeline to yours:
0. find image.
1. deploy to two regions in parallel.
2. resize the server group in the two regions to 0-0-0.

I was also able to reproduce the hanging resize. It appears though the first resize works properly, but the second does not. I don't see the resize operation at all for the second in Clouddriver.

**Comment by jtk54** [comment] 2018-09-25 17:48
On closer inspection, the first resize operation is never finishing though the server groups have been scaled down. Are the deployed server groups autoscaled?

**Comment by dylanbernhardt** [comment] 2018-09-25 19:39
Yes, the team that reported the issue to me is using autoscaling on their server groups

**Comment by jtk54** [comment] 2018-09-26 16:40
The resize was mutating the resources properly, but the server group instance caching was incorrect. Since the server groups had the same name, all instances from all regions were included in each server group. PR is here: https://github.com/spinnaker/clouddriver/pull/2991. We'll cherry pick this into the supported releases.

**Comment by dylanbernhardt** [comment] 2018-09-26 17:06
Great! Thanks for the fix.

**Comment by jtk54** [comment] 2018-09-28 18:00
Spinnaker 1.8.7 has been released with this change included.

**Closed** 2018-10-01 16:44 UTC
Labels: bug, provider/gce
