### ISSUE TITLE
Load balancer Modal Not opening

### ISSUE THREAD

**Issue by joesenova** [spinnaker/spinnaker#5445] opened 2020-02-14 07:35 UTC
### Issue Summary:
Trying to Create new Load balancer with the Create Load Balancer button on the Load balancers tab of an application does not open and throughs console error.

When I remove either ECS or AWS as Cloud Provider Account, the Modal for creation of Load Balancers work as expected.

### Cloud Provider(s):
AWS
ECS

### Environment:
Running EC2 instance, installed Spinnaker using Halyard, spinnaker installed as local installation and running on the same EC2 instance

Spinnaker v1.17.6

### Feature Area:
Deck (Management UI)

### Description:
Actual behaviour : Trying to Create new Load balancer with the Create Load Balancer button on the Load balancers tab of an application does not open the Load Balancer Modal.

Expected behaviour :  Load Balancer Modal to open and can choose form LoadBalancers to create

### Steps to Reproduce:
1. Create Application with AWS and ECS selected as Cloud Provider Accounts
2. Go to Load Balancers tab
3. Click on the Create Load Balancer button

### Additional Details:  
TypeError: Cannot read property 'incompatibleLoadBalancerTypes' of undefined
    at AmazonLoadBalancerChoiceModal.getIncompatibility (AmazonLoadBalancerChoiceModal.tsx:71)
    at AmazonLoadBalancerChoiceModal.tsx:104
    at Array.map (<anonymous>)
    at AmazonLoadBalancerChoiceModal.render (AmazonLoadBalancerChoiceModal.tsx:104)
    at Qg (react-dom.production.min.js:173)
    at Og (react-dom.production.min.js:172)
    at Tg (react-dom.production.min.js:180)
    at bi (react-dom.production.min.js:232)
    at ci (react-dom.production.min.js:233)
    at Di (react-dom.production.min.js:249)

---

**Comment by allisaurus** [comment] 2020-02-20 21:49
This appears to be a duplicate of https://github.com/spinnaker/spinnaker/issues/5271 , which was fixed by https://github.com/spinnaker/deck/pull/7741 in 1.18.x

@joesenova are you able to upgrade to take advantage of the fix?

**Closed by allisaurus** 2020-02-20 21:49 UTC
Labels: provider/ecs, sig/aws

**Comment by joesenova** [comment] 2020-02-20 21:55
I will upgrade now and let you know.

Thanks 🙏 😊

**Comment by joesenova** [comment] 2020-02-20 22:06
All working as expected now. Thanks
