### ISSUE TITLE
Failed to evaluate script (EL1041E) leads to "false" failed deployment

### ISSUE THREAD

**Issue by sramek5** [spinnaker/spinnaker#5961] opened 2020-08-07 10:40 UTC
### Issue Summary:
Spinnaker has **SOMETIMES** script validation error which I tried to workaround, mentioned in #3028.

### Cloud Provider(s):
OpenStack
Kubernetes: v1.18.6
Spinnaker: 1.21.0

### Environment:
Using Spinnaker to deploy Zebee into kubernetes.

### Feature Area:
v2 Manifest Deploy

### Description:
Configmap with shell script has environment variables. These are skipped in manifest using escape characters`${"${VAR}"}`.

### Steps to Reproduce:
Original configmap:
```
kind: ConfigMap
metadata:
  name: {{ include "zeebe-cluster.fullname" . }}
  labels: 
    {{- include "zeebe-cluster.labels" . | nindent 4 }}
apiVersion: v1
data:
  startup.sh: |
    #!/usr/bin/env bash
    set -eux -o pipefail

    export ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=${ZEEBE_BROKER_NETWORK_ADVERTISEDHOST:-$(hostname -f)}
    export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_POD_NAME##*-}}

    # As the number of replicas or the DNS is not obtainable from the downward API yet,
    # defined them here based on conventions
    export ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE:-1}
    contactPointPrefix=${K8S_POD_NAME%-*}
    contactPoints=${ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS:-""}
    if [[ -z "${contactPoints}" ]]; then
      for ((i=0; i<${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE}; i++))
      do
        contactPoints="${contactPoints},${contactPointPrefix}-$i.$(hostname -d):{{ .Values.serviceInternalPort }}"
      done

      export ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS="${contactPoints}"
    fi
    
    if [ "$(ls -A /exporters/)" ]; then
      mkdir /usr/local/zeebe/exporters/
      cp -a /exporters/*.jar /usr/local/zeebe/exporters/
    else  
      echo "No exporters available."
    fi

    exec /usr/local/zeebe/bin/broker

  application.yaml: |
{{- if .Values.zeebeCfg }}
{{- with .Values.zeebeCfg }}
{{ . | toYaml | indent 4 }}
{{- end }}
{{- end }}

  broker-log4j2.xml: |
{{- if .Values.log4j2 }}
    {{ .Values.log4j2 | indent 4 | trim }}
{{- end }}

  gateway-log4j2.xml: |
{{- if .Values.gateway.log4j2 }}
    {{ .Values.gateway.log4j2 | indent 4 | trim }}
{{- end }}
```
I changed it with escape characters:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zeebe-cluster.fullname" . }}
{{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
  labels:
    app: zeebe
data:
  startup.sh: |
    #!/usr/bin/env bash
    set -eux -o pipefail

    export ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=${"${ZEEBE_BROKER_NETWORK_ADVERTISEDHOST:-$(hostname -f)}"}
    export ZEEBE_BROKER_CLUSTER_NODEID=${"${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_POD_NAME##*-}}"}

    # As the number of replicas or the DNS is not obtainable from the downward API yet, 
    # defined them here based on conventions:
    export ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=${"${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE:-1}"}
    contactPointPrefix=${"${K8S_POD_NAME%-*}"}
    contactPoints=${"${ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS:-}"}
    if [[ -z ${"${contactPoints}"} ]]; then
      for ((i=0; i<${"${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE}"}; i++))
      do
        contactPoints=${"${contactPoints},${contactPointPrefix}-$i.$(hostname -d):{{ .Values.serviceInternalPort }}"}
      done

      export ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=${"${contactPoints}"}
    fi
    
    if [ ${"$(ls -A /exporters/)"} ]; then
      mkdir /usr/local/zeebe/exporters/
      cp -a /exporters/*.jar /usr/local/zeebe/exporters/
    else  
      echo "No exporters available."
    fi

    exec /usr/local/zeebe/bin/broker

  application.yaml: |
{{- if .Values.zeebeCfg }}
{{- with .Values.zeebeCfg }}
{{ . | toYaml | indent 4 }}
{{- end }}
{{- end }}

  broker-log4j2.xml: |
{{- if .Values.log4j2 }}
    {{ .Values.log4j2 | indent 4 | trim }}
{{- end }}

  gateway-log4j2.xml: |
{{- if .Values.gateway.log4j2 }}
    {{ .Values.gateway.log4j2 | indent 4 | trim }}
{{- end }}
```

### Additional Details:
Here you can see failed deployment:
![image](https://user-images.githubusercontent.com/53052347/89636154-73600780-d8a8-11ea-9ac6-37672b0f00c8.png)

But all deployment objects are successfully running:
```
NAME                                       READY   STATUS    RESTARTS   AGE
pod/cluster-zeebe-0                        1/1     Running   0          175m
pod/cluster-zeebe-1                        1/1     Running   0          175m
pod/cluster-zeebe-2                        1/1     Running   0          175m
pod/cluster-zeebe-gateway-57b4f9d9-vb4sp   1/1     Running   0          175m

NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                          AGE
service/cluster-zeebe           ClusterIP      None            <none>        9600/TCP,26502/TCP,26501/TCP     175m
service/cluster-zeebe-gateway   LoadBalancer   10.100.80.242   10.8.7.95     9600:31302/TCP,26500:30925/TCP   175m

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cluster-zeebe-gateway   1/1     1            1           175m

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/cluster-zeebe-gateway-57b4f9d9   1         1         1       175m

NAME                             READY   AGE
statefulset.apps/cluster-zeebe   3/3     175m
```
BONUS - renderred script inside a container:
```
#!/usr/bin/env bash
set -eux -o pipefail

export ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=${ZEEBE_BROKER_NETWORK_ADVERTISEDHOST:-$(hostname -f)}
export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_POD_NAME##*-}}

# As the number of replicas or the DNS is not obtainable from the downward API yet, 
# defined them here based on conventions:
export ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE:-1}
contactPointPrefix=${K8S_POD_NAME%-*}
contactPoints=${ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS:-}
if [[ -z ${contactPoints} ]]; then
  for ((i=0; i<${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE}; i++))
  do
    contactPoints=${contactPoints},${contactPointPrefix}-$i.$(hostname -d):26502
  done

  export ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=${contactPoints}
fi

if [ $(ls -A /exporters/) ]; then
  mkdir /usr/local/zeebe/exporters/
  cp -a /exporters/*.jar /usr/local/zeebe/exporters/
else  
  echo "No exporters available."
fi

exec /usr/local/zeebe/bin/broker
```
### Questions:
1. Why is this happening only sometimes?
2. Do we really need these escape characters? We do not need to validate scripts by spinnaker, its responsibility is to deploy by reading yaml manifests. I would like to see a possibility to place any other characters at the **START** of the script and at the **END** of it (possible new feature?).

Thank you for your help!

**Comment by kskewes** [comment] 2020-08-07 21:01
I wonder if this is related to Orca doing additional parsing and failing per https://github.com/spinnaker/spinnaker/issues/5626

**Comment by neakor** [comment] 2020-08-14 03:09
We are seeing the same issue in 1.20.4. This seems like a regression of #3644

**Comment by ezimanyi** [comment] 2020-08-15 00:11
Yeah, this is almost certainly due to the fact that Orca is evaluating SpEL on the manifest as noted by @kskewes.  We are working on a refactor of the way we handle Kubernetes deploy stages that will stop this from happening (#5909).  (This is part of a bunch of performance/refactoring work that we're actively working on.)

Right now what happens is that you can opt out of SpEL evaluation in the stage via:
![image](https://user-images.githubusercontent.com/1391982/90300678-b6524a00-de69-11ea-9114-ed3ff6ad0430.png)

But even if you do, `orca` still evaluates the manifest because it is included in the pipeline context, and `orca` evaluates everything in the context.  The workaround for now is that if the checkbox in the "Execution Options" is un-checked, the `orca` evaluation should only produce a warning and not fail the stage:
![image](https://user-images.githubusercontent.com/1391982/90300705-db46bd00-de69-11ea-89ac-b3a526c41ab4.png)

This still doesn't fully solve the problem because in the unlucky event that one of the undesired SpEL evaluations actually changed the manifest, then there's not really a way to stop that.

I'll close this as a duplicate of #5626 and #5909, as I believe those should solve the issue, but please feel free to re-open/comment if upon reading those you don't think it's a duplicate.

**Closed by ezimanyi** 2020-08-15 00:11 UTC
Labels: sig/kubernetes
