### ISSUE TITLE
Failed to trigger the bake and deploy pipeline

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#6736] opened 2022-10-08 08:02 UTC
### Issue Summary:
It failed to trigger the bake and deploy pipeline (createServerGroup) and it failed to trigger the disable and destroy pipeline. After investigated, it seems that the failure is caused by the commit https://github.com/spinnaker/clouddriver/pull/5791. If reverted this commit, it works fine. @ovidiupopa07, so could you take a look this issue and fix it asap since we're blocked now? Thanks.

### Error Message while triggering the bake and deploy pipeline:
```
{
    "phase": "ORCHESTRATION",
    "status": "Orchestration failed: CreateAzureServerGroupWithAzureLoadBalancerAtomicOperation | ManagementException: [Status code 400, "{  "error": {    "code": "LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue",    "message": "BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.",    "details": []  }}"]"
}
```

### Error Message while triggering the disable and destroy pipeline:
```
"type": "determineTargetServerGroup",
      "name": "determineTargetServerGroup",
      "status": "TERMINAL",
      "context": {
        "exception": {
          "exceptionType": "NotFoundException",
          "shouldRetry": false,
          "details": {
            "stackTrace": "com.netflix.spinnaker.orca.clouddriver.pipeline.servergroup.support.TargetServerGroup$NotFoundException: Unable to locate current_asg_dynamic in my-azure-account/westus2/xxxx-st-frontend\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat,
            "error": "Unexpected Task Failure",
            "errors": [
              "Unable to locate current_asg_dynamic in my-azure-account/westus2/xxxx-st-frontend"
            ]
          },
          "operation": "determineTargetServerGroup"
        },
```

### Cloud Provider(s):
Azure

### Environment:
ubuntu 18.04

### Feature Area:
Clouddriver

### Steps to Reproduce:
1. hal config version edit --version branch:upstream/master
2. hal deploy apply
3. Create a new Spinnaker Application
4. Create a new load balancer
5. Create the bake and deploy pipeline
6. Create the disable and destroy pipeline
7. Trigger the bake and deploy pipeline. This creates a new server group below the given load balancer but it failed
8. Trigger the disable and destroy pipeline but it failed

**Comment by neil-yechenwei** [comment] 2022-10-09 00:59
Add @ajordens for awareness.

**Comment by ovidiupopa07** [comment] 2022-10-10 06:50
hi @neil-yechenwei. I will start looking into this now. Would it be possible to provide the pipeline JSON to import it in my local Spinnaker instance, please? (of course without the sensitive data). Thank you!

**Comment by neil-yechenwei** [comment] 2022-10-11 01:49
Sure. Hopes it would be helpful.

```
{
    "type": "PIPELINE",
    "id": "xxx",
    "application": "xxxx",
    "name": "BakeAndDeploy",
    "buildTime": 1665285267237,
    "canceled": false,
    "limitConcurrent": true,
    "maxConcurrentExecutions": 0,
    "keepWaitingPipelines": false,
    "stages": [
        {
            "id": "xxx",
            "refId": "BAKE<1",
            "type": "bake",
            "name": "Bake in westus2",
            "startTime": 1665285267402,
            "endTime": 1665285268385,
            "status": "SUCCEEDED",
            "context": {
                "package": "",
                "imageId": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/images/all-20211213102146-ubuntu-1604",
                "imageName": "all-20211213102146-ubuntu-1604",
                "baseLabel": "release",
                "type": "bake",
                "extendedAttributes": {},
                "bakePackageName": "",
                "amiSuffix": "20221009031427",
                "baseOs": "ubuntu-1604",
                "previouslyBaked": true,
                "osType": "linux",
                "name": "Bake in westus2",
                "cloudProviderType": "azure",
                "region": "westus2",
                "ami": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/all-20211213102146-ubuntu-1604",
                "user": "xxxx@xxx.org",
                "status": {
                    "result": "SUCCESS",
                    "resourceId": "xxxx-xx-xx",
                    "id": "xx-xx-xxx",
                    "state": "COMPLETED"
                },
                "artifacts": [
                    {
                        "customKind": false,
                        "reference": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/all-20211213102146-ubuntu-1604",
                        "metadata": {},
                        "name": "all-20211213102146-ubuntu-1604",
                        "location": "westus2",
                        "type": "azure/image",
                        "uuid": "xxxx"
                    }
                ]
            },
            "outputs": {},
            "tasks": [
                {
                    "id": "1",
                    "implementingClass": "com.netflix.spinnaker.orca.bakery.tasks.CreateBakeTask",
                    "name": "createBake",
                    "startTime": 1665285267454,
                    "endTime": 1665285267866,
                    "status": "SUCCEEDED",
                    "stageStart": true,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "2",
                    "implementingClass": "com.netflix.spinnaker.orca.bakery.tasks.MonitorBakeTask",
                    "name": "monitorBake",
                    "startTime": 1665285267917,
                    "endTime": 1665285268021,
                    "status": "SUCCEEDED",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "3",
                    "implementingClass": "com.netflix.spinnaker.orca.bakery.tasks.CompletedBakeTask",
                    "name": "completedBake",
                    "startTime": 1665285268073,
                    "endTime": 1665285268177,
                    "status": "SUCCEEDED",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "4",
                    "implementingClass": "com.netflix.spinnaker.orca.pipeline.tasks.artifacts.BindProducedArtifactsTask",
                    "name": "bindProducedArtifacts",
                    "startTime": 1665285268229,
                    "endTime": 1665285268332,
                    "status": "SUCCEEDED",
                    "stageStart": false,
                    "stageEnd": true,
                    "loopStart": false,
                    "loopEnd": false
                }
            ],
            "syntheticStageOwner": "STAGE_BEFORE",
            "parentStageId": "xxx",
            "requisiteStageRefIds": []
        },
        {
            "id": "xxx",
            "refId": "BAKE",
            "type": "bake",
            "name": "Bake",
            "startTime": 1665285267350,
            "endTime": 1665285268648,
            "status": "SUCCEEDED",
            "context": {
                "amiSuffix": "20221009031427",
                "baseOs": "ubuntu-1604",
                "package": "",
                "regions": [
                    "westus2"
                ],
                "baseLabel": "release",
                "osType": "linux",
                "cloudProviderType": "azure",
                "user": "xxxx",
                "extendedAttributes": {}
            },
            "outputs": {
                "deploymentDetails": [
                    {
                        "ami": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/all-20211213102146-ubuntu-1604",
                        "imageId": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/all-20211213102146-ubuntu-1604",
                        "imageName": "all-20211213102146-ubuntu-1604",
                        "amiSuffix": "20221009031427",
                        "baseLabel": "release",
                        "baseOs": "ubuntu-1604",
                        "region": "westus2",
                        "package": "",
                        "cloudProviderType": "azure"
                    }
                ]
            },
            "tasks": [
                {
                    "id": "1",
                    "implementingClass": "com.netflix.spinnaker.orca.bakery.pipeline.BakeStage.CompleteParallelBakeTask",
                    "name": "completeParallel",
                    "startTime": 1665285268490,
                    "endTime": 1665285268595,
                    "status": "SUCCEEDED",
                    "stageStart": true,
                    "stageEnd": true,
                    "loopStart": false,
                    "loopEnd": false
                }
            ],
            "requisiteStageRefIds": []
        },
        {
            "id": "xxxx",
            "refId": "DEPLOY<1",
            "type": "createServerGroup",
            "name": "Deploy in westus2",
            "startTime": 1665285268753,
            "endTime": 1665285335060,
            "status": "TERMINAL",
            "context": {
                "subnet": "default",
                "notification.type": "createdeploy",
                "deploy.account.name": "my-azure-account",
                "stack": "st",
                "customScriptsSettings": {
                    "commandToExecute": ""
                },
                "instanceTags": {},
                "source": {},
                "type": "createServerGroup",
                "selectedProvider": "azure",
                "capacity": {
                    "min": 1,
                    "max": 1
                },
                "vnet": "xxx",
                "freeFormDetails": "frontend",
                "vnetResourceGroup": "xxxx",
                "loadBalancerName": "xxxx",
                "cloudProvider": "azure",
                "kato.result.expected": false,
                "sku": {
                    "tier": "Standard",
                    "name": "Standard_B1ms",
                    "capacity": 1
                },
                "kato.last.task.id": {
                    "id": "xxxx"
                },
                "rollback": {},
                "image": {
                    "offer": "",
                    "imageName": "all-20211213102146-ubuntu-1604",
                    "isCustom": true,
                    "publisher": "",
                    "ostype": "linux",
                    "region": "westus2",
                    "sku": "",
                    "uri": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/images/all-20211213102146-ubuntu-1604",
                    "version": ""
                },
                "interestingHealthProviderNames": [],
                "loadBalancerType": "Azure Load Balancer",
                "instanceType": "Standard_B1ms",
                "kato.task.terminalRetryCount": 0,
                "zonesEnabled": false,
                "useSourceCapacity": false,
                "zones": [],
                "kato.task.firstNotFoundRetry": -1,
                "upgradePolicy": "Manual",
                "application": "xxxx",
                "osConfig": {},
                "name": "xxxx",
                "viewState": {
                    "expectedArtifacts": [],
                    "useAllImageSelection": false,
                    "instanceProfile": "custom",
                    "securityGroupsConfigured": true,
                    "disableImageSelection": true,
                    "loadBalancersConfigured": true,
                    "useSimpleCapacity": true,
                    "mode": "createPipeline",
                    "disableStrategySelection": true,
                    "networkSettingsConfigured": true,
                    "submitButtonLabel": "Add",
                    "templatingEnabled": true,
                    "showImageSourceSelector": true,
                    "hideClusterNamePreview": false,
                    "readOnlyFields": {},
                    "usePreferredZones": true
                },
                "kato.tasks": [
                    {
                        "exception": {
                            "cause": "Status code 400, \"{\r\n  \"error\": {\r\n    \"code\": \"LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue\",\r\n    \"message\": \"BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.\",\r\n    \"details\": []\r\n  }\r\n}\"",
                            "details": [
                                {
                                    "message": "Status code 400, \"{\r\n  \"error\": {\r\n    \"code\": \"LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue\",\r\n    \"message\": \"BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.\",\r\n    \"details\": []\r\n  }\r\n}\""
                                }
                            ],
                            "message": "Status code 400, \"{\r\n  \"error\": {\r\n    \"code\": \"LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue\",\r\n    \"message\": \"BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.\",\r\n    \"details\": []\r\n  }\r\n}\"",
                            "type": "EXCEPTION",
                            "operation": "CreateAzureServerGroupWithAzureLoadBalancerAtomicOperation"
                        },
                        "resultObjects": [
                            {
                                "cause": "Status code 400, \"{\r\n  \"error\": {\r\n    \"code\": \"LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue\",\r\n    \"message\": \"BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.\",\r\n    \"details\": []\r\n  }\r\n}\"",
                                "details": [
                                    {
                                        "message": "Status code 400, \"{\r\n  \"error\": {\r\n    \"code\": \"LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue\",\r\n    \"message\": \"BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.\",\r\n    \"details\": []\r\n  }\r\n}\""
                                    }
                                ],
                                "message": "Status code 400, \"{\r\n  \"error\": {\r\n    \"code\": \"LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue\",\r\n    \"message\": \"BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.\",\r\n    \"details\": []\r\n  }\r\n}\"",
                                "type": "EXCEPTION",
                                "operation": "CreateAzureServerGroupWithAzureLoadBalancerAtomicOperation"
                            }
                        ],
                        "id": "xxxx",
                        "history": [
                            {
                                "phase": "ORCHESTRATION",
                                "status": "Initializing Orchestration Task"
                            },
                            {
                                "phase": "ORCHESTRATION",
                                "status": "Processing op: CreateAzureServerGroupWithAzureLoadBalancerAtomicOperation"
                            },
                            {
                                "phase": "CREATE_SERVER_GROUP",
                                "status": "Initializing deployment of server group with Azure Load Balancer xxxx-st-frontend in westus2"
                            },
                            {
                                "phase": "CREATE_SERVER_GROUP",
                                "status": "Beginning server group deployment"
                            },
                            {
                                "phase": "CREATE_SERVER_GROUP",
                                "status": "Using virtual network xxxx and subnet default for server group xxxx-st-frontend"
                            },
                            {
                                "phase": "CREATE_SERVER_GROUP",
                                "status": "Create new backend address pool in Load Balancer: xxxx-st-frontend"
                            },
                            {
                                "phase": "CREATE_SERVER_GROUP",
                                "status": "Create new inbound NAT pool in Load Balancer: xxxx-st-frontend"
                            },
                            {
                                "phase": "CREATE_SERVER_GROUP",
                                "status": "Deploying server group"
                            },
                            {
                                "phase": "CREATE_SERVER_GROUP",
                                "status": "Resource xxxx-st-frontend-v000 created"
                            },
                            {
                                "phase": "ORCHESTRATION",
                                "status": "Orchestration failed: CreateAzureServerGroupWithAzureLoadBalancerAtomicOperation | ManagementException: [Status code 400, \"{\r\n  \"error\": {\r\n    \"code\": \"LoadBalancingRuleBackendAdressPoolAndBackendAddressPoolsCannotBeSetAtTheSameTimeWithDifferentValue\",\r\n    \"message\": \"BackendAddressPool and BackendAddressPools[] in LoadBalancingRule xxxx-st-frontend-rule0 cannot be set at the same time with different value.\",\r\n    \"details\": []\r\n  }\r\n}\"]"
                            }
                        ],
                        "status": {
                            "retryable": false,
                            "completed": true,
                            "failed": true
                        }
                    }
                ],
                "detail": "frontend",
                "region": "westus2",
                "strategy": "",
                "kato.task.notFoundRetryCount": 0,
                "user": "xxxx",
                "account": "my-azure-account",
                "enableInboundNAT": false,
                "kato.task.lastStatus": "TERMINAL"
            },
            "outputs": {},
            "tasks": [
                {
                    "id": "1",
                    "implementingClass": "com.netflix.spinnaker.orca.kato.pipeline.strategy.DetermineSourceServerGroupTask",
                    "name": "determineSourceServerGroup",
                    "startTime": 1665285268855,
                    "endTime": 1665285268959,
                    "status": "SUCCEEDED",
                    "stageStart": true,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "2",
                    "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.DetermineHealthProvidersTask",
                    "name": "determineHealthProviders",
                    "startTime": 1665285269011,
                    "endTime": 1665285269116,
                    "status": "SUCCEEDED",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "3",
                    "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.servergroup.CreateServerGroupTask",
                    "name": "createServerGroup",
                    "startTime": 1665285269167,
                    "endTime": 1665285269322,
                    "status": "SUCCEEDED",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "4",
                    "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.MonitorKatoTask",
                    "name": "monitorDeploy",
                    "startTime": 1665285269374,
                    "endTime": 1665285334992,
                    "status": "TERMINAL",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "5",
                    "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.servergroup.ServerGroupCacheForceRefreshTask",
                    "name": "forceCacheRefresh",
                    "status": "NOT_STARTED",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "6",
                    "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask",
                    "name": "waitForUpInstances",
                    "status": "NOT_STARTED",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "7",
                    "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.servergroup.ServerGroupCacheForceRefreshTask",
                    "name": "forceCacheRefresh",
                    "status": "NOT_STARTED",
                    "stageStart": false,
                    "stageEnd": false,
                    "loopStart": false,
                    "loopEnd": false
                },
                {
                    "id": "8",
                    "implementingClass": "com.netflix.spinnaker.orca.igor.tasks.GetCommitsTask",
                    "name": "getCommits",
                    "status": "NOT_STARTED",
                    "stageStart": false,
                    "stageEnd": true,
                    "loopStart": false,
                    "loopEnd": false
                }
            ],
            "syntheticStageOwner": "STAGE_BEFORE",
            "parentStageId": "xxxx",
            "requisiteStageRefIds": []
        },
        {
            "id": "xxxx",
            "refId": "DEPLOY",
            "type": "deploy",
            "name": "Deploy",
            "startTime": 1665285268700,
            "endTime": 1665285335100,
            "status": "TERMINAL",
            "context": {
                "clusters": [
                    {
                        "subnet": "default",
                        "stack": "st",
                        "customScriptsSettings": {
                            "commandToExecute": ""
                        },
                        "instanceTags": {},
                        "type": "createServerGroup",
                        "selectedProvider": "azure",
                        "capacity": {
                            "min": 1,
                            "max": 1
                        },
                        "vnet": "xxxx",
                        "freeFormDetails": "frontend",
                        "vnetResourceGroup": "xxxx",
                        "loadBalancerName": "xxxx-st-frontend",
                        "cloudProvider": "azure",
                        "sku": {
                            "tier": "Standard",
                            "name": "Standard_B1ms",
                            "capacity": 1
                        },
                        "rollback": {},
                        "image": {
                            "offer": "",
                            "imageName": "",
                            "isCustom": "true",
                            "publisher": "",
                            "ostype": "",
                            "region": "westus2",
                            "sku": "",
                            "uri": "",
                            "version": ""
                        },
                        "interestingHealthProviderNames": [],
                        "loadBalancerType": "Azure Load Balancer",
                        "instanceType": "Standard_B1ms",
                        "zonesEnabled": false,
                        "useSourceCapacity": false,
                        "zones": [],
                        "upgradePolicy": "Manual",
                        "application": "xxxx",
                        "osConfig": {},
                        "name": "xxxx-st-frontend",
                        "viewState": {
                            "expectedArtifacts": [],
                            "useAllImageSelection": false,
                            "instanceProfile": "custom",
                            "securityGroupsConfigured": true,
                            "disableImageSelection": true,
                            "loadBalancersConfigured": true,
                            "useSimpleCapacity": true,
                            "mode": "createPipeline",
                            "disableStrategySelection": true,
                            "networkSettingsConfigured": true,
                            "submitButtonLabel": "Add",
                            "templatingEnabled": true,
                            "showImageSourceSelector": true,
                            "hideClusterNamePreview": false,
                            "readOnlyFields": {},
                            "usePreferredZones": true
                        },
                        "detail": "frontend",
                        "region": "westus2",
                        "strategy": "",
                        "user": "xxxx",
                        "account": "my-azure-account",
                        "enableInboundNAT": false
                    }
                ]
            },
            "outputs": {},
            "tasks": [
                {
                    "id": "1",
                    "implementingClass": "com.netflix.spinnaker.orca.kato.pipeline.ParallelDeployStage.CompleteParallelDeployTask",
                    "name": "completeParallelDeploy",
                    "status": "NOT_STARTED",
                    "stageStart": true,
                    "stageEnd": true,
                    "loopStart": false,
                    "loopEnd": false
                }
            ],
            "requisiteStageRefIds": [
                "BAKE"
            ]
        }
    ],
    "startTime": 1665285267334,
    "endTime": 1665285335151,
    "status": "TERMINAL",
    "authentication": {
        "user": "xxxx",
        "allowedAccounts": [
            "my-azure-account"
        ]
    },
    "origin": "api",
    "trigger": {
        "type": "manual",
        "user": "xxx",
        "parameters": {},
        "artifacts": [],
        "notifications": [],
        "rebake": false,
        "dryRun": false,
        "strategy": false,
        "resolvedExpectedArtifacts": [],
        "expectedArtifacts": [],
        "application": "xxxx",
        "description": "Test - begin bake and deploy: BakeAndDeploy",
        "job": [
            {
                "dryRun": false,
                "type": "manual",
                "user": "xxxx"
            }
        ]
    },
    "pipelineConfigId": "xxxxx",
    "notifications": [],
    "initialConfig": {},
    "systemNotifications": []
}
```

**Comment by neil-yechenwei** [comment] 2022-10-14 01:14
@ovidiupopa07 , kindly ping. May I ask whether the blocking issue has been fixed? If no, does it make sense to revert the blocking change for now since we're blocked now?

Add @mybayern1974 for awareness.

**Comment by ovidiupopa07** [comment] 2022-10-14 06:11
hi @neil-yechenwei. Not yet, I am still trying to understand what changed in the SDK that is causing this behavior - as the clouddriver flow was untouched. One question: would it be possible to use the latest LTS release (1.29) until this is fixed in master branch? The only diff between `1.29` release and `master` is only the SDK upgrade - in the azure module.

**Comment by neil-yechenwei** [comment] 2022-10-14 08:18
Thanks @ovidiupopa07 for the update. We have to ensure there is no breaking change or blocking issue on master branch in case the bug/issue is brought into stable release. So we can wait until it's fixed. Once the issue is fixed, please let us know. Thanks in advance.

**Comment by ovidiupopa07** [comment] 2022-10-14 08:22
> Thanks @ovidiupopa07 for the update. We have to ensure there is no breaking change or blocking issue on master branch in case the bug/issue is brought into stable release. So we can wait until it's fixed. Once the issue is fixed, please let us know. Thanks in advance.

Yes, I agree, I will fix it for sure. I was mentioning this as a workaround until I fix the issue in the master branch, just to unblock you. I will let you know when I push the fix.

**Comment by neil-yechenwei** [comment] 2022-10-24 01:06
Hi @ovidiupopa07 , kindly ping. Is there any update for the issue?

**Comment by ovidiupopa07** [comment] 2022-10-26 12:36
Hi again @neil-yechenwei. I did the test with a load balancer. It works fine for me
![image](https://user-images.githubusercontent.com/105648914/198026403-f605240a-d415-416c-886a-b70a0aff30a2.png)
![image](https://user-images.githubusercontent.com/105648914/198027026-b372aa70-3cbc-4844-a18a-d8698a8923c1.png)
![image](https://user-images.githubusercontent.com/105648914/198027243-d57a6c70-101c-4760-b7e1-63dbc9330813.png)

The load balancer is pointing to the correct backend pool 
![image](https://user-images.githubusercontent.com/105648914/198027398-978ff246-4616-4225-9c2d-eb908ed8ef1f.png)

**Comment by neil-yechenwei** [comment] 2022-10-27 02:40
@ovidiupopa07 , though the load balancer is created but it's with error. You can get the error by clicking "Activity Log" in Azure Portal after created the resource several minutes (etc, 20 mins). When I reverted your commit, the error disappeared. So could you double check the error message from Azure Portal? Thanks.

![image](https://user-images.githubusercontent.com/19754191/198177824-07f37d08-dc70-4f45-800b-2775e6810127.png)

**Comment by neil-yechenwei** [comment] 2022-10-27 10:30
@ovidiupopa07 , I encountered this error while deploying with command `hal config version edit --version branch:upstream/master` and `hal deploy apply` that would involve your commit.

**Comment by ovidiupopa07** [comment] 2022-10-27 16:01
hi @neil-yechenwei. I managed to reproduce it. If the load balancer has no rule defined everything works fine. If a rule is defined it fails when adding a new backend pool. 

Anyway, it is strange why is not failing with the old azure SDK but is failing with the new one. I've gone through the SDKs and I don't see any big difference. I will further investigate the reason why this is happening and I will come up with a solution

**Comment by ovidiupopa07** [comment] 2022-10-27 16:27
> hi @neil-yechenwei. I managed to reproduce it. If the load balancer has no rule defined everything works fine. If a rule is defined it fails when adding a new backend pool.
> 
> Anyway, it is strange why is not failing with the old azure SDK but is failing with the new one. I've gone through the SDKs and I don't see any big difference. I will further investigate the reason why this is happening and I will come up with a solution

Actually, I just saw something. In the old SDK, there is only one property `backendAddressPool` defined in `LoadBalancingRuleInner`. 

In the latest SDK there are 2 properties 
![image](https://user-images.githubusercontent.com/105648914/198346508-8a7c5eab-255b-465f-9e9b-b91f8233c7cd.png)

**Comment by ovidiupopa07** [comment] 2022-10-28 10:38
hi @neil-yechenwei. I fixed the issue: 
![image](https://user-images.githubusercontent.com/105648914/198568175-6eed9ffb-9e93-4740-a040-16b974f3b944.png)

I will open a PR later today.

**Closed** 2022-11-02 15:17 UTC
