### ISSUE TITLE
Kubernetes RetrofitError: network timeout 

### ISSUE THREAD

**Issue by ademariag** [spinnaker/spinnaker#5218] opened 2019-12-10 13:39 UTC
### Issue Summary:
Suddenly Spinnaker is unable to connect to all Kubernetes clusters.

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.17.2. Spinnaker for GCP.

### Feature Area:
Pipelines

### Description:
Every couple of days, our Spinnaker installation loses the ability to connect to all remote Kubernetes cluster.

In the errored pipelines, 

```
Exception ( Delete Manifest )
timeout
```

and digging into the pipeline execution, we see 
```
        "exception": {
          "exceptionType": "RetrofitError",
          "shouldRetry": false,
          "details": {
            "kind": "NETWORK",
            "error": "timeout",
            "errors": [
              
            ]
          },
```

### Steps to Reproduce:
Once the event occurs, any pipeline from any cluster will trigger the condition.

### Additional Details:

WORKAROUND:
restarting the CloudDriver component seems to fix it.

---

**_Please delete the instructions below this line prior to submitting_**

**Comment by bsda** [comment] 2019-12-11 10:22
Just add that this could be related to https://github.com/spinnaker/spinnaker/issues/5041.

Clouddriver was using 100% of 4 CPUs at the time it happened
We upgraded our nodes and will keep an eye on it.

**Comment by maggieneterval** [comment] 2019-12-18 20:03
Hey @ademariag, thanks for taking the time to open this issue! Let's try to collect some more information next time the timeout event happens so we can determine the root cause: next time, would you mind checking the Orca and Clouddriver logs, and running `kubectl top` on your Clouddriver pod (or however you check resource utilization)? As @bsda mentioned, you may need to allocate additional resources to the Clouddriver pod. How many Kubernetes accounts do you currently have Clouddriver deploying to? Do you have only one Clouddriver pod, or are you running in [HA mode](https://www.spinnaker.io/reference/halyard/high-availability/#ha-clouddriver)?

**Comment by ademariag** [comment] 2019-12-18 22:05
Hi @maggieneterval ,
@bsda works in my team and yes we did increase the resources available.
Since then, we have not experienced this issue anymore.

We are running with one pod but migrating to HA mode soon

**Comment by maggieneterval** [comment] 2019-12-18 22:09
@ademariag thanks for the quick reply! I'm happy to hear that allocating additional resources to Clouddriver resolved the issue; going to close this bug for now. Please feel free to open another if you run into any more problems!

**Closed by maggieneterval** 2019-12-18 22:09 UTC
Labels: bug, component/clouddriver, sig/kubernetes

**Comment by rampatnaik** [comment] 2020-03-13 08:02
NAME                                     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gke-spinace10a6f-czhm   7527m        47%    18542Mi         33%

**Comment by rampatnaik** [comment] 2020-03-13 08:04
@spinnakerbot  reopen
