### ISSUE TITLE
GCS default artifact is not working: Required String parameter 'version' is not present

### ISSUE THREAD

**Issue by fpytloun** [spinnaker/spinnaker#2491] opened 2018-03-01 13:35 UTC
*Cloud Provider*

GCE

*Environment*

I am running GCE with configured GCS artifact storage

*Feature Area*

Pipelines, artifact storage

*Description*

When using GCS with default artifact (tried both GCE or custom with reference), running pipeline will result in error: "Required String parameter 'version' is not present"
I do not have enabled file versioning so when I enter version in custom default artifact, it will fail with error saying that object was not found

*Steps to Reproduce*

See attached screenshot: https://imgur.com/a/IEjqb

**Comment by ezimanyi** [comment] 2018-03-01 16:16
This is a duplicate of #2468; the fix was merged this week and it will be fixed in 1.6.1.

**Closed by ezimanyi** 2018-03-01 16:16 UTC
