### ISSUE TITLE
When namespace is not provided in manifests.yaml everything is deployed into spinnaker namespace

### ISSUE THREAD

**Issue by sramek5** [spinnaker/spinnaker#6193] opened 2020-11-24 08:14 UTC
### Environment:
Spinnaker: 1.23.2 (Hemlock Grove)
Kubernetes: v1.19.0

### Additional Details
Logically, it was default namespace before (when namespace not specified).

**Comment by ezimanyi** [comment] 2020-11-30 17:49
Closing as a duplicate of #5731; please see that issue for a discussion and how to set up the accounts to specify the namespace.

**Closed by ezimanyi** 2020-11-30 17:49 UTC
Labels: sig/kubernetes

**Comment by sramek5** [comment] 2020-12-04 16:05
I know how to specify namespace.

I just want to point out, that people who deploy make mistakes and in some manifests they forget to mention namespace.

For us is namespace spinaker omitted, so in this situation, there is a lot of unwanted stuff. This stuff should be in default namespace like in previous versions.
