### ISSUE TITLE
Pub/Sub MessageDispatcher error (GKE)

### ISSUE THREAD

**Issue by klodnickik** [spinnaker/spinnaker#5453] opened 2020-02-17 16:03 UTC
### Issue Summary:

I have issue with Pub/Sub configuration for Spinnaker. Spinnaker is hosted on GKE, the deployment has been done with Halyard. The pub/sub trigger has been configured according to documentation on website https://www.spinnaker.io/setup/triggers/google/

Every time when I sent the  message (JSON format) to Pub/Sub topic there is error generated on Spinnaker side (echo microservice). It looks that Spinnaker is not able to receive the message (c.g.cloud.pubsub.v1.MessageDispatcher    : MessageReceiver failed to processes)

### Cloud Provider(s):
Google, GKE

### Environment:
Spinnaker versions: 1.17.1, 1.17.6 and 1.18.2 (I tested with 3 versions)

### Feature Area:
spin-echo, pub/sub trigger

### Description:
According to Google support, all  test messages which I published were received and all three remained unacked until they expired after the default 7d. They received multiple modifications of the ACK deadline (possible Nacks based on the error message), but not a single ACK. Therefore, since there's no ACK, my jobs aren't accepting the messages and Pub/Sub kept redelivering. As per the PubSub Engineering Team everything looks to be working as intended from Google side and it would be an issue with Spinnaker or some configuration regarding the messages ACK. 

### Error message:

Example of error message ( kubectl logs spin-echo-7f8b88c556-wpvcn -n spinnaker). In that case, Spinnaker 1.17.1 but the same type of errors I noticed for other tested versions.

2020-01-28 08:04:22.781  WARN 1 --- [          Gax-5] c.g.cloud.pubsub.v1.MessageDispatcher    : MessageReceiver failed to processes ack ID: CypYEU4EISE-MD5FU0RQBhYsXUZIUTcZCGhRDk9eIz81IChFFwggbw8_QloZYmhcXHUHUAtPJy9jJD9fEQIIRVl-d2s5Mm9YVHIGUggQdXhicWtZFCn4sNL-1_WBPHJgZMPh3swsUpnKyaloZh89WxJLLD5-PTNFQV5AEkw2BkRJUytD, the message will be nacked.

java.lang.NullPointerException: null
        at com.netflix.spinnaker.kork.jedis.telemetry.TelemetryHelper.payloadSize(TelemetryHelper.java:60) ~[kork-jedis-6.15.1.jar:6.15.1]
        at com.netflix.spinnaker.kork.jedis.telemetry.InstrumentedJedis.set(InstrumentedJedis.java:128) ~[kork-jedis-6.15.1.jar:6.15.1]
        at com.netflix.spinnaker.echo.pubsub.PubsubMessageHandler.lambda$acquireMessageLock$0(PubsubMessageHandler.java:133) ~[echo-pubsub-core.jar:na]
        at com.netflix.spinnaker.kork.jedis.JedisClientDelegate.withCommandsClient(JedisClientDelegate.java:46) ~[kork-jedis-6.15.1.jar:6.15.1]
        at com.netflix.spinnaker.echo.pubsub.PubsubMessageHandler.acquireMessageLock(PubsubMessageHandler.java:131) ~[echo-pubsub-core.jar:na]
        at com.netflix.spinnaker.echo.pubsub.PubsubMessageHandler.tryAck(PubsubMessageHandler.java:119) ~[echo-pubsub-core.jar:na]
        at com.netflix.spinnaker.echo.pubsub.PubsubMessageHandler.handleMessage(PubsubMessageHandler.java:103) ~[echo-pubsub-core.jar:na]
        at com.netflix.spinnaker.echo.pubsub.google.GooglePubsubSubscriber$GooglePubsubMessageReceiver.receiveMessage(GooglePubsubSubscriber.java:195) ~[echo-pubsub-google.jar:na]
        at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:368) ~[google-cloud-pubsub-1.78.0.jar:1.78.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_232]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232]

**Comment by ajordens** [comment] 2020-02-18 15:54
@ttomsu Thoughts on this stacktrace?

```
java.lang.NullPointerException: null
at com.netflix.spinnaker.kork.jedis.telemetry.TelemetryHelper.payloadSize(TelemetryHelper.java:60) ~[kork-jedis-6.15.1.jar:6.15.1]
at com.netflix.spinnaker.kork.jedis.telemetry.InstrumentedJedis.set(InstrumentedJedis.java:128) ~[kork-jedis-6.15.1.jar:6.15.1]
```

**Comment by ttomsu** [comment] 2020-02-18 18:41
Hi @klodnickik - Thanks for the bug report!

This definitely looks like a bug. For some background, we must support a use case where multiple Echo instances are running. Deliverying a pubsub message _exactly_ once is (apparently) very hard, and thus our code must be tolerant of a message being redelivered. 

Obviously we only want to react to the first message received and ignore any further ones. We built a locking mechanism within Redis where the Echo instance that receives the message attempts to acquire a Redis lock for that message (just a key & value). The value for that lock is the "identity" of the Echo instance that attempted to acquire it.

It's in this Identity code where I think this bug lives. As it's written, [this code](https://github.com/spinnaker/echo/blob/acc6e930c90a67a90b6f267885be9f64e62f61af/echo-pubsub-core/src/main/java/com/netflix/spinnaker/echo/pubsub/utils/NodeIdentity.java#L32)'s `getIdentity()` method _can_ return null if all attempts finding something more descriptive fail.

This null value is what I think is causing this `NullPointerException`

**Comment by ttomsu** [comment] 2020-02-18 18:50
@klodnickik Would you be able to test this out when it's merged? You should be able to try with `master-latest-unvalidated` a few hours after it's merged (you can ensure it's in there by inspecting the `master-latest-unvalidated` BOM for Echo's commit hash).

**Comment by ttomsu** [comment] 2020-02-19 14:29
@klodnickik Would you be able to test out this change now that it's merged?

**Closed** 2020-02-19 14:29 UTC
Labels: provider/gce, sig/none

**Comment by klodnickik** [comment] 2020-02-19 14:33
@ttomsu  When you are working on the fix, I started preparation for tests. However, it looks that I would need some help / guidlines.

**How can I use code from master-latest-unvalidated branch in Distributed installation type?** it looks that Halyard supports it only for LocalGit.

The Pub/Sub bug materialzed in GKE cluster with Distributed installation type. So, I assume that it does not make sense to test it in local installation ..

```
$ hal config version edit --version branch:upstream
+ Get current deployment
  Success
- Edit Spinnaker version
  Failure
Validation in default:
! ERROR You can't run Spinnaker from a branch when your deployment
  type isn't "LocalGit".
```


if possible, I could use also Docker image with updated version of code. However, I am not able to build it...

$ docker build -f Dockerfile.java8  .

[...]

Step 3/6 : COPY --from=compile /compiled_sources/echo-web/build/install/echo /opt/echo
invalid from flag value compile: pull access denied for compile, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ttomsu** [comment] 2020-02-19 15:51
If the bug happened in your Distributed environment, then yes that would be the best place to reproduce it. 

You'll need to do a two step process to get a local build going. @plumpy is making it better with https://github.com/spinnaker/echo/pull/783. Try this for now (the PR isn't submitted so these instructions may only work for a limited amount of time):

```
git fetch origin refs/pull/783/head
git checkout -b plumpy/container_builds FETCH_HEAD

./gradlew echo-web:installDist -x test && docker build -f Dockerfile.java8 .
```

**Comment by klodnickik** [comment] 2020-02-19 16:39
Thank you!!!!! The fix works! 
When it would be included in official 1.18 version?

```
2020-02-19 16:32:04.507  INFO 1 --- [pool-2-thread-1] c.n.s.e.p.orca.OrcaService               : <--- HTTP 200 http://spin-orca.spinnaker:8083/orchestrate (399ms)
> 2020-02-19 16:32:04.512  INFO 1 --- [pool-2-thread-1] c.n.s.e.p.orca.PipelineInitiator         : **Successfully triggered Pipeline**(gencorp-microservice-ur-janrainlookupservice, Deploy to Develop, 559d21ed-5ffb-4495-baa9-8f975cee681e): execution id: /pipelines/01E1F4NJ5DGPDEX0G88KCSCVT8
 
```

**Comment by ttomsu** [comment] 2020-02-19 17:53
Wonderful! I'll get it cherry picked into 1.18 now.

**Comment by dpkirchner** [comment] 2020-03-17 21:01
Based on what I see in the commit, the change does resolve the NPE but not the underlying error. That is, if we saw the NPE before, now we'll see errors mentioning UnknownHost. Is that correct?

If so, is there a workaround for the UnknownHost issue besides restarting the service? Is this error happening because echo was unable to look up a necessary hostname at some point and the Java resolver (IIRC, known to be buggy-by-design) caches the resolve error forever?
