### ISSUE TITLE
Bake (Manifest) Configuration not showing Artifact Account drop down selection 

### ISSUE THREAD

**Issue by asanami** [spinnaker/spinnaker#4930] opened 2019-09-19 07:49 UTC
### Issue Summary:

When creating a new Bake (Manifest) configuration and after selecting an expected Artifact, the UI does not allow (or even show) the drop down list for selecting an Artifact Account as per user docs

### Cloud Provider(s):

Kubernetes

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

UI/UX

### Steps to Reproduce:

1. Configure the an S3 expected artifact matching against an S3 object path.  E.g.

```
s3://bucket/logserver/logserver-0.0.1.tgz
```

2. Create a Bake (Manifest) configuration using the Helm template

### Additional Details:

---

**Comment by ethanfrogers** [comment] 2019-09-19 11:57
@asanami could you provide a screenshot? Also, do you have `artifactsRewrite` enabled?

**Comment by maggieneterval** [comment] 2019-09-19 15:18
And what version of Spinnaker are you running? Thanks!

**Comment by Tediferous** [comment] 2019-09-25 20:03
I am also running into this error on spinnaker 1.16.1
To get around this error I had to manually add my artifact account to the pipeline json
related: https://github.com/spinnaker/spinnaker/issues/4737#issuecomment-529713975

**Comment by ethanfrogers** [comment] 2019-10-31 11:39
This appears to have been fixed in newer releases but is also a duplicate of #4737 . Let's move future conversation to that issue.

**Closed by ethanfrogers** 2019-10-31 11:39 UTC
Labels: provider/kubernetes-v2, sig/kubernetes
