### ISSUE TITLE
nodeSelector is not updated when cloning a server group template

### ISSUE THREAD

**Issue by jrcast** [spinnaker/spinnaker#1561] opened 2017-04-12 14:37 UTC
When using kubernetes as the cloud provider, the node selector seems to stay empty when cloning the server group template. This means when your first deploy the server group, it runs OK, but when you deploy a new server group using ~~'clone'~~ (I just noticed that the nodeSelector is updated correctly when using clone, but not when using deploy step) or a 'deploy' step in a pipeline the server group will run anywhere. 

I am running spinnaker using AWS AMI

Steps to reproduce:

1- create server group + add a node selector label
2- wait for it to create
3- clone the server group. Note that node selector is empty

**Comment by jcastillo-cb** [comment] 2017-04-12 17:17
I just noticed that the nodeSelector is updated correctly when using clone, but not when using a deploy step

**Comment by danielpeach** [comment] 2017-04-27 17:32
I'm not able to reproduce this:
- I'm able to create a server group with a `nodeSelector` map, and the map is copied over when I clone that server group.
- I'm able to create / edit / copy a server group with a `nodeSelector` map in a pipeline deploy stage, and when I run the pipeline, the resulting server group has the correct `nodeSelector` properties.

Could this be a duplicate of https://github.com/spinnaker/spinnaker/issues/1557?

**Comment by jrcast** [comment] 2017-04-28 00:36
Yes as per my previous comment, it works when you hit clone. The copy part is the affected one. So yes, this is a dup of #1557

**Comment by lwander** [comment] 2017-06-07 22:20
Dupe of a closed issue

**Closed by lwander** 2017-06-07 22:20 UTC
