### ISSUE TITLE
Front-50 Resource controller pods is always in "CrashLoopbackoff"

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1042] opened 2016-08-01 22:00 UTC
Please provide:

_Title_

Front-50 Resource controller pods is always in "CrashLoopbackoff"

_Cloud Provider_

Kubernetes

_Environment_

I am using experimental Kubernetes bash script. 

_Feature Area_

Front-50 service in spinnaker

_Description_

Today when I ran bash scripts/startup-spinnaker.sh, all rcs are started successfully except front-50.
# When I do "kubectl logs" for the pods. I see below error

Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationsController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.netflix.spinnaker.front50.model.application.ApplicationDAO com.netflix.spinnaker.front50.controllers.ApplicationsController.applicationDAO; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.netflix.spinnaker.front50.model.application.ApplicationDAO] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
        at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
#         at com.netflix.spinnaker.front50.Main.main(Main.groovy:47)

_Steps to Reproduce_
Run "kubectl create -f rcs/spin-front50.yaml" and it shows pods in error state and keeps restarting.
All pods,services,rcs were working fine till 7/29.

_Additional Details_

**Comment by duftler** [comment] 2016-08-01 22:02
@lwander

**Comment by lwander** [comment] 2016-08-03 19:00
Thanks for the detailed report. Have you configured the front50 pod to use GCS? You likely need to add a storage scope to your GCP service account.  https://cloud.google.com/iam/docs/understanding-roles (sorry this is missing from the startup docs, I'm adding that now).

**Comment by mickfeech** [comment] 2016-08-03 19:05
I'm also getting a similar error with redis.

```
  front50:
    host: spin-front50.spinnaker.svc.cluster.local
    port: 8080
    baseUrl: ${services.default.protocol}://${services.front50.host}:${services.front50.port}

    # If using storage bucket persistence (gcs or s3), specify the bucket here
    # disable cassandra and enable the storage service below.
    #storage_bucket: # Needs to be a globally unique name. Pick something clever.
    #bucket_root: front50

    cassandra:
      enabled: true
    redis:
      enabled: true
    gcs:
      enabled: false # Enable me
    #  project: # Set me
    s3:
      enabled: false # Or me
```

```
2016-08-03 19:04:54.873  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'pollingScheduler' of type [class com.netflix.config.FixedDelayPollingScheduler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-08-03 19:04:54.877  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'polledConfigurationSource' of type [class com.netflix.spinnaker.kork.archaius.SpringEnvironmentPolledConfigurationSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-08-03 19:04:55.693  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2016-08-03 19:04:55.697  INFO 1 --- [           main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2016-08-03 19:04:59.355  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2016-08-03 19:05:00.582  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2016-08-03 19:05:00.583  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.23
2016-08-03 19:05:01.091  INFO 1 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2016-08-03 19:05:01.092  INFO 1 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 14591 ms
2016-08-03 19:05:03.404  INFO 1 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2016-08-03 19:05:03.423  INFO 1 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'simpleCORSFilter' to: [/*]
2016-08-03 19:05:03.424  INFO 1 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'metricFilter' to: [/*]
2016-08-03 19:05:03.424  INFO 1 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-08-03 19:05:03.424  INFO 1 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-08-03 19:05:03.431  INFO 1 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2016-08-03 19:05:03.432  INFO 1 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'applicationContextIdFilter' to: [/*]
2016-08-03 19:05:03.801  WARN 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationsController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.netflix.spinnaker.front50.model.application.ApplicationDAO com.netflix.spinnaker.front50.controllers.ApplicationsController.applicationDAO; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.netflix.spinnaker.front50.model.application.ApplicationDAO] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2016-08-03 19:05:03.856  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2016-08-03 19:05:03.953  INFO 1 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [file:/opt/front50/config/, file:/opt/front50/lib/front50-web-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/groovy-all-2.3.11.jar, file:/opt/front50/lib/front50-core-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/front50-cassandra-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/front50-gcs-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/front50-redis-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/front50-s3-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/front50-pipelines-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/front50-migrations-1.33.0-SNAPSHOT.jar, file:/opt/front50/lib/spring-boot-starter-actuator-1.2.5.RELEASE.jar, file:/opt/front50/lib/spring-boot-starter-web-1.2.5.RELEASE.jar, file:/opt/front50/lib/spring-boot-starter-data-rest-1.2.5.RELEASE.jar, file:/opt/front50/lib/kork-web-1.66.0.jar, file:/opt/front50/lib/kork-swagger-1.66.0.jar, file:/opt/front50/lib/kork-core-1.66.0.jar, file:/opt/front50/lib/kork-cassandra-1.66.0.jar, file:/opt/front50/lib/google-api-services-compute-alpha-rev5-1.22.0.jar, file:/opt/front50/lib/google-api-services-storage-v1-rev72-1.22.0.jar, file:/opt/front50/lib/spring-data-redis-1.7.1.RELEASE.jar, file:/opt/front50/lib/jedis-2.8.1.jar, file:/opt/front50/lib/clouddriver-aws-1.85.0.jar, file:/opt/front50/lib/sshoogr-0.9.15.jar, file:/opt/front50/lib/spring-boot-starter-1.2.5.RELEASE.jar, file:/opt/front50/lib/spring-boot-actuator-1.2.5.RELEASE.jar, file:/opt/front50/lib/spring-boot-starter-tomcat-1.2.5.RELEASE.jar, file:/opt/front50/lib/spring-web-4.1.7.RELEASE.jar, file:/opt/front50/lib/spring-webmvc-4.1.7.RELEASE.jar, file:/opt/front50/lib/spring-data-rest-webmvc-2.2.3.RELEASE.jar, file:/opt/front50/lib/kork-security-1.66.0.jar, file:/opt/front50/lib/spring-security-core-3.2.8.RELEASE.jar, file:/opt/front50/lib/spectator-api-0.36.0.jar, file:/opt/front50/lib/okhttp-2.7.0.jar, file:/opt/front50/lib/retrofit-1.9.0.jar, file:/opt/front50/lib/guava-15.0.jar, file:/opt
/front50/lib/spring-boot-autoconfigure-1.2.5.RELEASE.jar, file:/opt/front50/lib/springfox-swagger2-2.2.2.jar, file:/opt/front50/lib/springfox-swagger-ui-2.2.2.jar, file:/opt/front50/lib/swagger-annotations-1.3.13.jar, file:/opt/front50/lib/archaius-core-0.7.3.jar, file:/opt/front50/lib/eureka-client-1.4.6.jar, file:/opt/front50/lib/aws-java-sdk-core-1.10.68.jar, file:/opt/front50/lib/spectator-ext-aws-0.36.0.jar, file:/opt/front50/lib/spectator-ext-gc-0.36.0.jar, file:/opt/front50/lib/spectator-ext-jvm-0.36.0.jar, file:/opt/front50/lib/astyanax-cql-3.8.0.jar, file:/opt/front50/lib/astyanax-cassandra-3.8.0.jar, file:/opt/front50/lib/astyanax-thrift-3.8.0.jar, file:/opt/front50/lib/astyanax-test-3.8.0.jar, file:/opt/front50/lib/google-api-client-1.22.0.jar, file:/opt/front50/lib/spring-data-keyvalue-1.1.1.RELEASE.jar, file:/opt/front50/lib/spring-oxm-4.2.5.RELEASE.jar, file:/opt/front50/lib/spring-aop-4.2.5.RELEASE.jar, file:/opt/front50/lib/spring-context-support-4.2.5.RELEASE.jar, file:/opt/front50/lib/slf4j-api-1.7.19.jar, file:/opt/front50/lib/jcl-over-slf4j-1.7.19.jar, file:/opt/front50/lib/commons-pool2-2.4.2.jar, file:/opt/front50/lib/clouddriver-core-1.85.0.jar, file:/opt/front50/lib/aws-java-sdk-1.10.27.jar, file:/opt/front50/lib/awsobjectmapper-1.10.27.0.jar, file:/opt/front50/lib/httpclient-4.3.6.jar, file:/opt/front50/lib/httpcore-4.3.3.jar, file:/opt/front50/lib/okhttp-urlconnection-2.7.0.jar, file:/opt/front50/lib/okhttp-apache-2.7.0.jar, file:/opt/front50/lib/converter-jackson-1.9.0.jar, file:/opt/front50/lib/frigga-0.13.jar, file:/opt/front50/lib/commons-codec-1.9.jar, file:/opt/front50/lib/jsch-0.1.50.jar, file:/opt/front50/lib/commons-io-1.4.jar, file:/opt/front50/lib/spring-boot-1.2.5.RELEASE.jar, file:/opt/front50/lib/spring-boot-starter-logging-1.2.5.RELEASE.jar, file:/opt/front50/lib/snakeyaml-1.14.jar, file:/opt/front50/lib/commons-logging-1.2.jar, file:/opt/front50/lib/tomcat-embed-core-8.0.23.jar, file:/opt/front50/lib/tomcat-embed-el-8.0.23.jar, file:/opt/front50/lib/tomcat-embed-logging-j
uli-8.0.23.jar, file:/opt/front50/lib/tomcat-embed-websocket-8.0.23.jar, file:/opt/front50/lib/spring-data-rest-core-2.2.3.RELEASE.jar, file:/opt/front50/lib/json-patch-1.7.jar, file:/opt/front50/lib/aopalliance-1.0.jar, file:/opt/front50/lib/okio-1.6.0.jar, file:/opt/front50/lib/gson-2.3.1.jar, file:/opt/front50/lib/mapstruct-1.0.0.CR1.jar, file:/opt/front50/lib/swagger-annotations-1.5.3.jar, file:/opt/front50/lib/swagger-models-1.5.3.jar, file:/opt/front50/lib/springfox-spi-2.2.2.jar, file:/opt/front50/lib/springfox-schema-2.2.2.jar, file:/opt/front50/lib/springfox-swagger-common-2.2.2.jar, file:/opt/front50/lib/springfox-spring-web-2.2.2.jar, file:/opt/front50/lib/classmate-1.2.0.jar, file:/opt/front50/lib/aspectjrt-1.8.6.jar, file:/opt/front50/lib/aspectjweaver-1.8.6.jar, file:/opt/front50/lib/spring-plugin-core-1.2.0.RELEASE.jar, file:/opt/front50/lib/spring-plugin-metadata-1.2.0.RELEASE.jar, file:/opt/front50/lib/spring-hateoas-0.18.0.RELEASE.jar, file:/opt/front50/lib/astyanax-core-3.8.0.jar, file:/opt/front50/lib/cassandra-driver-core-2.0.6.jar, file:/opt/front50/lib/netty-3.9.0.Final.jar, file:/opt/front50/lib/lz4-1.2.0.jar, file:/opt/front50/lib/metrics-core-3.0.2.jar, file:/opt/front50/lib/snappy-java-1.0.5.jar, file:/opt/front50/lib/cassandra-all-2.0.12.jar, file:/opt/front50/lib/jackson-mapper-asl-1.9.2.jar, file:/opt/front50/lib/cassandra-thrift-2.0.12.jar, file:/opt/front50/lib/org.apache.servicemix.bundles.commons-csv-1.0-r706900_3.jar, file:/opt/front50/lib/libthrift-0.9.1.jar, file:/opt/front50/lib/astyanax-contrib-3.8.0.jar, file:/opt/front50/lib/astyanax-recipes-3.8.0.jar, file:/opt/front50/lib/astyanax-queue-3.8.0.jar, file:/opt/front50/lib/astyanax-entity-mapper-3.8.0.jar, file:/opt/front50/lib/junit-4.8.1.jar, file:/opt/front50/lib/persistence-api-1.0.jar, file:/opt/front50/lib/commons-lang-2.6.jar, file:/opt/front50/lib/google-oauth-client-1.22.0.jar, file:/opt/front50/lib/guava-jdk5-17.0.jar, file:/opt/front50/lib/spring-data-commons-1.12.0.RELEASE.jar, file:/opt/front50/lib/cats-core-1.8
5.0.jar, file:/opt/front50/lib/cats-redis-1.85.0.jar, file:/opt/front50/lib/clouddriver-security-1.85.0.jar, file:/opt/front50/lib/aws-java-sdk-support-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-simpledb-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-simpleworkflow-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-storagegateway-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-route53-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-s3-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-importexport-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-sts-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-sqs-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-rds-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-redshift-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-elasticbeanstalk-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-glacier-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-iam-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-datapipeline-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-elasticloadbalancing-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-emr-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-elasticache-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-elastictranscoder-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-ec2-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-dynamodb-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-sns-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cloudtrail-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cloudwatch-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-logs-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cognitoidentity-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cognitosync-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-directconnect-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cloudformation-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cloudfront-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-kinesis-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-opsworks-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-ses-1.10.27.jar, file:/opt/front50/lib/aws-java-sd
k-autoscaling-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cloudsearch-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cloudwatchmetrics-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-swf-libraries-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-codedeploy-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-codepipeline-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-kms-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-config-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-lambda-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-ecs-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-cloudhsm-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-ssm-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-workspaces-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-machinelearning-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-directory-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-efs-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-codecommit-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-devicefarm-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-elasticsearch-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-waf-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-marketplacecommerceanalytics-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-inspector-1.10.27.jar, file:/opt/front50/lib/aws-java-sdk-iot-1.10.27.jar, file:/opt/front50/lib/jul-to-slf4j-1.7.12.jar, file:/opt/front50/lib/log4j-over-slf4j-1.7.12.jar, file:/opt/front50/lib/evo-inflector-1.2.jar, file:/opt/front50/lib/jackson-coreutils-1.6.jar, file:/opt/front50/lib/springfox-core-2.2.2.jar, file:/opt/front50/lib/high-scale-lib-1.1.2.jar, file:/opt/front50/lib/uuid-3.2.jar, file:/opt/front50/lib/compress-lzf-0.8.4.jar, file:/opt/front50/lib/commons-cli-1.1.jar, file:/opt/front50/lib/commons-lang3-3.1.jar, file:/opt/front50/lib/concurrentlinkedhashmap-lru-1.3.jar, file:/opt/front50/lib/antlr-3.2.jar, file:/opt/front50/lib/jackson-core-asl-1.9.2.jar, file:/opt/front50/lib/jline-1.0.jar, file:/opt/front50/lib/json-simple-1.1.jar, file:/opt/front50/lib/snaptree-0.1.jar, file:/opt/fron
t50/lib/jbcrypt-0.3m.jar, file:/opt/front50/lib/metrics-core-2.2.0.jar, file:/opt/front50/lib/reporter-config-2.1.0.jar, file:/opt/front50/lib/thrift-server-0.3.7.jar, file:/opt/front50/lib/super-csv-2.1.0.jar, file:/opt/front50/lib/log4j-1.2.16.jar, file:/opt/front50/lib/jamm-0.2.5.jar, file:/opt/front50/lib/stax-api-1.0.1.jar, file:/opt/front50/lib/msg-simple-1.1.jar, file:/opt/front50/lib/disruptor-3.0.1.jar, file:/opt/front50/lib/btf-1.2.jar, file:/opt/front50/lib/antlr-2.7.7.jar, file:/opt/front50/lib/hibernate-validator-5.2.2.Final.jar, file:/opt/front50/lib/validation-api-1.1.0.Final.jar, file:/opt/front50/lib/jboss-logging-3.2.1.Final.jar, file:/opt/front50/lib/spring-tx-4.2.5.RELEASE.jar, file:/opt/front50/lib/rxjava-1.0.16.jar, file:/opt/front50/lib/jackson-core-2.5.4.jar, file:/opt/front50/lib/jackson-databind-2.5.4.jar, file:/opt/front50/lib/spring-beans-4.2.5.RELEASE.jar, file:/opt/front50/lib/spring-context-4.2.5.RELEASE.jar, file:/opt/front50/lib/spring-core-4.2.5.RELEASE.jar, file:/opt/front50/lib/spring-expression-4.2.5.RELEASE.jar, file:/opt/front50/lib/google-http-client-jackson2-1.22.0.jar, file:/opt/front50/lib/netflix-eventbus-0.3.0.jar, file:/opt/front50/lib/xstream-1.4.2.jar, file:/opt/front50/lib/jsr311-api-1.1.1.jar, file:/opt/front50/lib/servo-core-0.10.1.jar, file:/opt/front50/lib/jersey-core-1.19.jar, file:/opt/front50/lib/jersey-client-1.19.jar, file:/opt/front50/lib/jersey-apache-client4-1.19.jar, file:/opt/front50/lib/guice-4.0.jar, file:/opt/front50/lib/governator-api-1.12.10.jar, file:/opt/front50/lib/netflix-infix-0.3.0.jar, file:/opt/front50/lib/commons-math-2.2.jar, file:/opt/front50/lib/xmlpull-1.1.3.1.jar, file:/opt/front50/lib/xpp3_min-1.1.4c.jar, file:/opt/front50/lib/javax.inject-1.jar, file:/opt/front50/lib/commons-jxpath-1.3.jar, file:/opt/front50/lib/jackson-dataformat-cbor-2.5.3.jar, file:/opt/front50/lib/logback-classic-1.1.3.jar, file:/opt/front50/lib/commons-configuration-1.8.jar, file:/opt/front50/lib/google-http-client-1.22.0.jar, file:/opt/front50/lib/jsr305-3.0
.1.jar, file:/opt/front50/lib/jackson-annotations-2.5.4.jar, file:/opt/front50/lib/jettison-1.3.7.jar, file:/opt/front50/lib/annotations-2.0.0.jar, file:/opt/front50/lib/servo-internal-0.10.1.jar, file:/opt/front50/lib/joda-time-2.8.1.jar, file:/opt/front50/lib/antlr-runtime-3.4.jar, file:/opt/front50/lib/logback-core-1.1.3.jar, file:/opt/front50/lib/stringtemplate-3.2.1.jar]
2016-08-03 19:05:03.961  INFO 1 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)


2016-08-03 19:05:03.971 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
```

**Comment by veeresh1982** [comment] 2016-08-03 19:50
@lwander:
I have used S3 bucket storage instead of GCS and configured in the spinnaker-local.yml as below
============================================================
  front50:
    host: spin-front50.spinnaker.svc.cluster.local
    port: 8080
    baseUrl: ${services.default.protocol}://${services.front50.host}:${services.front50.port}

    # If using storage bucket persistence (gcs or s3), specify the bucket here
    # disable cassandra and enable the storage service below.
    storage_bucket: mybucketname # Needs to be a globally unique name. Pick something clever.
    bucket_root: front50

    cassandra:
      enabled: false
    redis:
      enabled: false
    gcs:
      enabled: false # Enable me
      project: # Set me
    s3:
      enabled: true # Or me
============================================================
Today also I see the error happening for front50 and clouddriver and orca pods still in "ContainerCreating" state. Please see below

#kubectl get rc,pods,services --namespace=spinnaker
NAME                           DESIRED         CURRENT             AGE
data-redis-master-v000         1               1                   5h
spin-clouddriver-v000          1               1                   5h
spin-deck-v000                 1               1                   5h
spin-echo-v000                 1               1                   5h
spin-front50-v000              1               1                   5h
spin-gate-v000                 1               1                   5h
spin-igor-v000                 1               1                   5h
spin-orca-v000                 1               1                   5h
NAME                           READY           STATUS              RESTARTS   AGE
data-redis-master-v000-wbhz6   1/1             Running             0          5h
spin-clouddriver-v000-ac19z    0/1             ContainerCreating   0          5h
spin-deck-v000-mhw1w           1/1             Running             0          5h
spin-echo-v000-rk33s           1/1             Running             0          5h
spin-front50-v000-tc7fd        0/1             ImagePullBackOff    0          5h
spin-gate-v000-cf64m           1/1             Running             0          5h
spin-igor-v000-5nhzk           1/1             Running             0          5h
spin-orca-v000-7ax36           0/1             ContainerCreating   0          5h
NAME                           CLUSTER-IP      EXTERNAL-IP         PORT(S)    AGE
data-redis-server              10.233.39.3     <none>              6379/TCP   5h
spin-clouddriver               10.233.20.174   <none>              7002/TCP   5h
spin-deck                      10.233.57.147   <nodes>             9000/TCP   5h
spin-echo                      10.233.55.130   <none>              8089/TCP   5h
spin-front50                   10.233.40.235   <none>              8080/TCP   5h
spin-gate                      10.233.59.16    <none>              8084/TCP   5h
spin-igor                      10.233.32.252   <none>              8088/TCP   5h
spin-orca                      10.233.1.59     <none>              8083/TCP   5h

**Comment by veeresh1982** [comment] 2016-08-04 23:28
I am able to have all my spinnaker services running fine today. I have not find the exact issue though. We had some internal firewall related changes (which was reverted back today)  and seems to have all my services up and running fine. I checked all the container logs and seems to be all OK.

@mickfeech : Are you still seeing the redis issue ?

**Comment by mickfeech** [comment] 2016-08-05 13:20
I think my issues may be related to #1038

**Comment by dberuben** [comment] 2016-09-15 16:12
+1 i have the same issue !

**Comment by plombardi89** [comment] 2016-10-30 00:08
@lwander The problem is that the Spinnaker guide sets the scope as `compute.storageAdmin` which is for managing GCE disks. I am pretty sure you want `storage.admin` which is for GCS. 

Fragment in question:
```bash
gcloud projects add-iam-policy-binding $PROJECT \
    --role roles/compute.storageAdmin --member serviceAccount:$SA_EMAIL
```

I ended up setting it via the UI after I noticed tons of CrashBackoff stuff after `setup-all.sh`

**Comment by lwander** [comment] 2016-10-31 13:10
Good call @plombardi89, would you like to take the credit and update the docs in here? https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple#gcr

**Comment by plombardi89** [comment] 2016-11-03 15:28
@lwander Yea I'll try and take it minute to do it this afternoon.

**Comment by lwander** [comment] 2017-06-07 22:54
Closing since all future config should be done via [halyard](https://www.spinnaker.io/setup/install/halyard/). If you run into issue ping us in http://join.spinnaker.io, or file a bug on https://github.com/spinnaker/halyard/issues

**Closed by lwander** 2017-06-07 22:54 UTC
