### ISSUE TITLE
Default VPC for cloudDriver

### ISSUE THREAD

**Issue by mattmauriello** [spinnaker/spinnaker#630] opened 2015-11-27 17:53 UTC
If there is no default VPC defined in an AWS account, CloudDriver exits and makes other services non functional (gate starts responding with too many requests error and UI locks up).
I've not been able to find a location where a default VPC can be specified, and I didn't see anything obvious in the yaml for configuring that value.

I'm currently running Spinnaker in the same account that it would manage, using credentials from the instance profile.

**Comment by tomaslin** [comment] 2015-11-27 18:32
We have seen this with one other person who was trying Spinnaker. Their issue was that the default vpc in one of their regions was deleted and they had to restore this via contacting help desk. 

https://aws.amazon.com/premiumsupport/knowledge-center/deleted-default-vpc/

**Comment by mattmauriello** [comment] 2015-11-30 18:03
We removed our default subnets intentionally and created new ones so we could better plan and allocate our CIDR ranges along side our on premise infrastructure. It also helps us mitigate un-intentional mistakes by requiring that all the fields are submitted for a request, rather than making a default assumption. If there currently isn't a way to specify a default subnetID for cloudDriver, its definitely something we'd love to see.

**Comment by varun1308** [comment] 2015-12-04 17:14
Facing the same problem with our setup... Please do provide a fix soon.
Many thanks in advance.

**Comment by webratz** [comment] 2015-12-11 14:22
I'm also facing this issue in my test account

**Comment by Jason733i** [comment] 2015-12-15 20:22
Also facing this issue right now.  Ideally we would be able to use Spinnaker across multiple VPCs.

**Comment by alustenberg** [comment] 2015-12-23 17:51
hopping on the train, ran into this while evaluating.  same boat as @mattmauriello, no default VPC is by design.

**Comment by pdehlke** [comment] 2015-12-28 16:13
Really? Only works in the default VPC *again*? This is a pattern with NetflixOSS software- Priam only works in the default VPC, asgard is barely functional if it's not in the default VPC, etc. And this is not clearly documented anywhere- you sort of have to experience a lot of failure, hair-pulling, and googling before it hits you.

It would be, you know, really, really great if 

1) All NetflixOSS software could be *very clearly* documented, in the first paragraph of the README and the getting started guides, that this stuff only works in the default VPC.
2) There was some sort of documentation about how successful users of the NetflixOSS stack manage their VPC infrastructures, and cross-account access if they use multiple VPCs in the same regions.

**Comment by cfieber** [comment] 2015-12-28 17:49
we have a custom (non default VPC), default vpc is not a requirement, however we do have some vpc and subnet naming requirements

On the vpc's Name tag, give it a name that doesn't include a `.` character (e.g. `myvpc`)
In the Name tag of each subnet, give it a name that follows `vpcname.subnetpurpose.availability-zone` - e.g. `myvpc.internal.us-west-2a`

subnet purpose is what is presented to the user in the deploy dialogue, and all subnets with that purpose are assigned to the ASG.

we typically have `internal` for the primary subnet where a public IP is not the default, and `external` for the subnet that has public IP by default

Can you confirm you have the vpc and subnets tagged correctly and are still seeing problems. If so can you provide the stack trace you are seeing when clouddriver exits

**Comment by zentavr** [comment] 2016-01-05 00:40
Any updates about that issue? Unfortunately, it becomes a big deal when we are in the sevaral regions, and everywhere the VPCs has 172.31/16 networks :( We dropped the 'default' VPCs in order not to mix the subnets (unfortunately, we cannot re-assign the subnets for the VPCs).

**Comment by aglover** [comment] 2016-01-05 03:19
@mattmauriello see @cfieber's comment regarding tagging above -- does this rectify things for you?

**Comment by cfieber** [comment] 2016-01-05 05:02
from Slack: @zentavr confirmed proper tagging on subnets and still seeing the error

I'll see if I can repro in a fresh AWS account by deleting the default VPC and go from there

**Comment by zentavr** [comment] 2016-01-05 19:06
@cfieber  - I asked AWS support to recreate the default VPC, so Spinnaker works now.

**Closed** 2016-01-05 21:28 UTC

**Comment by clebio** [comment] 2016-07-13 01:49
I don't understand how the merged commit resolves this issue, but believe I'm experiencing the problem. I have two VPCs, one which, while not named "default", is presumably the original default, since that's the only one whose security groups Spinnaker is showing me (aren't legacy systems grand?).

Is there a work-around or a way to explicitly set the VPC (ID) for Spinnaker? It seems like `/opt/spinnaker/config/orca.yml` might be it, but not sure what I need to clear/restart to get it to update. Thanks in advance!

**Comment by ajordens** [comment] 2016-07-13 06:15
@clebio Just to confirm, your VPC subnets are named according to http://www.spinnaker.io/docs/troubleshooting-guide#section-i-don-t-see-my-vpcs-in-any-of-the-dropdowns-?

**Comment by clebio** [comment] 2016-07-13 13:38
Well, as much as I've been using that exact page, I am sad to say I missed that part. I've added `immutable_metadata {"purpose": "internal"}` to the private subnets of the particular VPC and restarted Spinnaker as well as refreshed caches in the UI, but still don't find the security groups I expect. The older VPC still exists and I see security groups from there.

Is there anything further to do to clear caches or resync the available security groups?
Would the presence of two VPCs, one being the original "default" impact this?

I can try in another account or region I have, but will take a bit of setup. Thanks for your help!
