### ISSUE TITLE
Gate: there is no reservations endpoint

### ISSUE THREAD

**Issue by tomaslin** [spinnaker/spinnaker#641] opened 2015-12-03 16:28 UTC
reservation reports don't have an endpoint but we reference it in deck

**Comment by anotherchrisberry** [comment] 2015-12-03 16:45
It's only referenced in the Netflix overrides. The problem is figuring out why folks are getting the Netflix-specific code included in Deck.

**Comment by duftler** [comment] 2015-12-03 17:11
Doesn't the checked-in app.js sill include the netflix module?
https://github.com/spinnaker/deck/blob/master/app/scripts/app.js#L10

It does not get rewritten as far as I know.

**Comment by anotherchrisberry** [comment] 2015-12-03 17:12
@duftler it does, but unless the `netflixMode` feature flag is set, the template overrides should not register: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/netflix/templateOverride/templateOverrides.module.js#L11

**Comment by duftler** [comment] 2015-12-03 17:19
Ah, forgot about that.

**Comment by AMeng** [comment] 2015-12-07 21:56
Seeing reservations in Spinnaker without needing to enable `netflixMode` would be nice.

**Comment by anotherchrisberry** [comment] 2015-12-16 20:55
Created an issue to optionally expose reservation reports here: https://github.com/spinnaker/spinnaker/issues/669

Closing this issue - we will track the work on making this functionality optional in the new issue.

**Closed by anotherchrisberry** 2015-12-16 20:55 UTC
