### ISSUE TITLE
Support External Account Configuration in clouddriver for GAE

### ISSUE THREAD

**Issue by guido9j** [spinnaker/spinnaker#5781] opened 2020-05-18 23:47 UTC
### Issue Summary: 
Support external account configuration in clouddriver for GAE (Google App Engine). 

### Cloud Provider(s): 
GCP

### Environment:
Our organization is running Spinnaker on GCP to deploy to GKE and GAE (other providers to be adopted in the near future). Our team supports 1,000's of engineers with 100's of Google projects and eventually supporting other clouds. We enable teams to deploy to production while complying with IT Controls/regulations, and providing self-service is key to our support model, so we never slow down our engineers.

### Feature Area:
Provider appengine
Component Clouddriver

### Description:
- Enable external account configuration in Spinnaker clouddriver for GAE
   - Store the account credentials in vault
   - Use these account credentials with GAE
   - Changes to account credentials in vault are read by clouddriver. Accounts are dynamic updated without restart.

Currently, external Account Configuration is only supported for Cloud Foundry and Kubernetes cloud provider accounts in clouddriver:
[spinnaker.io external account configuration](https://www.spinnaker.io/setup/configuration/#external-account-configuration)

**Comment by maggieneterval** [comment] 2020-05-19 18:02
Hi @guido9j, thanks for opening this feature request! It looks like this is a duplicate of https://github.com/spinnaker/spinnaker/issues/5781, so I'm going to close this issue so that we're only tracking this request in one place.

**Closed by maggieneterval** 2020-05-19 18:02 UTC
Labels: enhancement, provider/appengine, sig/none
